import type {SceneRichnessEntry} from '../../visual-system/sceneRichness';

export const GPT56_SCENE_RICHNESS: readonly SceneRichnessEntry[] = [
  {
    sceneId: 'gpt56-01',
    heroObjects: 2,
    supportElements: 6,
    brandAnchors: 1,
    meaningfulStateChanges: 4,
    microBeats: 4,
    depthLayers: 3,
    cameraMotion: 'push',
    visualMechanisms: ['brand-anchor', 'model-morph', 'calendar-impact', 'connector-flow'],
    intentionalWhitespace: false,
  },
  {
    sceneId: 'gpt56-02',
    heroObjects: 1,
    supportElements: 7,
    brandAnchors: 1,
    meaningfulStateChanges: 4,
    microBeats: 4,
    depthLayers: 4,
    cameraMotion: 'parallax',
    visualMechanisms: ['hero-orb', 'orbit-badges', 'speed-trails', 'brand-anchor'],
    intentionalWhitespace: false,
  },
  {
    sceneId: 'gpt56-03',
    heroObjects: 1,
    supportElements: 7,
    brandAnchors: 1,
    meaningfulStateChanges: 4,
    microBeats: 4,
    depthLayers: 4,
    cameraMotion: 'depth',
    visualMechanisms: ['hero-orb', 'task-network', 'code-window', 'brand-anchor'],
    intentionalWhitespace: false,
  },
  {
    sceneId: 'gpt56-04',
    heroObjects: 1,
    supportElements: 6,
    brandAnchors: 1,
    meaningfulStateChanges: 4,
    microBeats: 4,
    depthLayers: 3,
    cameraMotion: 'push',
    visualMechanisms: ['ui-state-machine', 'thinking-slider', 'brain-pulse', 'brand-anchor'],
    intentionalWhitespace: false,
  },
  {
    sceneId: 'gpt56-05',
    heroObjects: 1,
    supportElements: 6,
    brandAnchors: 0,
    meaningfulStateChanges: 4,
    microBeats: 4,
    depthLayers: 4,
    cameraMotion: 'pan',
    visualMechanisms: ['reasoning-ladder', 'unlock-state', 'depth-stack', 'premium-reveal'],
    intentionalWhitespace: false,
  },
  {
    sceneId: 'gpt56-06',
    heroObjects: 1,
    supportElements: 8,
    brandAnchors: 0,
    meaningfulStateChanges: 4,
    microBeats: 4,
    depthLayers: 3,
    cameraMotion: 'pull',
    visualMechanisms: ['plan-ladder', 'access-lines', 'feature-chips', 'tier-emphasis'],
    intentionalWhitespace: false,
  },
  {
    sceneId: 'gpt56-07',
    heroObjects: 2,
    supportElements: 8,
    brandAnchors: 1,
    meaningfulStateChanges: 5,
    microBeats: 5,
    depthLayers: 4,
    cameraMotion: 'push',
    visualMechanisms: ['prompt-branch', 'twin-chat', 'configuration-badges', 'result-contrast'],
    intentionalWhitespace: false,
  },
] as const;
