import type {AuthoredVisualScene} from '../../animation-library/authoredProductionGate';

export const GPT56_VISUAL_PROFILES: readonly AuthoredVisualScene[] = [
  {sceneId:'gpt56-01',visualId:'gpt56-model-swap-v1',fingerprint:{primaryPrimitive:'timeline',cameraMotion:'push',depthStyle:'layered-2d',entryMechanism:'replace',medium:'remotion-native',direction:'right-to-left',visualFamily:'current-model-swap',layoutFamily:'calendar-model-slot',motionSignature:'calendar-fold-old-eject-new-snap'}},
  {sceneId:'gpt56-02',visualId:'gpt56-luna-orbit-v1',fingerprint:{primaryPrimitive:'orbit',cameraMotion:'pan',depthStyle:'pseudo-3d',entryMechanism:'route',medium:'remotion-native',direction:'outside-in',visualFamily:'model-family',layoutFamily:'badges-orbit-core',motionSignature:'plans-route-orbit-speed-lines'}},
  {sceneId:'gpt56-03',visualId:'gpt56-sol-core-v1',fingerprint:{primaryPrimitive:'nodes',cameraMotion:'push',depthStyle:'pseudo-3d',entryMechanism:'assemble',medium:'remotion-native',direction:'radial-in',visualFamily:'capability-core',layoutFamily:'task-satellites-core',motionSignature:'core-grow-tasks-ingest-rays'}},
  {sceneId:'gpt56-04',visualId:'gpt56-thinking-slider-v1',fingerprint:{primaryPrimitive:'control',cameraMotion:'locked',depthStyle:'layered-2d',entryMechanism:'draw',medium:'remotion-native',direction:'left-to-right',visualFamily:'thinking-control',layoutFamily:'slider-rings',motionSignature:'track-draw-knob-travel-rings-grow'}},
  {sceneId:'gpt56-05',visualId:'gpt56-thinking-steps-v1',fingerprint:{primaryPrimitive:'steps',cameraMotion:'rise',depthStyle:'isometric',entryMechanism:'stack',medium:'remotion-native',direction:'bottom-to-top',visualFamily:'reasoning-levels',layoutFamily:'four-step-ladder',motionSignature:'steps-build-lock-pulse-unlock'}},
  {sceneId:'gpt56-06',visualId:'gpt56-plan-ladder-v1',fingerprint:{primaryPrimitive:'columns',cameraMotion:'pull',depthStyle:'layered-2d',entryMechanism:'grow',medium:'remotion-native',direction:'bottom-to-top',visualFamily:'plan-access',layoutFamily:'plan-columns-access-lines',motionSignature:'plus-mark-higher-columns-rise-access-connect'}},
  {sceneId:'gpt56-07',visualId:'gpt56-same-prompt-v1',fingerprint:{primaryPrimitive:'split-flow',cameraMotion:'push',depthStyle:'pseudo-3d',entryMechanism:'duplicate',medium:'remotion-native',direction:'center-out',visualFamily:'configuration-comparison',layoutFamily:'prompt-twin-lanes-equation',motionSignature:'prompt-copy-lanes-configure-responses-equation'}}
] as const;
