import React from 'react';
import {AbsoluteFill,interpolate,spring,useCurrentFrame,useVideoConfig} from 'remotion';
import {Archive,ArrowRight,CalendarDays,CheckCircle2,Download,Image,Images,PenTool,Sparkles,Trash2,WandSparkles} from 'lucide-react';
import {DALLE_PALETTE as C} from './contract';

const pop=(f:number,delay=0)=>spring({frame:f-delay,fps:30,config:{damping:14,stiffness:150,mass:.8}});
const fade=(f:number,a:number,b:number)=>interpolate(f,[a,b],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});
const card:React.CSSProperties={background:'rgba(255,255,255,.92)',border:'1px solid rgba(16,32,51,.09)',borderRadius:34,boxShadow:'0 24px 70px rgba(16,32,51,.12)'};
const Badge:React.FC<{children:React.ReactNode,bg:string,color:string}> = ({children,bg,color})=><div style={{display:'inline-flex',alignItems:'center',gap:10,padding:'12px 18px',borderRadius:999,background:bg,color,fontSize:26,fontWeight:900}}>{children}</div>;
const Feature:React.FC<{icon:React.ReactNode,title:string,sub:string,accent:string,delay:number}> = ({icon,title,sub,accent,delay})=>{const f=useCurrentFrame();const s=pop(f,delay);return <div style={{...card,padding:28,display:'flex',gap:20,alignItems:'center',opacity:s,transform:`translateY(${(1-s)*35}px) scale(${.95+.05*s})`}}><div style={{width:76,height:76,borderRadius:24,display:'grid',placeItems:'center',background:`${accent}18`,color:accent}}>{icon}</div><div><div style={{fontSize:31,fontWeight:950,color:C.ink}}>{title}</div><div style={{fontSize:24,fontWeight:650,color:'#536273',marginTop:6}}>{sub}</div></div></div>};

export const ShutdownVisual:React.FC=()=>{const f=useCurrentFrame();const s=pop(f,8);const stamp=pop(f,50);return <AbsoluteFill style={{background:'radial-gradient(circle at 20% 20%,#FFF8D8 0,transparent 32%),radial-gradient(circle at 86% 25%,#DDF9FC 0,transparent 34%),linear-gradient(180deg,#FBFDFF,#F3F7FB)'}}><div style={{position:'absolute',left:110,right:110,top:330,bottom:520,display:'grid',placeItems:'center'}}><div style={{...card,width:760,padding:42,opacity:s,transform:`scale(${.9+.1*s}) rotate(${(1-s)*-2}deg)`}}><div style={{display:'flex',alignItems:'center',gap:20}}><div style={{width:88,height:88,borderRadius:28,display:'grid',placeItems:'center',background:C.purpleSoft,color:C.purple}}><Sparkles size={46}/></div><div><div style={{fontSize:48,fontWeight:980,color:C.ink}}>DALL·E</div><div style={{fontSize:25,fontWeight:700,color:'#64748B'}}>Offizieller GPT in ChatGPT</div></div></div><div style={{height:1,background:'rgba(16,32,51,.08)',margin:'32px 0'}}/><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><Badge bg={C.redSoft} color={C.red}><CalendarDays size={28}/>30. AUGUST</Badge><div style={{fontSize:27,fontWeight:850,color:'#64748B'}}>wird eingestellt</div></div></div><div style={{position:'absolute',right:90,top:500,opacity:stamp,transform:`scale(${1.45-.45*stamp}) rotate(-8deg)`,border:`6px solid ${C.red}`,borderRadius:28,padding:'16px 24px',color:C.red,fontSize:42,fontWeight:1000,background:'rgba(255,255,255,.88)'}}>ENDE</div></div></AbsoluteFill>};

export const ImagesStayVisual:React.FC=()=>{const f=useCurrentFrame();const leave=fade(f,35,90);const stay=pop(f,58);return <AbsoluteFill style={{background:'radial-gradient(circle at 80% 18%,#DDF9FC 0,transparent 36%),linear-gradient(180deg,#FFFFFF,#F4FBFC)'}}><div style={{position:'absolute',left:72,right:72,top:330,display:'grid',gridTemplateColumns:'1fr 1fr',gap:28}}><div style={{...card,padding:30,opacity:1-leave*.65,transform:`translateX(${-150*leave}px) rotate(${-5*leave}deg)`}}><Badge bg={C.redSoft} color={C.red}><Trash2 size={26}/>verschwindet</Badge><div style={{fontSize:41,fontWeight:980,color:C.ink,marginTop:32}}>DALL·E-GPT</div><div style={{fontSize:24,fontWeight:650,color:'#64748B',marginTop:12}}>als eigener offizieller GPT</div></div><div style={{...card,padding:30,opacity:stay,transform:`scale(${.92+.08*stay})`,border:`2px solid ${C.cyan}44`}}><Badge bg={C.cyanSoft} color={C.cyan}><CheckCircle2 size={26}/>bleibt</Badge><div style={{display:'flex',alignItems:'center',gap:16,marginTop:32}}><Image size={48} color={C.cyan}/><div style={{fontSize:41,fontWeight:980,color:C.ink}}>ChatGPT Bilder</div></div><div style={{fontSize:24,fontWeight:650,color:'#64748B',marginTop:12}}>erstellen + bearbeiten</div></div></div><div style={{position:'absolute',left:140,right:140,top:1050,...card,padding:28,textAlign:'center',opacity:stay}}><div style={{fontSize:34,fontWeight:950,color:C.ink}}>Bildgenerierung bleibt in ChatGPT.</div></div></AbsoluteFill>};

export const BackupVisual:React.FC=()=>{const f=useCurrentFrame();const images=[0,1,2].map((i)=>pop(f,12+i*12));const download=pop(f,70);return <AbsoluteFill style={{background:'radial-gradient(circle at 18% 18%,#FFF0E4 0,transparent 34%),linear-gradient(180deg,#FFFDFC,#F8FAFC)'}}><div style={{position:'absolute',left:90,right:90,top:320,...card,padding:34}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><Badge bg={C.orangeSoft} color={C.orange}><Images size={27}/>Deine Bilder</Badge><Badge bg={C.yellowSoft} color='#9A7400'><CalendarDays size={27}/>vor 30.08.</Badge></div><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:20,marginTop:30}}>{images.map((s,i)=><div key={i} style={{height:260,borderRadius:28,background:[C.cyanSoft,C.purpleSoft,C.greenSoft][i],display:'grid',placeItems:'center',opacity:s,transform:`translateY(${(1-s)*38}px)`}}><Image size={72} color={[C.cyan,C.purple,C.green][i]}/></div>)}</div><div style={{height:4,background:'rgba(16,32,51,.08)',margin:'34px 0',borderRadius:999}}/><div style={{display:'flex',alignItems:'center',justifyContent:'center',gap:22,opacity:download,transform:`translateY(${(1-download)*30}px)`}}><Download size={50} color={C.orange}/><div style={{fontSize:40,fontWeight:980,color:C.ink}}>Jetzt herunterladen</div><ArrowRight size={42} color='#94A3B8'/><Archive size={52} color={C.green}/></div></div></AbsoluteFill>};

export const WhatStaysVisual:React.FC=()=> <AbsoluteFill style={{background:'radial-gradient(circle at 85% 16%,#E6F8EF 0,transparent 35%),linear-gradient(180deg,#FFFFFF,#F4FBF7)'}}><div style={{position:'absolute',left:72,right:72,top:330,display:'grid',gap:22}}><Feature delay={8} icon={<WandSparkles size={42}/>} title="Bilder erstellen" sub="direkt mit ChatGPT Bilder" accent={C.green}/><Feature delay={26} icon={<PenTool size={42}/>} title="Bilder bearbeiten" sub="bleibt weiterhin möglich" accent={C.cyan}/><Feature delay={44} icon={<Sparkles size={42}/>} title="Eigene GPTs" sub="mit Bildgenerierung nicht betroffen" accent={C.purple}/></div></AbsoluteFill>;

export const SummaryVisual:React.FC=()=>{const f=useCurrentFrame();const a=pop(f,8),b=pop(f,28),cta=pop(f,65);return <AbsoluteFill style={{background:'radial-gradient(circle at 18% 16%,#EFEAFF 0,transparent 32%),radial-gradient(circle at 88% 30%,#DDF9FC 0,transparent 34%),linear-gradient(180deg,#FFFFFF,#F7F9FC)'}}><div style={{position:'absolute',left:76,right:76,top:330,display:'grid',gridTemplateColumns:'1fr 1fr',gap:24}}><div style={{...card,padding:32,opacity:a,transform:`translateY(${(1-a)*30}px)`}}><Badge bg={C.redSoft} color={C.red}>30.08.</Badge><div style={{fontSize:39,fontWeight:980,color:C.ink,marginTop:28}}>DALL·E-GPT</div><div style={{fontSize:28,fontWeight:900,color:C.red,marginTop:18}}>verschwindet</div></div><div style={{...card,padding:32,opacity:b,transform:`translateY(${(1-b)*30}px)`,border:`2px solid ${C.green}33`}}><Badge bg={C.greenSoft} color={C.green}>danach</Badge><div style={{fontSize:39,fontWeight:980,color:C.ink,marginTop:28}}>ChatGPT Bilder</div><div style={{fontSize:28,fontWeight:900,color:C.green,marginTop:18}}>bleibt</div></div></div><div style={{position:'absolute',left:130,right:130,top:1050,...card,padding:'30px 34px',display:'flex',alignItems:'center',justifyContent:'center',gap:18,opacity:cta,transform:`scale(${.94+.06*cta})`}}><Download size={44} color={C.orange}/><div style={{fontSize:36,fontWeight:980,color:C.ink,textAlign:'center'}}>Bilder vorher sichern.</div></div></AbsoluteFill>};
