import React,{useMemo} from 'react';
import {AbsoluteFill,Html5Audio,Sequence,interpolate,useCurrentFrame} from 'remotion';
import {BRAND} from '../../../brand/brand';
import {REEL_CAPTION_SAFE} from '../captionSafe';
import {AI_SKETCH_WEBSITE_CAPTION_ZONE_Y,AI_SKETCH_WEBSITE_SCENES,AI_SKETCH_WEBSITE_SUBTITLES,type AISketchWebsiteCue,type AISketchWebsiteScene} from './contract';
import {FunctionVisual,LayoutVisual,SketchMeaningVisual,StructureVisual,TestPrototypeVisual} from './Visuals';

const visualByScene:Record<string,React.FC>={'sketch-01':SketchMeaningVisual,'sketch-02':StructureVisual,'sketch-03':LayoutVisual,'sketch-04':FunctionVisual,'sketch-05':TestPrototypeVisual};
const iconPaths:Record<string,React.ReactNode>={sketch:<><path d="M7 23l3-9 10-10 5 5-10 10z"/><path d="M9 21l-2 5 5-2"/></>,structure:<><rect x="4" y="5" width="24" height="7" rx="2"/><rect x="4" y="16" width="10" height="11" rx="2"/><rect x="18" y="16" width="10" height="11" rx="2"/></>,layout:<><rect x="4" y="5" width="24" height="22" rx="3"/><path d="M4 11h24M11 11v16"/></>,code:<><path d="M11 9l-6 7 6 7M21 9l6 7-6 7M18 6l-4 20"/></>,verify:<><circle cx="16" cy="16" r="12"/><path d="M10 16l4 4 8-9"/></>};
const Header:React.FC<{scene:AISketchWebsiteScene}>=({scene})=>{const f=useCurrentFrame();const enter=interpolate(f,[0,14],[.35,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});return <div style={{position:'absolute',left:64,right:64,top:92,zIndex:50,display:'flex',justifyContent:'center',alignItems:'center',gap:22,opacity:enter,transform:`translateY(${(1-enter)*-12}px)`}}><div style={{width:74,height:74,borderRadius:23,display:'flex',alignItems:'center',justifyContent:'center',background:'rgba(185,140,255,.16)',border:'1.5px solid rgba(110,69,201,.25)',color:BRAND.accentDk,boxShadow:'0 12px 30px rgba(110,69,201,.12)'}}><svg width="44" height="44" viewBox="0 0 32 32" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round">{iconPaths[scene.icon]??iconPaths.sketch}</svg></div><div style={{maxWidth:820,textAlign:'center',fontFamily:BRAND.font,fontSize:scene.headline.length>24?49:57,lineHeight:1.02,fontWeight:900,letterSpacing:-1.7,color:BRAND.accentDk,textShadow:'0 7px 22px rgba(110,69,201,.10)'}}>{scene.headline}</div></div>};
const activeWordIndex=(frame:number,cue:AISketchWebsiteCue,count:number)=>{if(count<=1)return 0;if(cue.words?.length===count){const exact=cue.words.findIndex(w=>frame>=w.startFrame&&frame<w.endFrame);if(exact>=0)return exact;}const p=interpolate(frame,[cue.startFrame,Math.max(cue.startFrame+1,cue.endFrame-1)],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});return Math.min(count-1,Math.floor(p*count));};
const buildCaptionGroups=(words:string[],maxWords=REEL_CAPTION_SAFE.maxWordsPerGroup):number[][]=>{const groups:number[][]=[];let current:number[]=[];words.forEach((word,index)=>{current.push(index);const hard=/[.!?][”“\"')\]]?$/.test(word);const soft=/[,;:][”“\"')\]]?$/.test(word)&&current.length>=4;if(hard||soft||current.length>=maxWords){groups.push(current);current=[];}});if(current.length)groups.push(current);return groups;};
const Captions:React.FC=()=>{const frame=useCurrentFrame();const cue=AI_SKETCH_WEBSITE_SUBTITLES.find(c=>frame>=c.startFrame&&frame<c.endFrame);if(!cue)return null;const words=cue.words?.length?cue.words.map(w=>w.text):cue.text.trim().split(/\s+/).filter(Boolean);const active=activeWordIndex(frame,cue,words.length);const groups=buildCaptionGroups(words);const visible=groups.find(g=>g.includes(active))??groups[0]??[];const fade=Math.min(interpolate(frame,[cue.startFrame,cue.startFrame+4],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}),interpolate(frame,[cue.endFrame-4,cue.endFrame],[1,0],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}));return <div style={{position:'absolute',left:REEL_CAPTION_SAFE.horizontalInset,right:REEL_CAPTION_SAFE.horizontalInset,bottom:REEL_CAPTION_SAFE.bottom,zIndex:200,display:'flex',justifyContent:'center',opacity:fade,pointerEvents:'none'}}><div style={{width:'100%',maxWidth:REEL_CAPTION_SAFE.maxWidth,textAlign:'center',fontFamily:BRAND.font,fontSize:52,fontWeight:850,lineHeight:1.14,letterSpacing:-.9,color:BRAND.ink,textShadow:'0 2px 0 rgba(255,255,255,.98),0 0 15px rgba(255,255,255,.98),0 8px 30px rgba(26,26,46,.10)'}}>{visible.map((idx,i)=><React.Fragment key={`${cue.sceneId}-${cue.startFrame}-${idx}`}><span style={{display:'inline-block',color:idx===active?BRAND.accentDk:BRAND.ink,transform:`scale(${idx===active?1.04:1})`,transformOrigin:'50% 70%'}}>{words[idx]}</span>{i<visible.length-1?' ':null}</React.Fragment>)}</div></div>};
const SceneLayer:React.FC<{scene:AISketchWebsiteScene}>=({scene})=>{const Visual=visualByScene[scene.sceneId];if(!Visual)throw new Error(`missing NEW_BUILD visual for ${scene.sceneId}`);return <AbsoluteFill><Header scene={scene}/><div style={{position:'absolute',left:0,right:0,top:225,height:AI_SKETCH_WEBSITE_CAPTION_ZONE_Y-225-30,overflow:'hidden',zIndex:20}}><Visual/></div></AbsoluteFill>};
export type ReelAISketchWebsiteProps={voiceoverSrc?:string;showCaptions?:boolean};
export const ReelAISketchWebsite:React.FC<ReelAISketchWebsiteProps>=({voiceoverSrc,showCaptions=true})=>{const scenes=useMemo(()=>AI_SKETCH_WEBSITE_SCENES,[]);return <AbsoluteFill style={{background:'radial-gradient(circle at 50% 35%, #FFFFFF 0%, #FAF8FC 58%, #F1EDF6 100%)',color:BRAND.ink,overflow:'hidden',fontFamily:BRAND.font}}><div style={{position:'absolute',inset:0,background:'linear-gradient(rgba(110,69,201,.024) 1px, transparent 1px),linear-gradient(90deg,rgba(110,69,201,.024) 1px,transparent 1px)',backgroundSize:'72px 72px',maskImage:'linear-gradient(to bottom,transparent 0%,black 14%,black 72%,transparent 88%)'}}/>{scenes.map(scene=><Sequence key={scene.sceneId} from={scene.startFrame} durationInFrames={scene.endFrame-scene.startFrame} name={`${scene.sceneId}-NEW_BUILD`}><SceneLayer scene={scene}/></Sequence>)}{voiceoverSrc?<Html5Audio src={voiceoverSrc}/>:null}{showCaptions?<Captions/>:null}</AbsoluteFill>};
