import React from 'react';
import {interpolate,useCurrentFrame} from 'remotion';
import {BRAND} from '../../../brand/brand';

const OK='#4F9D74';
const BAD='#D95C6A';
const card:React.CSSProperties={background:'#fff',border:'2px solid rgba(110,69,201,.18)',borderRadius:30,boxShadow:'0 24px 70px rgba(26,26,46,.10)'};
const label:React.CSSProperties={fontFamily:BRAND.font,fontWeight:850,fontSize:32,color:BRAND.ink};
const stage:React.CSSProperties={position:'absolute',left:70,right:70,top:35,bottom:35,display:'flex',alignItems:'center',justifyContent:'center'};
const clamp=(v:number)=>Math.max(0,Math.min(1,v));

const SketchPaper:React.FC<{roles?:number}> = ({roles=0}) => <div style={{...card,width:790,height:650,padding:40,position:'relative',borderColor:'rgba(26,26,46,.14)',transform:'rotate(-1.5deg)',background:'linear-gradient(180deg,#fff,#FCFBFF)'}}>
  <div style={{position:'absolute',left:36,right:36,top:36,height:72,border:'4px solid rgba(26,26,46,.52)',borderRadius:16}}/>
  <div style={{position:'absolute',left:36,right:36,top:138,height:205,border:'4px solid rgba(26,26,46,.52)',borderRadius:18}}/>
  <div style={{position:'absolute',left:78,right:78,top:385,height:78,border:'4px solid rgba(26,26,46,.52)',borderRadius:16}}/>
  <div style={{position:'absolute',left:238,right:238,top:505,height:86,border:'4px solid rgba(26,26,46,.52)',borderRadius:22}}/>
  {roles>0?<><div style={{position:'absolute',top:51,left:275,...label,fontSize:29,color:BRAND.accentDk,opacity:roles}}>NAVIGATION</div><div style={{position:'absolute',top:212,left:278,...label,fontSize:29,color:BRAND.accentDk,opacity:roles}}>ÜBERSCHRIFT</div><div style={{position:'absolute',top:407,left:285,...label,fontSize:29,color:BRAND.accentDk,opacity:roles}}>EINGABEFELD</div><div style={{position:'absolute',top:528,left:305,...label,fontSize:29,color:BRAND.accentDk,opacity:roles}}>BUTTON</div></>:null}
</div>;

export const SketchMeaningVisual:React.FC=()=>{const f=useCurrentFrame();const roles=clamp(interpolate(f,[105,260],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}));const clean=clamp(interpolate(f,[30,150],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}));return <div style={stage}><div style={{transform:`translateY(-65px) scale(${.9+.08*clean})`}}><SketchPaper roles={roles}/></div><div style={{position:'absolute',top:815,left:180,right:180,height:120,...card,display:'flex',alignItems:'center',justifyContent:'center',...label,color:BRAND.accentDk,opacity:roles}}>Formen bekommen Bedeutung</div></div>};

export const StructureVisual:React.FC=()=>{const f=useCurrentFrame();const zone=clamp(interpolate(f,[10,110],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}));const group=clamp(interpolate(f,[100,245],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}));const click=clamp(interpolate(f,[240,360],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}));const zones=[['HEADER','Navigation'],['HERO','Überschrift'],['FORM','Input + Button'],['FOOTER','Info']];return <div style={stage}><div style={{position:'absolute',top:90,left:120,right:120,display:'grid',gap:18}}>{zones.map((z,i)=><div key={z[0]} style={{...card,height:150,padding:'0 34px',display:'flex',alignItems:'center',justifyContent:'space-between',opacity:zone,transform:`translateX(${(1-zone)*(i%2?35:-35)}px)`}}><span style={{...label,color:BRAND.accentDk}}>{z[0]}</span><span style={{...label,fontSize:29,color:'rgba(26,26,46,.65)'}}>{z[1]}</span></div>)}</div><div style={{position:'absolute',top:755,left:215,right:215,height:105,borderRadius:28,background:'rgba(185,140,255,.15)',border:'2px solid rgba(110,69,201,.28)',display:'flex',alignItems:'center',justifyContent:'center',...label,color:BRAND.accentDk,opacity:group}}>Elemente gehören zusammen</div><div style={{position:'absolute',top:900,left:255,right:255,display:'flex',alignItems:'center',justifyContent:'center',gap:20,opacity:click}}><div style={{...card,padding:'22px 30px',...label,color:BRAND.accentDk}}>BUTTON</div><div style={{fontSize:54,color:BRAND.accentDk}}>→</div><div style={{...card,padding:'22px 30px',...label,color:OK}}>ERGEBNIS</div></div></div>};

export const LayoutVisual:React.FC=()=>{const f=useCurrentFrame();const polish=clamp(interpolate(f,[0,150],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}));const hierarchy=clamp(interpolate(f,[130,270],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}));return <div style={stage}><div style={{...card,width:850,height:700,padding:34,position:'relative',transform:'translateY(-65px)'}}><div style={{height:74,borderRadius:20,background:`rgba(110,69,201,${.08+.08*polish})`,display:'flex',alignItems:'center',padding:'0 28px',justifyContent:'space-between'}}><div style={{width:180,height:20,borderRadius:20,background:BRAND.accentDk}}/><div style={{display:'flex',gap:18}}>{[1,2,3].map(i=><div key={i} style={{width:74,height:14,borderRadius:20,background:'rgba(26,26,46,.25)'}}/>)}</div></div><div style={{marginTop:38,textAlign:'center',fontFamily:BRAND.font,fontWeight:950,fontSize:50,color:BRAND.ink,opacity:.75+.25*hierarchy}}>Deine nächste Idee</div><div style={{margin:'26px auto 0',width:520,height:22,borderRadius:20,background:'rgba(26,26,46,.12)'}}/><div style={{margin:'52px auto 0',width:610,height:92,borderRadius:26,border:'2px solid rgba(110,69,201,.22)',background:'#fff'}}/><div style={{margin:'24px auto 0',width:290,height:92,borderRadius:28,background:BRAND.accentDk,boxShadow:`0 18px 40px rgba(110,69,201,${.12+.16*polish})`}}/><div style={{position:'absolute',left:60,right:60,bottom:50,display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:20,opacity:hierarchy}}>{['ABSTAND','GRÖSSE','HIERARCHIE'].map(x=><div key={x} style={{height:72,borderRadius:20,background:'rgba(185,140,255,.13)',display:'flex',alignItems:'center',justifyContent:'center',...label,fontSize:27,color:BRAND.accentDk}}>{x}</div>)}</div></div></div>};

export const FunctionVisual:React.FC=()=>{const f=useCurrentFrame();const parts=clamp(interpolate(f,[0,100],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}));const flow=clamp(interpolate(f,[90,220],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}));const success=clamp(interpolate(f,[210,295],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}));const items=['Header','Form','Button'];return <div style={stage}><div style={{position:'absolute',top:115,left:125,right:125,display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:22}}>{items.map((x,i)=><div key={x} style={{...card,height:190,display:'flex',alignItems:'center',justifyContent:'center',...label,color:BRAND.accentDk,opacity:parts,transform:`translateY(${(1-parts)*(25+i*8)}px)`}}>{x}</div>)}</div><div style={{position:'absolute',top:440,left:160,right:160,...card,height:170,display:'flex',alignItems:'center',justifyContent:'space-around'}}><div style={{...label,color:BRAND.accentDk}}>KLICK</div><div style={{width:280,height:12,borderRadius:20,background:'rgba(110,69,201,.10)',overflow:'hidden'}}><div style={{height:'100%',width:`${flow*100}%`,background:BRAND.accentDk}}/></div><div style={{...label,color:flow>.85?OK:'rgba(26,26,46,.35)'}}>EVENT</div></div><div style={{position:'absolute',top:720,left:220,right:220,height:180,borderRadius:38,background:'rgba(79,157,116,.10)',border:'3px solid rgba(79,157,116,.45)',display:'flex',alignItems:'center',justifyContent:'center',fontFamily:BRAND.font,fontWeight:950,fontSize:44,color:OK,opacity:success,transform:`scale(${.9+.1*success})`}}>AKTION AUSGELÖST</div></div>};

export const TestPrototypeVisual:React.FC=()=>{const f=useCurrentFrame();const test=clamp(interpolate(f,[0,120],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}));const bug=clamp(interpolate(f,[105,205],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}));const patch=clamp(interpolate(f,[195,310],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}));const verified=clamp(interpolate(f,[300,410],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}));return <div style={stage}><div style={{position:'absolute',top:85,left:90,right:90,display:'flex',gap:26,justifyContent:'center'}}><div style={{...card,width:520,height:520,padding:28}}><div style={{...label,color:BRAND.accentDk}}>DESKTOP</div><div style={{marginTop:30,height:70,borderRadius:18,background:'rgba(185,140,255,.16)'}}/><div style={{marginTop:24,height:180,borderRadius:22,border:'2px solid rgba(110,69,201,.18)'}}/><div style={{margin:'24px auto 0',width:190,height:70,borderRadius:22,background:BRAND.accentDk}}/></div><div style={{...card,width:290,height:520,padding:24,borderColor:bug>.45&&patch<.65?BAD:'rgba(110,69,201,.18)'}}><div style={{...label,fontSize:29,color:BRAND.accentDk}}>MOBILE</div><div style={{marginTop:30,height:70,borderRadius:18,background:'rgba(185,140,255,.16)'}}/><div style={{marginTop:24,height:180,borderRadius:22,border:'2px solid rgba(110,69,201,.18)',transform:`translateX(${bug>.45&&patch<.65?22:0}px)`}}/><div style={{margin:'24px auto 0',width:160,height:70,borderRadius:22,background:BRAND.accentDk}}/></div></div><div style={{position:'absolute',top:655,left:120,right:120,display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:14,opacity:test}}>{['Mobil','Input','State','Fehler'].map((x,i)=><div key={x} style={{...card,height:105,display:'flex',alignItems:'center',justifyContent:'center',...label,fontSize:27,color:test>(i+1)/4?OK:'rgba(26,26,46,.35)'}}>{x}</div>)}</div><div style={{position:'absolute',top:810,left:230,right:230,height:105,borderRadius:26,background:bug>.45&&patch<.65?'rgba(217,92,106,.10)':'rgba(79,157,116,.10)',border:`2px solid ${bug>.45&&patch<.65?BAD:'rgba(79,157,116,.45)'}`,display:'flex',alignItems:'center',justifyContent:'center',...label,color:bug>.45&&patch<.65?BAD:OK,opacity:bug}}>Nur Mobile-Block korrigieren</div><div style={{position:'absolute',top:945,left:245,right:245,height:125,borderRadius:38,background:'rgba(79,157,116,.12)',border:'3px solid rgba(79,157,116,.52)',display:'flex',alignItems:'center',justifyContent:'center',fontFamily:BRAND.font,fontWeight:950,fontSize:43,color:OK,opacity:verified,transform:`scale(${.9+.1*verified})`}}>PROTOTYP VERIFIZIERT</div></div>};
