import type {AuthoredVisualScene} from '../../animation-library/authoredProductionGate';

export const AI_SKETCH_WEBSITE_VISUAL_PROFILES: readonly AuthoredVisualScene[] = [
  {
    sceneId: 'sketch-01',
    visualId: 'ai-sketch-semantic-paper-scan-v2',
    fingerprint: {
      primaryPrimitive: 'illustration',
      cameraMotion: 'push',
      depthStyle: 'layered-2d',
      entryMechanism: 'mask',
      medium: 'remotion-native',
      direction: 'top-to-bottom',
      visualFamily: 'sketch-semantic-recognition',
      layoutFamily: 'annotated-paper-scan-stage',
      motionSignature: 'paper-enter-scan-role-reveal-semantic-resolve',
    },
  },
  {
    sceneId: 'sketch-02',
    visualId: 'ai-sketch-structure-relationship-graph-v2',
    fingerprint: {
      primaryPrimitive: 'nodes',
      cameraMotion: 'pull',
      depthStyle: 'flat',
      entryMechanism: 'draw',
      medium: 'remotion-native',
      direction: 'center-out',
      visualFamily: 'information-architecture',
      layoutFamily: 'radial-page-relationship-graph',
      motionSignature: 'root-draw-branches-expand-action-resolve',
    },
  },
  {
    sceneId: 'sketch-03',
    visualId: 'ai-sketch-wireframe-layout-morph-v2',
    fingerprint: {
      primaryPrimitive: 'object',
      cameraMotion: 'push',
      depthStyle: 'pseudo-3d',
      entryMechanism: 'morph',
      medium: 'remotion-native',
      direction: 'depth-forward',
      visualFamily: 'wireframe-to-layout',
      layoutFamily: 'perspective-layout-plane',
      motionSignature: 'rough-offsets-align-depth-polish-hierarchy-lock',
    },
  },
  {
    sceneId: 'sketch-04',
    visualId: 'ai-sketch-event-flow-route-v2',
    fingerprint: {
      primaryPrimitive: 'path',
      cameraMotion: 'pan',
      depthStyle: 'layered-2d',
      entryMechanism: 'draw',
      medium: 'remotion-native',
      direction: 'left-to-right',
      visualFamily: 'interaction-event-flow',
      layoutFamily: 'curved-event-action-route',
      motionSignature: 'route-draw-trigger-travel-logic-action-confirm',
    },
  },
  {
    sceneId: 'sketch-05',
    visualId: 'ai-sketch-device-diagnostic-repair-v2',
    fingerprint: {
      primaryPrimitive: 'object',
      cameraMotion: 'orbit',
      depthStyle: 'pseudo-3d',
      entryMechanism: 'mask',
      medium: 'remotion-native',
      direction: 'top-to-bottom',
      visualFamily: 'prototype-diagnostics',
      layoutFamily: 'device-diagnostic-scan-field',
      motionSignature: 'device-stage-scan-isolate-patch-recheck-verify',
    },
  },
] as const;
