import React from 'react';
import {Composition, Folder} from 'remotion';
import {ReelAntigravityContextOverload,ANTIGRAVITY_CONTEXT_OVERLOAD_COMPOSITION_ID,ANTIGRAVITY_CONTEXT_OVERLOAD_DURATION_IN_FRAMES,ANTIGRAVITY_CONTEXT_OVERLOAD_FPS,ANTIGRAVITY_CONTEXT_OVERLOAD_HEIGHT,ANTIGRAVITY_CONTEXT_OVERLOAD_WIDTH} from './reels/antigravity-context-overload';
import {ReelAiHallucinations,AI_HALLUCINATIONS_COMPOSITION_ID,AI_HALLUCINATIONS_DURATION_IN_FRAMES,AI_HALLUCINATIONS_FPS,AI_HALLUCINATIONS_HEIGHT,AI_HALLUCINATIONS_WIDTH} from './reels/ai-hallucinations';
import {ReelAmbiguousPrompts,AMBIGUOUS_PROMPTS_COMPOSITION_ID,AMBIGUOUS_PROMPTS_DURATION_IN_FRAMES,AMBIGUOUS_PROMPTS_FPS,AMBIGUOUS_PROMPTS_HEIGHT,AMBIGUOUS_PROMPTS_WIDTH} from './reels/ambiguous-prompts';
import {ReelVisionPhotoUnderstanding,VISION_PHOTO_COMPOSITION_ID,VISION_PHOTO_DURATION_IN_FRAMES,VISION_PHOTO_FPS,VISION_PHOTO_HEIGHT,VISION_PHOTO_WIDTH} from './reels/vision-photo-understanding';
import {ReelPdfRetrieval,PDF_RETRIEVAL_COMPOSITION_ID,PDF_RETRIEVAL_DURATION_IN_FRAMES,PDF_RETRIEVAL_FPS,PDF_RETRIEVAL_HEIGHT,PDF_RETRIEVAL_WIDTH} from './reels/pdf-retrieval';
import {ReelGpt56ChatGPT,GPT56_COMPOSITION_ID,GPT56_DURATION_IN_FRAMES,GPT56_FPS,GPT56_HEIGHT,GPT56_WIDTH} from './reels/gpt-5-6-chatgpt';
import {ReelGpt55Retirement,GPT55_COMPOSITION_ID,GPT55_DURATION_IN_FRAMES,GPT55_FPS,GPT55_HEIGHT,GPT55_WIDTH} from './reels/gpt-5-5-retirement';
import {ReelAiAgents,AI_AGENTS_COMPOSITION_ID,AI_AGENTS_DURATION_IN_FRAMES,AI_AGENTS_FPS,AI_AGENTS_HEIGHT,AI_AGENTS_WIDTH} from './reels/ai-agents';
import {ReelAiAppPrototype,AI_APP_PROTOTYPE_COMPOSITION_ID,AI_APP_PROTOTYPE_DURATION_IN_FRAMES,AI_APP_PROTOTYPE_FPS,AI_APP_PROTOTYPE_HEIGHT,AI_APP_PROTOTYPE_WIDTH} from './reels/ai-app-prototype';
import {ReelAiProductAd,AI_PRODUCT_AD_COMPOSITION_ID,AI_PRODUCT_AD_DURATION_IN_FRAMES,AI_PRODUCT_AD_FPS,AI_PRODUCT_AD_HEIGHT,AI_PRODUCT_AD_WIDTH} from './reels/ai-product-ad';
import {ReelWhyAiReadsDifferently,WHY_AI_READS_DIFFERENTLY_COMPOSITION_ID,WHY_AI_READS_DIFFERENTLY_DURATION_IN_FRAMES,WHY_AI_READS_DIFFERENTLY_FPS,WHY_AI_READS_DIFFERENTLY_HEIGHT,WHY_AI_READS_DIFFERENTLY_WIDTH} from './reels/why-ai-reads-differently';
import {ReelAiSketchWebsite,AI_SKETCH_WEBSITE_COMPOSITION_ID,AI_SKETCH_WEBSITE_DURATION_IN_FRAMES,AI_SKETCH_WEBSITE_FPS,AI_SKETCH_WEBSITE_HEIGHT,AI_SKETCH_WEBSITE_WIDTH} from './reels/ai-sketch-website';
import {ReelGithubRepositoryBasics,GITHUB_REPOSITORY_BASICS_COMPOSITION_ID,GITHUB_REPOSITORY_BASICS_DURATION_IN_FRAMES,GITHUB_REPOSITORY_BASICS_FPS,GITHUB_REPOSITORY_BASICS_HEIGHT,GITHUB_REPOSITORY_BASICS_WIDTH} from './reels/github-repository-basics';
import {LongformAIAppWorkflow,AI_APP_WORKFLOW_COMPOSITION_ID,AI_APP_WORKFLOW_DURATION_IN_FRAMES,AI_APP_WORKFLOW_FPS,AI_APP_WORKFLOW_HEIGHT,AI_APP_WORKFLOW_WIDTH} from './longform/ai-app-workflow';

export const ProductionRoot:React.FC=()=> (
  <>
    <Folder name="KI-Production-Reels">
      <Composition id={ANTIGRAVITY_CONTEXT_OVERLOAD_COMPOSITION_ID} component={ReelAntigravityContextOverload} durationInFrames={ANTIGRAVITY_CONTEXT_OVERLOAD_DURATION_IN_FRAMES} fps={ANTIGRAVITY_CONTEXT_OVERLOAD_FPS} width={ANTIGRAVITY_CONTEXT_OVERLOAD_WIDTH} height={ANTIGRAVITY_CONTEXT_OVERLOAD_HEIGHT}/>
      <Composition id={AI_HALLUCINATIONS_COMPOSITION_ID} component={ReelAiHallucinations} durationInFrames={AI_HALLUCINATIONS_DURATION_IN_FRAMES} fps={AI_HALLUCINATIONS_FPS} width={AI_HALLUCINATIONS_WIDTH} height={AI_HALLUCINATIONS_HEIGHT}/>
      <Composition id={AMBIGUOUS_PROMPTS_COMPOSITION_ID} component={ReelAmbiguousPrompts} durationInFrames={AMBIGUOUS_PROMPTS_DURATION_IN_FRAMES} fps={AMBIGUOUS_PROMPTS_FPS} width={AMBIGUOUS_PROMPTS_WIDTH} height={AMBIGUOUS_PROMPTS_HEIGHT}/>
      <Composition id={VISION_PHOTO_COMPOSITION_ID} component={ReelVisionPhotoUnderstanding} durationInFrames={VISION_PHOTO_DURATION_IN_FRAMES} fps={VISION_PHOTO_FPS} width={VISION_PHOTO_WIDTH} height={VISION_PHOTO_HEIGHT}/>
      <Composition id={PDF_RETRIEVAL_COMPOSITION_ID} component={ReelPdfRetrieval} durationInFrames={PDF_RETRIEVAL_DURATION_IN_FRAMES} fps={PDF_RETRIEVAL_FPS} width={PDF_RETRIEVAL_WIDTH} height={PDF_RETRIEVAL_HEIGHT}/>
      <Composition id={GPT56_COMPOSITION_ID} component={ReelGpt56ChatGPT} durationInFrames={GPT56_DURATION_IN_FRAMES} fps={GPT56_FPS} width={GPT56_WIDTH} height={GPT56_HEIGHT}/>
      <Composition id={GPT55_COMPOSITION_ID} component={ReelGpt55Retirement} durationInFrames={GPT55_DURATION_IN_FRAMES} fps={GPT55_FPS} width={GPT55_WIDTH} height={GPT55_HEIGHT}/>
      <Composition id={AI_AGENTS_COMPOSITION_ID} component={ReelAiAgents} durationInFrames={AI_AGENTS_DURATION_IN_FRAMES} fps={AI_AGENTS_FPS} width={AI_AGENTS_WIDTH} height={AI_AGENTS_HEIGHT}/>
      <Composition id={AI_APP_PROTOTYPE_COMPOSITION_ID} component={ReelAiAppPrototype} durationInFrames={AI_APP_PROTOTYPE_DURATION_IN_FRAMES} fps={AI_APP_PROTOTYPE_FPS} width={AI_APP_PROTOTYPE_WIDTH} height={AI_APP_PROTOTYPE_HEIGHT}/>
      <Composition id={AI_PRODUCT_AD_COMPOSITION_ID} component={ReelAiProductAd} durationInFrames={AI_PRODUCT_AD_DURATION_IN_FRAMES} fps={AI_PRODUCT_AD_FPS} width={AI_PRODUCT_AD_WIDTH} height={AI_PRODUCT_AD_HEIGHT}/>
      <Composition id={WHY_AI_READS_DIFFERENTLY_COMPOSITION_ID} component={ReelWhyAiReadsDifferently} durationInFrames={WHY_AI_READS_DIFFERENTLY_DURATION_IN_FRAMES} fps={WHY_AI_READS_DIFFERENTLY_FPS} width={WHY_AI_READS_DIFFERENTLY_WIDTH} height={WHY_AI_READS_DIFFERENTLY_HEIGHT}/>
      <Composition id={AI_SKETCH_WEBSITE_COMPOSITION_ID} component={ReelAiSketchWebsite} durationInFrames={AI_SKETCH_WEBSITE_DURATION_IN_FRAMES} fps={AI_SKETCH_WEBSITE_FPS} width={AI_SKETCH_WEBSITE_WIDTH} height={AI_SKETCH_WEBSITE_HEIGHT}/>
      <Composition id={GITHUB_REPOSITORY_BASICS_COMPOSITION_ID} component={ReelGithubRepositoryBasics} durationInFrames={GITHUB_REPOSITORY_BASICS_DURATION_IN_FRAMES} fps={GITHUB_REPOSITORY_BASICS_FPS} width={GITHUB_REPOSITORY_BASICS_WIDTH} height={GITHUB_REPOSITORY_BASICS_HEIGHT}/>
    </Folder>
    <Folder name="Production-Longform">
      <Composition id={AI_APP_WORKFLOW_COMPOSITION_ID} component={LongformAIAppWorkflow} durationInFrames={AI_APP_WORKFLOW_DURATION_IN_FRAMES} fps={AI_APP_WORKFLOW_FPS} width={AI_APP_WORKFLOW_WIDTH} height={AI_APP_WORKFLOW_HEIGHT}/>
    </Folder>
  </>
);
