import type {AuthoredVisualScene} from '../../animation-library/authoredProductionGate';

export const VOICE_PLUGIN_VISUAL_PROFILES: readonly AuthoredVisualScene[] = [
  {sceneId:'voice-01',visualId:'voice-workflow-hero-v1',fingerprint:{primaryPrimitive:'typography',cameraMotion:'push',depthStyle:'layered-2d',entryMechanism:'assemble',medium:'remotion-native',direction:'center-out',visualFamily:'voice-workflow-transform',layoutFamily:'hero-orb-type-burst',motionSignature:'orb-pulse-signal-burst-type-slam'}},
  {sceneId:'voice-02',visualId:'voice-device-space-v1',fingerprint:{primaryPrimitive:'three-object',cameraMotion:'orbit',depthStyle:'three-3d',entryMechanism:'depth',medium:'three',direction:'outside-in',visualFamily:'platform-device-space',layoutFamily:'three-device-arc',motionSignature:'devices-rise-orbit-synchronize'}},
  {sceneId:'voice-03',visualId:'voice-plugin-network-v1',fingerprint:{primaryPrimitive:'path',cameraMotion:'pan',depthStyle:'layered-2d',entryMechanism:'draw',medium:'remotion-native',direction:'center-out',visualFamily:'plugin-data-flow',layoutFamily:'hub-radial-routes',motionSignature:'route-draw-payload-arrive-node-pulse'}},
  {sceneId:'voice-04',visualId:'voice-work-artifacts-v1',fingerprint:{primaryPrimitive:'object',cameraMotion:'parallax',depthStyle:'pseudo-3d',entryMechanism:'morph',medium:'remotion-native',direction:'left-to-right',visualFamily:'work-artifact-morph',layoutFamily:'depth-artifact-fan',motionSignature:'voice-morph-artifacts-fan-forward'}},
  {sceneId:'voice-05',visualId:'voice-task-continuity-v1',fingerprint:{primaryPrimitive:'path',cameraMotion:'pan',depthStyle:'layered-2d',entryMechanism:'draw',medium:'remotion-native',direction:'left-to-right',visualFamily:'task-continuity',layoutFamily:'call-to-text-route',motionSignature:'call-collapse-route-persists-text-resolve'}},
  {sceneId:'voice-06',visualId:'voice-permission-rings-v1',fingerprint:{primaryPrimitive:'object',cameraMotion:'pull',depthStyle:'pseudo-3d',entryMechanism:'assemble',medium:'remotion-native',direction:'outside-in',visualFamily:'permission-boundaries',layoutFamily:'concentric-lock-field',motionSignature:'rings-close-locks-snap-limit-hold'}},
  {sceneId:'voice-07',visualId:'voice-control-verdict-v1',fingerprint:{primaryPrimitive:'typography',cameraMotion:'push',depthStyle:'layered-2d',entryMechanism:'assemble',medium:'remotion-native',direction:'bottom-to-top',visualFamily:'workflow-verdict',layoutFamily:'wave-hub-verdict',motionSignature:'wave-condense-hub-lock-type-resolve'}},
] as const;
