import type {AuthoredVisualScene} from '../../animation-library/authoredProductionGate';

export const VISION_PHOTO_VISUAL_PROFILES: readonly AuthoredVisualScene[] = [
  {
    sceneId: 'vision-photo-01',
    visualId: 'vision-photo-desk-hook-v1',
    fingerprint: {
      primaryPrimitive: 'illustration',
      cameraMotion: 'push',
      depthStyle: 'layered-2d',
      entryMechanism: 'scale',
      medium: 'remotion-native',
      direction: 'depth-forward',
      visualFamily: 'photo-question-hook',
      layoutFamily: 'large-desk-photo-focus',
      motionSignature: 'photo-rise-question-dock-key-focus',
    },
  },
  {
    sceneId: 'vision-photo-02',
    visualId: 'vision-photo-patch-explosion-v1',
    fingerprint: {
      primaryPrimitive: 'mixed',
      cameraMotion: 'parallax',
      depthStyle: 'pseudo-3d',
      entryMechanism: 'assemble',
      medium: 'remotion-native',
      direction: 'center-out',
      visualFamily: 'image-tokenization',
      layoutFamily: 'exploded-photo-grid',
      motionSignature: 'grid-draw-tiles-lift-token-stream',
    },
  },
  {
    sceneId: 'vision-photo-03',
    visualId: 'vision-photo-question-focus-v1',
    fingerprint: {
      primaryPrimitive: 'nodes',
      cameraMotion: 'pan',
      depthStyle: 'layered-2d',
      entryMechanism: 'draw',
      medium: 'remotion-native',
      direction: 'left-to-right',
      visualFamily: 'cross-modal-focus',
      layoutFamily: 'question-to-image-focus-map',
      motionSignature: 'word-tokens-enter-paths-connect-background-dims',
    },
  },
  {
    sceneId: 'vision-photo-04',
    visualId: 'vision-photo-answer-grounding-v1',
    fingerprint: {
      primaryPrimitive: 'typography',
      cameraMotion: 'push',
      depthStyle: 'layered-2d',
      entryMechanism: 'mask',
      medium: 'remotion-native',
      direction: 'left-to-right',
      visualFamily: 'answer-grounding',
      layoutFamily: 'key-crop-answer-stream',
      motionSignature: 'crop-push-words-build-pointer-draw',
    },
  },
  {
    sceneId: 'vision-photo-05',
    visualId: 'vision-photo-clarity-limit-v1',
    fingerprint: {
      primaryPrimitive: 'illustration',
      cameraMotion: 'pull',
      depthStyle: 'layered-2d',
      entryMechanism: 'morph',
      medium: 'remotion-native',
      direction: 'outside-in',
      visualFamily: 'vision-clarity-limit',
      layoutFamily: 'blur-clear-split-final-rule',
      motionSignature: 'blur-loss-split-reveal-inputs-converge',
    },
  },
] as const;
