import React from 'react';
import {interpolate,useCurrentFrame} from 'remotion';
import {BRAND} from '../../../brand/brand';

const OK='#4F9D74';
const MUTED='rgba(26,26,46,.48)';
const card:React.CSSProperties={background:'#fff',border:'2px solid rgba(110,69,201,.18)',borderRadius:30,boxShadow:'0 24px 70px rgba(26,26,46,.10)'};
const label:React.CSSProperties={fontFamily:BRAND.font.body,fontWeight:850,fontSize:32,color:BRAND.ink};
const stage:React.CSSProperties={position:'absolute',left:70,right:70,top:35,bottom:35};
const clamp=(v:number)=>Math.max(0,Math.min(1,v));
const p=(f:number,a:number,b:number)=>clamp(interpolate(f,[a,b],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}));

const FileCard:React.FC<{name:string;kind:string;opacity?:number}> = ({name,kind,opacity=1}) => <div style={{...card,width:176,height:150,padding:20,opacity,display:'flex',flexDirection:'column',justifyContent:'space-between'}}><div style={{fontFamily:BRAND.font.body,fontSize:25,fontWeight:900,color:BRAND.accentDk}}>{kind}</div><div style={{...label,fontSize:27}}>{name}</div></div>;

export const FolderMemoryVisual:React.FC=()=>{const f=useCurrentFrame();const open=p(f,0,45);const files=p(f,45,125);const memory=p(f,145,285);return <div style={stage}><div style={{position:'absolute',top:95,left:120,right:120,height:500,...card,borderRadius:48,background:'linear-gradient(145deg,#fff,#F3EEFC)',transform:`scale(${.94+.06*open})`,opacity:.45+.55*open}}><div style={{position:'absolute',top:-42,left:58,width:270,height:86,borderRadius:'30px 30px 10px 10px',background:'#E8DDFB',border:'2px solid rgba(110,69,201,.24)'}}/><div style={{position:'absolute',left:52,right:52,top:90,display:'flex',justifyContent:'space-between',transform:`translateY(${(1-files)*35}px)`,opacity:files}}><FileCard kind="CODE" name="app.tsx"/><FileCard kind="DOC" name="README"/><FileCard kind="CFG" name="config"/></div><div style={{position:'absolute',left:70,right:70,bottom:48,textAlign:'center',...label,fontSize:42,color:BRAND.accentDk}}>PROJEKT-REPOSITORY</div></div><div style={{position:'absolute',top:690,left:120,right:120,height:12,borderRadius:20,background:'rgba(110,69,201,.10)'}}><div style={{height:'100%',width:`${memory*100}%`,borderRadius:20,background:BRAND.accentDk}}/></div><div style={{position:'absolute',top:648,left:120,right:120,display:'flex',justifyContent:'space-between',opacity:memory}}>{[0,1,2,3].map(i=><div key={i} style={{width:30,height:30,borderRadius:'50%',background:i===3?BRAND.accentDk:'#D8C6F5',border:'6px solid #fff',boxShadow:'0 4px 14px rgba(110,69,201,.22)'}}/>)}</div><div style={{position:'absolute',top:770,left:210,right:210,...card,padding:'26px 30px',textAlign:'center',...label,fontSize:38,color:BRAND.accentDk,opacity:memory}}>Ordner + Versionsgedächtnis</div></div>};

export const ContentsVisual:React.FC=()=>{const f=useCurrentFrame();const show=p(f,0,80);const delta=p(f,90,160);const meta=p(f,170,260);const items=[['CODE','app.tsx'],['BILD','hero.png'],['DOC','README'],['CFG','.env']];return <div style={stage}><div style={{position:'absolute',top:70,left:65,right:65,height:510,...card,padding:36}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div style={{...label,fontSize:38,color:BRAND.accentDk}}>repository/</div><div style={{...label,fontSize:27,color:MUTED}}>4 Dateitypen</div></div><div style={{marginTop:42,display:'grid',gridTemplateColumns:'1fr 1fr',gap:22}}>{items.map((x,i)=><div key={x[0]} style={{height:130,borderRadius:24,border:`2px solid ${i===0&&delta>.35?'#6E45C9':'rgba(110,69,201,.16)'}`,background:i===0&&delta>.35?'rgba(185,140,255,.16)':'#fff',display:'flex',alignItems:'center',padding:'0 28px',gap:22,opacity:Math.min(1,show*(1.6-i*.15))}}><div style={{width:86,...label,fontSize:27,color:BRAND.accentDk}}>{x[0]}</div><div style={{...label,fontSize:31}}>{x[1]}</div></div>)}</div></div><div style={{position:'absolute',top:650,left:95,right:95,display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:18,opacity:meta}}>{[['ÄNDERUNG','app.tsx'],['ZEIT','07:24'],['PERSON','du']].map(x=><div key={x[0]} style={{...card,height:150,padding:22,textAlign:'center'}}><div style={{fontFamily:BRAND.font.body,fontSize:25,fontWeight:900,color:MUTED}}>{x[0]}</div><div style={{marginTop:24,...label,fontSize:32,color:BRAND.accentDk}}>{x[1]}</div></div>)}</div><div style={{position:'absolute',top:875,left:170,right:170,...card,padding:'24px 28px',textAlign:'center',...label,fontSize:35,opacity:meta}}>Git merkt sich den Kontext</div></div>};

export const CommitHistoryVisual:React.FC=()=>{const f=useCurrentFrame();const build=p(f,0,100);const diff=p(f,100,160);const rewind=p(f,160,220);const nodes=['c1','c2','c3','c4'];return <div style={stage}><div style={{position:'absolute',top:175,left:100,right:100,height:210}}><div style={{position:'absolute',left:35,right:35,top:86,height:12,borderRadius:20,background:'rgba(110,69,201,.12)'}}><div style={{height:'100%',width:`${build*100}%`,background:BRAND.accentDk,borderRadius:20}}/></div><div style={{position:'absolute',left:24,right:24,top:53,display:'flex',justifyContent:'space-between'}}>{nodes.map((n,i)=>{const on=build>i/(nodes.length-1);return <div key={n} style={{width:78,height:78,borderRadius:'50%',background:on?BRAND.accentDk:'#E9E2F4',border:'8px solid #fff',boxShadow:'0 8px 25px rgba(26,26,46,.12)',display:'flex',alignItems:'center',justifyContent:'center',fontFamily:BRAND.font.body,fontSize:23,fontWeight:900,color:on?'#fff':MUTED}}>{n}</div>})}</div></div><div style={{position:'absolute',top:470,left:140,right:140,...card,padding:34,opacity:diff}}><div style={{...label,fontSize:30,color:MUTED}}>COMMIT c4 · Unterschied</div><div style={{marginTop:28,fontFamily:'monospace',fontSize:31,lineHeight:1.7}}><div style={{padding:'5px 12px',borderRadius:12,background:'rgba(217,92,106,.08)',color:'#B84959'}}>- button disabled</div><div style={{marginTop:10,padding:'5px 12px',borderRadius:12,background:'rgba(79,157,116,.09)',color:OK}}>+ button enabled</div></div></div><div style={{position:'absolute',top:820,left:205,right:205,...card,height:132,display:'flex',alignItems:'center',justifyContent:'center',gap:20,opacity:rewind,transform:`scale(${.94+.06*rewind})`}}><div style={{fontSize:44,color:BRAND.accentDk}}>↶</div><div style={{...label,fontSize:34}}>Früherer Stand auffindbar</div></div></div>};

export const BranchPullRequestVisual:React.FC=()=>{const f=useCurrentFrame();const split=p(f,10,60);const work=p(f,60,100);const review=p(f,100,140);const merge=p(f,140,175);return <div style={stage}><svg style={{position:'absolute',top:85,left:35}} width="940" height="530" viewBox="0 0 940 530"><path d="M90 90 H850" stroke="rgba(110,69,201,.22)" strokeWidth="16" strokeLinecap="round"/><path d="M90 90 H850" stroke="#6E45C9" strokeWidth="12" strokeLinecap="round"/><path d="M300 90 C360 90 360 280 440 280 H690 C760 280 760 90 825 90" fill="none" stroke="rgba(110,69,201,.16)" strokeWidth="18" strokeLinecap="round"/><path d="M300 90 C360 90 360 280 440 280 H690 C760 280 760 90 825 90" fill="none" stroke="#B98CFF" strokeWidth="12" strokeLinecap="round" strokeDasharray="650" strokeDashoffset={650*(1-split)}/><circle cx="300" cy="90" r="23" fill="#6E45C9"/><circle cx="825" cy="90" r="26" fill={merge>.55?OK:'#D8C6F5'}/><circle cx={440+250*work} cy="280" r="24" fill="#B98CFF" opacity={split}/></svg><div style={{position:'absolute',top:72,left:150,...label,fontSize:30,color:BRAND.accentDk}}>MAIN · stabil</div><div style={{position:'absolute',top:340,left:330,...card,width:420,height:125,padding:'22px 28px',opacity:split}}><div style={{...label,fontSize:28,color:MUTED}}>FEATURE-BRANCH</div><div style={{marginTop:12,...label,fontSize:33}}>Neue Funktion getrennt</div></div><div style={{position:'absolute',top:660,left:205,right:205,...card,height:155,padding:28,textAlign:'center',opacity:review,transform:`scale(${.94+.06*review})`}}><div style={{...label,fontSize:29,color:MUTED}}>PULL REQUEST</div><div style={{marginTop:16,...label,fontSize:38,color:BRAND.accentDk}}>Änderung prüfen</div></div><div style={{position:'absolute',top:880,left:270,right:270,height:105,borderRadius:30,background:'rgba(79,157,116,.12)',border:'2px solid rgba(79,157,116,.45)',display:'flex',alignItems:'center',justifyContent:'center',...label,fontSize:38,color:OK,opacity:merge}}>MERGE ✓</div></div>};

export const RepositoryWholeVisual:React.FC=()=>{const f=useCurrentFrame();const modules=p(f,0,125);const join=p(f,110,230);const share=p(f,225,330);const finish=p(f,300,365);const parts=[['DATEIEN','{ }'],['VERLAUF','●—●'],['TEAM','◉ ◉']];return <div style={stage}><div style={{position:'absolute',top:80,left:70,right:70,display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:20}}>{parts.map((x,i)=><div key={x[0]} style={{...card,height:190,padding:24,textAlign:'center',opacity:Math.min(1,modules*(1.5-i*.15)),transform:`translateY(${(1-modules)*(24+i*8)}px)`}}><div style={{fontFamily:BRAND.font.body,fontWeight:950,fontSize:40,color:BRAND.accentDk}}>{x[1]}</div><div style={{marginTop:28,...label,fontSize:29}}>{x[0]}</div></div>)}</div><div style={{position:'absolute',top:420,left:170,right:170,height:285,...card,borderRadius:46,background:'linear-gradient(145deg,#fff,#F3EEFC)',opacity:join,transform:`scale(${.9+.1*join})`,display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center'}}><div style={{fontSize:78,color:BRAND.accentDk}}>▰</div><div style={{marginTop:18,...label,fontSize:43,color:BRAND.accentDk}}>REPOSITORY</div><div style={{marginTop:13,...label,fontSize:27,color:MUTED}}>Dateien + Geschichte + Team</div></div><div style={{position:'absolute',top:770,left:150,right:150,height:95,display:'flex',alignItems:'center',gap:24,opacity:share}}><div style={{flex:1,height:10,borderRadius:20,background:'rgba(110,69,201,.12)'}}><div style={{width:`${share*100}%`,height:'100%',borderRadius:20,background:BRAND.accentDk}}/></div><div style={{...label,fontSize:36,color:BRAND.accentDk}}>→</div><div style={{width:90,height:90,borderRadius:'50%',background:'rgba(185,140,255,.20)',border:'3px solid rgba(110,69,201,.30)',display:'flex',alignItems:'center',justifyContent:'center',...label,fontSize:32,color:BRAND.accentDk}}>DU</div></div><div style={{position:'absolute',top:915,left:170,right:170,...card,height:115,display:'flex',alignItems:'center',justifyContent:'center',...label,fontSize:36,color:BRAND.accentDk,opacity:finish}}>Das Projekt + seine Entwicklung</div></div>};
