import type {AuthoredVisualScene} from '../../animation-library/authoredProductionGate';

export const GITHUB_REPOSITORY_VISUAL_PROFILES: readonly AuthoredVisualScene[] = [
  {
    sceneId: 'repo-01',
    visualId: 'github-repo-folder-memory-object-v2',
    fingerprint: {
      primaryPrimitive: 'object',
      cameraMotion: 'push',
      depthStyle: 'pseudo-3d',
      entryMechanism: 'assemble',
      medium: 'remotion-native',
      direction: 'bottom-to-top',
      visualFamily: 'repository-memory-metaphor',
      layoutFamily: 'opening-folder-depth-stage',
      motionSignature: 'folder-open-files-rise-history-trace-resolve',
    },
  },
  {
    sceneId: 'repo-02',
    visualId: 'github-repo-file-context-orbit-v2',
    fingerprint: {
      primaryPrimitive: 'nodes',
      cameraMotion: 'orbit',
      depthStyle: 'flat',
      entryMechanism: 'draw',
      medium: 'remotion-native',
      direction: 'circular',
      visualFamily: 'repository-content-context',
      layoutFamily: 'radial-file-context-orbit',
      motionSignature: 'core-appear-files-orbit-metadata-bind',
    },
  },
  {
    sceneId: 'repo-03',
    visualId: 'github-repo-commit-history-lens-v2',
    fingerprint: {
      primaryPrimitive: 'path',
      cameraMotion: 'pan',
      depthStyle: 'layered-2d',
      entryMechanism: 'draw',
      medium: 'remotion-native',
      direction: 'left-to-right',
      visualFamily: 'version-history',
      layoutFamily: 'commit-line-diff-lens',
      motionSignature: 'timeline-draw-lens-travel-diff-rewind',
    },
  },
  {
    sceneId: 'repo-04',
    visualId: 'github-repo-branch-review-depth-gate-v2',
    fingerprint: {
      primaryPrimitive: 'illustration',
      cameraMotion: 'pull',
      depthStyle: 'pseudo-3d',
      entryMechanism: 'depth',
      medium: 'remotion-native',
      direction: 'mixed',
      visualFamily: 'branch-safety-workflow',
      layoutFamily: 'split-depth-lanes-review-gate',
      motionSignature: 'main-hold-feature-split-review-gate-merge',
    },
  },
  {
    sceneId: 'repo-05',
    visualId: 'github-repo-layered-system-assembly-v2',
    fingerprint: {
      primaryPrimitive: 'mixed',
      cameraMotion: 'orbit',
      depthStyle: 'pseudo-3d',
      entryMechanism: 'assemble',
      medium: 'remotion-native',
      direction: 'center-out',
      visualFamily: 'repository-system-model',
      layoutFamily: 'stacked-project-system-core',
      motionSignature: 'layers-enter-bind-core-share-resolve',
    },
  },
] as const;
