export {ReelChatGPTAdsGermany} from './ReelChatGPTAdsGermany';
export {
  CHATGPT_ADS_GERMANY_COMPOSITION_ID,
  CHATGPT_ADS_GERMANY_DURATION_IN_FRAMES,
  CHATGPT_ADS_GERMANY_FPS,
  CHATGPT_ADS_GERMANY_HEIGHT,
  CHATGPT_ADS_GERMANY_WIDTH,
} from './contract';
