import type {AuthoredVisualScene} from '../../animation-library/authoredProductionGate';

export const ARITHMETIC_VISUAL_PROFILES: readonly AuthoredVisualScene[] = [
  {
    sceneId: 'arithmetic-01',
    visualId: 'arithmetic-equation-fracture-v1',
    fingerprint: {
      primaryPrimitive: 'typography',
      cameraMotion: 'push',
      depthStyle: 'layered-2d',
      entryMechanism: 'cut',
      medium: 'remotion-native',
      direction: 'center-out',
      visualFamily: 'equation-conflict',
      layoutFamily: 'full-canvas-equation-fracture',
      motionSignature: 'digit-snap-fracture-isolate',
    },
  },
  {
    sceneId: 'arithmetic-02',
    visualId: 'arithmetic-token-prediction-v1',
    fingerprint: {
      primaryPrimitive: 'nodes',
      cameraMotion: 'pan',
      depthStyle: 'layered-2d',
      entryMechanism: 'draw',
      medium: 'remotion-native',
      direction: 'left-to-right',
      visualFamily: 'token-prediction-flow',
      layoutFamily: 'token-rail-candidate-axis',
      motionSignature: 'token-stagger-path-draw-candidate-wave',
    },
  },
  {
    sceneId: 'arithmetic-03',
    visualId: 'arithmetic-error-cascade-v1',
    fingerprint: {
      primaryPrimitive: 'path',
      cameraMotion: 'parallax',
      depthStyle: 'pseudo-3d',
      entryMechanism: 'draw',
      medium: 'remotion-native',
      direction: 'left-to-right',
      visualFamily: 'causal-error-flow',
      layoutFamily: 'three-step-dependency-route',
      motionSignature: 'single-error-node-red-pulse-cascade',
    },
  },
  {
    sceneId: 'arithmetic-04',
    visualId: 'arithmetic-tool-route-v1',
    fingerprint: {
      primaryPrimitive: 'ui',
      cameraMotion: 'push',
      depthStyle: 'layered-2d',
      entryMechanism: 'assemble',
      medium: 'remotion-native',
      direction: 'depth-forward',
      visualFamily: 'calculator-tool-route',
      layoutFamily: 'input-fork-terminal-return',
      motionSignature: 'route-draw-terminal-type-result-return',
    },
  },
  {
    sceneId: 'arithmetic-05',
    visualId: 'arithmetic-verdict-lock-v1',
    fingerprint: {
      primaryPrimitive: 'object',
      cameraMotion: 'pull',
      depthStyle: 'flat',
      entryMechanism: 'morph',
      medium: 'remotion-native',
      direction: 'outside-in',
      visualFamily: 'verified-number-verdict',
      layoutFamily: 'wrong-vs-verified-final-lock',
      motionSignature: 'wrong-strike-correct-lock-word-stagger-check',
    },
  },
] as const;
