import type {AuthoredVisualScene} from '../../animation-library/authoredProductionGate';

export const AI_AGENTS_VISUAL_PROFILES: readonly AuthoredVisualScene[] = [
  {
    sceneId: 'agents-01',
    visualId: 'ai-agents-chat-vs-autonomous-route-v2',
    fingerprint: {
      primaryPrimitive: 'object',
      cameraMotion: 'push',
      depthStyle: 'layered-2d',
      entryMechanism: 'assemble',
      medium: 'remotion-native',
      direction: 'left-to-right',
      visualFamily: 'agency-comparison',
      layoutFamily: 'split-dialogue-agent-route',
      motionSignature: 'chat-stop-goal-route-result',
    },
  },
  {
    sceneId: 'agents-02',
    visualId: 'ai-agents-radial-tool-orchestration-v2',
    fingerprint: {
      primaryPrimitive: 'nodes',
      cameraMotion: 'orbit',
      depthStyle: 'flat',
      entryMechanism: 'draw',
      medium: 'remotion-native',
      direction: 'center-out',
      visualFamily: 'tool-orchestration',
      layoutFamily: 'radial-agent-tool-field',
      motionSignature: 'core-connect-orbit-select-resolve',
    },
  },
  {
    sceneId: 'agents-03',
    visualId: 'ai-agents-plan-act-check-loop-v2',
    fingerprint: {
      primaryPrimitive: 'nodes',
      cameraMotion: 'locked',
      depthStyle: 'flat',
      entryMechanism: 'draw',
      medium: 'remotion-native',
      direction: 'circular',
      visualFamily: 'agent-loop',
      layoutFamily: 'orbital-plan-act-check',
      motionSignature: 'ring-draw-node-activate-pulse-cycle',
    },
  },
  {
    sceneId: 'agents-04',
    visualId: 'ai-agents-permission-boundary-cascade-v2',
    fingerprint: {
      primaryPrimitive: 'object',
      cameraMotion: 'pull',
      depthStyle: 'layered-2d',
      entryMechanism: 'scale',
      medium: 'remotion-native',
      direction: 'center-out',
      visualFamily: 'permission-risk',
      layoutFamily: 'concentric-rights-boundaries',
      motionSignature: 'rings-expand-actions-cascade-warning',
    },
  },
  {
    sceneId: 'agents-05',
    visualId: 'ai-agents-guardrail-gate-pipeline-v2',
    fingerprint: {
      primaryPrimitive: 'path',
      cameraMotion: 'pan',
      depthStyle: 'flat',
      entryMechanism: 'draw',
      medium: 'remotion-native',
      direction: 'left-to-right',
      visualFamily: 'guardrail-control',
      layoutFamily: 'horizontal-permission-gates',
      motionSignature: 'signal-travel-gate-check-block-continue',
    },
  },
] as const;
