import React from 'react';
import {AbsoluteFill,Easing,Sequence,interpolate,spring,useCurrentFrame,useVideoConfig} from 'remotion';
import {BRAND} from '../../../brand/brand';
import {AnimatedDataPath,DepthStage,KineticType,ObjectTransformation} from '../../visual-system/AdvancedMotionKit';
import {REEL_CAPTION_SAFE} from '../captionSafe';
import {CHATGPT_SECURITY_SCENES,CHATGPT_SECURITY_SUBTITLES,type ChatGPTSecurityScene} from './contract';

const RISK='#C8435E';
const GOOD='#2B8A68';
const clamp=(v:number)=>Math.max(0,Math.min(1,v));
const ease=(frame:number,from:number,to:number)=>interpolate(frame,[from,Math.max(from+1,to)],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.bezier(.16,1,.3,1)});

const CaptionLayer:React.FC<{showCaptions:boolean}>=({showCaptions})=>{const frame=useCurrentFrame();if(!showCaptions)return null;const cue=CHATGPT_SECURITY_SUBTITLES.find((c)=>frame>=c.startFrame&&frame<c.endFrame);if(!cue)return null;const words=cue.text.split(/\s+/).filter(Boolean);const p=clamp((frame-cue.startFrame)/Math.max(1,cue.endFrame-cue.startFrame));const active=Math.min(words.length-1,Math.floor(p*words.length));return <div style={{position:'absolute',left:REEL_CAPTION_SAFE.horizontalInset,right:REEL_CAPTION_SAFE.horizontalInset,bottom:REEL_CAPTION_SAFE.bottom,zIndex:200,display:'flex',justifyContent:'center'}}><div style={{maxWidth:REEL_CAPTION_SAFE.maxWidth,textAlign:'center',fontSize:48,lineHeight:1.08,fontWeight:950,letterSpacing:-1.2,color:BRAND.ink}}>{words.map((w,i)=><React.Fragment key={`${w}-${i}`}><span style={{color:i===active?BRAND.accentDk:BRAND.ink}}>{w}</span>{i<words.length-1?' ':''}</React.Fragment>)}</div></div>};

const Header:React.FC<{label:string;dark?:boolean}>=({label,dark=false})=><div style={{position:'absolute',left:72,right:72,top:62,zIndex:80,textAlign:'center'}}><div style={{fontSize:18,fontWeight:900,letterSpacing:5.2,color:dark?'rgba(234,223,255,.72)':'rgba(110,69,201,.66)',marginBottom:8}}>CHATGPT</div><div style={{fontSize:34,fontWeight:950,letterSpacing:1.6,color:dark?'#EADFFF':BRAND.accentDk}}>{label}</div></div>;
const PhoneShell:React.FC<{x:number;y:number;scale?:number;dark?:boolean}>=({x,y,scale=1,dark=false})=><div style={{position:'absolute',left:x,top:y,width:330,height:610,borderRadius:62,background:dark?'#15131E':'#F9F7FC',border:`10px solid ${dark?'#302943':'#282231'}`,boxShadow:'0 36px 100px rgba(31,20,53,.24)',transform:`scale(${scale})`,transformOrigin:'center'}}><div style={{position:'absolute',left:102,top:15,width:126,height:29,borderRadius:20,background:dark?'#302943':'#282231'}}/><div style={{position:'absolute',left:28,right:28,top:70,height:46,borderRadius:20,background:dark?'#272236':'#ECE8F2'}}><div style={{position:'absolute',left:20,top:15,width:120,height:14,borderRadius:10,background:dark?'#675B7D':'#C9C0D5'}}/></div><div style={{position:'absolute',left:34,right:34,top:148,bottom:42,borderRadius:34,background:dark?'linear-gradient(180deg,#221D31,#16131F)':'linear-gradient(180deg,#fff,#F1ECF8)'}}/></div>;
const ShieldCore:React.FC<{x:number;y:number;size:number;impact?:number}>=({x,y,size,impact=0})=><div style={{position:'absolute',left:x,top:y,width:size,height:size,borderRadius:'50%',background:'radial-gradient(circle at 35% 30%,#FFF,#E9DBFF 34%,#B98CFF 64%,#6E45C9)',border:'6px solid rgba(255,255,255,.72)',boxShadow:`0 0 ${70+impact*70}px rgba(185,140,255,.5),0 35px 110px rgba(35,22,58,.35)`,display:'grid',placeItems:'center',transform:`scale(${1+impact*.08})`}}><div style={{width:size*.33,height:size*.4,borderRadius:28,background:'#fff',position:'relative',boxShadow:'0 12px 35px rgba(40,25,69,.18)'}}><div style={{position:'absolute',left:'20%',right:'20%',top:'-31%',height:'48%',border:'10px solid #6E45C9',borderBottom:0,borderRadius:'50% 50% 0 0'}}/></div></div>;
const EventPill:React.FC<{x:number;y:number;label:string;tone?:'risk'|'good'|'brand';progress?:number}>=({x,y,label,tone='brand',progress=1})=>{const color=tone==='risk'?RISK:tone==='good'?GOOD:BRAND.accentDk;return <div style={{position:'absolute',left:x,top:y,minWidth:210,height:76,padding:'0 24px',borderRadius:28,background:'#fff',border:`3px solid ${color}33`,boxShadow:'0 18px 50px rgba(35,22,58,.12)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:25,fontWeight:950,color,opacity:progress,transform:`scale(${.82+.18*progress}) translateY(${(1-progress)*24}px)`}}>{label}</div>};

// REMOTION_BEAT: security-hook
const SecurityHook:React.FC=()=>{const frame=useCurrentFrame();const {fps}=useVideoConfig();const hit=ease(frame,12,34);const capture=ease(frame,42,96);const pulse=spring({frame:Math.max(0,frame-8),fps,config:{damping:14,stiffness:180,mass:.65}});return <AbsoluteFill style={{background:'radial-gradient(circle at 50% 42%,#302443 0%,#171421 62%,#0D0B12 100%)',overflow:'hidden'}}><Header label="SICHERHEIT" dark/><PhoneShell x={110} y={395} scale={.9} dark/><ShieldCore x={560} y={500} size={330} impact={hit}/><div style={{position:'absolute',left:380+hit*160,top:690-hit*80,width:76,height:76,borderRadius:'50%',background:RISK,boxShadow:'0 0 0 18px rgba(200,67,94,.12),0 0 55px rgba(200,67,94,.55)',transform:`scale(${.8+pulse*.25})`}}/><div style={{position:'absolute',left:365,top:790,width:360,height:8,borderRadius:8,background:`linear-gradient(90deg,${RISK},${BRAND.accent})`,transform:`scaleX(${capture})`,transformOrigin:'left center'}}/><EventPill x={620} y={830} label="UNBEKANNTER LOGIN" tone="risk" progress={capture}/><KineticType text="FREMDER LOGIN?" x={90} y={245} width={900} fontSize={88} color="#FFFFFF" delay={2}/></AbsoluteFill>};

// REMOTION_BEAT: history-flow
const SecurityTimeline:React.FC=()=>{const frame=useCurrentFrame();const p1=ease(frame,12,50),p2=ease(frame,58,98),p3=ease(frame,108,148);return <AbsoluteFill style={{background:'linear-gradient(180deg,#FCFAFF,#F1EBF8)',overflow:'hidden'}}><Header label="SICHERHEITSVERLAUF"/><div style={{position:'absolute',left:100,top:430,width:880,height:620,borderRadius:70,background:'rgba(255,255,255,.72)',border:'2px solid rgba(110,69,201,.10)',boxShadow:'0 36px 100px rgba(45,30,68,.10)'}}/><AnimatedDataPath path="M 80 250 C 220 80, 330 400, 480 240 S 720 100, 820 250" x={130} y={520} width={820} height={480} delay={8} duration={130} stroke={BRAND.accentDk} strokeWidth={10}/><EventPill x={110} y={620} label="LOGIN" progress={p1}/><EventPill x={415} y={820} label="LOGOUT" progress={p2}/><EventPill x={735} y={615} label="MFA / PASSKEY" progress={p3}/><div style={{position:'absolute',left:188,top:1120,fontSize:32,fontWeight:900,color:BRAND.ink,opacity:ease(frame,120,160)}}>ein Verlauf statt einzelner Hinweise</div></AbsoluteFill>};

// REMOTION_BEAT: detail-device
const SecurityDeviceDetails:React.FC=()=>{const frame=useCurrentFrame();const time=ease(frame,36,78),device=ease(frame,66,108),place=ease(frame,96,138);return <AbsoluteFill style={{background:'linear-gradient(155deg,#F7F3FC,#FFFFFF 50%,#EEE6F7)',overflow:'hidden'}}><Header label="WAS KANN EIN EINTRAG ZEIGEN?"/><DepthStage x={110} y={330} width={860} height={900} rotateX={5} rotateY={-7}><PhoneShell x={260} y={80} scale={1}/><div style={{position:'absolute',left:40,top:250,transform:`translate3d(${-70*time}px,${-20*time}px,${120*time}px)`,opacity:time}}><EventPill x={0} y={0} label="ZEIT" progress={time}/></div><div style={{position:'absolute',left:520,top:420,transform:`translate3d(${80*device}px,0,${170*device}px)`,opacity:device}}><EventPill x={0} y={0} label="GERÄT" progress={device}/></div><div style={{position:'absolute',left:60,top:650,transform:`translate3d(${-40*place}px,${30*place}px,${210*place}px)`,opacity:place}}><EventPill x={0} y={0} label="ORT · CA." progress={place}/></div></DepthStage><div style={{position:'absolute',left:150,right:150,top:1190,textAlign:'center',fontSize:25,fontWeight:800,color:'#6B6278',opacity:ease(frame,120,158)}}>Details können ungenau oder nicht verfügbar sein.</div></AbsoluteFill>};

// REMOTION_BEAT: secure-action
const SecurityAction:React.FC=()=>{const frame=useCurrentFrame();const scan=ease(frame,18,92);const gate=ease(frame,44,112);return <AbsoluteFill style={{background:'radial-gradient(circle at 50% 42%,#282033,#171421 65%,#0E0C13)',overflow:'hidden'}}><Header label="AUFFÄLLIG? PRÜFEN." dark/><div style={{position:'absolute',left:140,top:420,width:800,height:470,borderRadius:80,border:'4px solid rgba(185,140,255,.22)',boxShadow:'inset 0 0 90px rgba(185,140,255,.08)',transform:`scale(${.94+gate*.06})`}}><div style={{position:'absolute',left:390,top:40,width:20,height:390,borderRadius:20,background:`linear-gradient(180deg,transparent,${BRAND.accent},transparent)`,transform:`translateX(${(-330+scan*660)}px)`,boxShadow:'0 0 35px rgba(185,140,255,.65)'}}/><ShieldCore x={285} y={85} size={230} impact={gate}/></div><div style={{position:'absolute',left:180,top:965}}><ObjectTransformation fromLabel="UNBEKANNT" toLabel="PRÜFEN & SICHERN" x={0} y={0} width={720} delay={78}/></div><div style={{position:'absolute',left:250,top:1260,width:580,height:10,borderRadius:10,background:'rgba(255,255,255,.12)',overflow:'hidden'}}><div style={{width:`${scan*100}%`,height:'100%',background:`linear-gradient(90deg,${RISK},${BRAND.accent},${GOOD})`}}/></div></AbsoluteFill>};

const visualByScene:Record<string,React.FC>={'security-01':SecurityHook,'security-02':SecurityTimeline,'security-03':SecurityDeviceDetails,'security-04':SecurityAction};
const Scene:React.FC<{scene:ChatGPTSecurityScene}>=({scene})=>{const Visual=visualByScene[scene.sceneId];return <Visual/>};

export type ReelChatGPTSecurityHistoryProps={showCaptions?:boolean};
export const ReelChatGPTSecurityHistory:React.FC<ReelChatGPTSecurityHistoryProps>=({showCaptions=true})=><AbsoluteFill style={{background:'#fff',fontFamily:'Inter,Arial,sans-serif',color:BRAND.ink}}>{CHATGPT_SECURITY_SCENES.map((scene)=><Sequence key={scene.sceneId} from={scene.startFrame} durationInFrames={scene.endFrame-scene.startFrame} layout="none"><Scene scene={scene}/></Sequence>)}<CaptionLayer showCaptions={showCaptions}/></AbsoluteFill>;
