import React from 'react';
import {interpolate, useCurrentFrame} from 'remotion';
import {BRAND} from '../../../brand/brand';

const BUG = '#D95C6A';
const OK = '#4F9D74';
const card: React.CSSProperties = {background:'#fff',border:'2px solid rgba(110,69,201,.18)',borderRadius:30,boxShadow:'0 24px 70px rgba(26,26,46,.10)'};
const label: React.CSSProperties = {fontFamily:BRAND.font,fontWeight:850,fontSize:32,color:BRAND.ink};
const stage: React.CSSProperties = {position:'absolute',left:70,right:70,top:40,bottom:40,display:'flex',alignItems:'center',justifyContent:'center'};
const clamp = (v:number) => Math.max(0, Math.min(1, v));

const AppShell:React.FC<{broken?:boolean;click?:number}> = ({broken=false,click=0}) => <div style={{...card,width:800,height:560,padding:36,position:'relative'}}>
  <div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div style={{...label,fontSize:36}}>Projektboard</div><div style={{width:120,height:18,borderRadius:20,background:'rgba(110,69,201,.14)'}}/></div>
  <div style={{marginTop:34,display:'grid',gridTemplateColumns:'1fr 1fr',gap:24}}>
    <div style={{height:150,borderRadius:24,background:'rgba(185,140,255,.15)',border:'1px solid rgba(110,69,201,.18)'}}/>
    <div style={{height:150,borderRadius:24,background:broken?'rgba(217,92,106,.13)':'rgba(185,140,255,.10)',border:`2px solid ${broken?BUG:'rgba(110,69,201,.18)'}`,display:'flex',alignItems:'center',justifyContent:'center',fontFamily:BRAND.font,fontWeight:850,fontSize:32,color:broken?BUG:BRAND.ink}}>{broken?'Daten fehlen':'Daten bereit'}</div>
  </div>
  <button style={{position:'absolute',left:250,right:250,bottom:42,height:88,borderRadius:28,border:'none',background:BRAND.accentDk,color:'#fff',fontFamily:BRAND.font,fontSize:34,fontWeight:900,transform:`scale(${1-click*.06})`,boxShadow:`0 16px 35px rgba(110,69,201,${.24+click*.2})`}}>Speichern</button>
</div>;

export const BrokenClickVisual:React.FC = () => {const f=useCurrentFrame();const click=clamp(interpolate(f,[38,58],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}));const broken=f>58;const trace=clamp(interpolate(f,[95,190],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}));const rewrite=clamp(interpolate(f,[190,300],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}));return <div style={stage}>
  <div style={{transform:'translateY(-45px)'}}><AppShell broken={broken} click={click}/></div>
  {broken?<div style={{position:'absolute',top:710,left:150,right:150,height:112,borderRadius:26,background:'rgba(217,92,106,.10)',border:`2px solid ${BUG}`,display:'flex',alignItems:'center',justifyContent:'center',...label,color:BUG}}>Fehler reproduziert</div>:null}
  <div style={{position:'absolute',top:850,left:180,width:720,height:12,borderRadius:20,background:'rgba(110,69,201,.10)',overflow:'hidden'}}><div style={{height:'100%',width:`${trace*100}%`,background:BRAND.accentDk}}/></div>
  <div style={{position:'absolute',top:900,left:310,right:310,textAlign:'center',...label,color:BRAND.accentDk,opacity:trace}}>Signal → Ursache eingrenzen</div>
  <div style={{position:'absolute',top:980,left:255,right:255,padding:'20px 28px',...card,textAlign:'center',...label,opacity:rewrite,transform:`scale(${.96+.04*rewrite})`}}><span style={{textDecoration:'line-through',textDecorationThickness:5,textDecorationColor:BUG,color:'rgba(26,26,46,.52)'}}>Alles neu schreiben</span></div>
</div>};

export const ReproduceVisual:React.FC = () => {const f=useCurrentFrame();const p1=clamp(interpolate(f,[0,70],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}));const p2=clamp(interpolate(f,[70,155],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}));const p3=clamp(interpolate(f,[155,240],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}));const pack=clamp(interpolate(f,[240,340],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}));const items=[['1','KLICK','Speichern'],['2','SOLL','Daten bleiben'],['3','IST','Daten fehlen']];return <div style={stage}>
  <div style={{position:'absolute',top:115,left:105,right:105,display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:22}}>{items.map((x,i)=>{const p=[p1,p2,p3][i];return <div key={x[0]} style={{...card,height:260,padding:26,opacity:p,transform:`translateY(${(1-p)*28}px)`}}><div style={{fontSize:28,fontFamily:BRAND.font,fontWeight:900,color:BRAND.accentDk}}>{x[0]} · {x[1]}</div><div style={{marginTop:54,...label,fontSize:34,textAlign:'center',color:i===2?BUG:BRAND.ink}}>{x[2]}</div></div>})}</div>
  <div style={{position:'absolute',top:465,left:140,right:140,display:'flex',gap:22,opacity:p3}}><div style={{...card,flex:1,padding:28,borderColor:'rgba(217,92,106,.38)'}}><div style={{...label,color:BUG}}>ERROR</div><div style={{marginTop:16,fontFamily:'monospace',fontSize:29,color:BRAND.ink}}>state.items = undefined</div></div><div style={{...card,flex:1,padding:28}}><div style={{...label,color:BRAND.accentDk}}>CODE</div><div style={{marginTop:16,fontFamily:'monospace',fontSize:29,color:BRAND.ink}}>save(items.length)</div></div></div>
  <div style={{position:'absolute',top:760,left:220,right:220,height:170,...card,display:'flex',alignItems:'center',justifyContent:'center',...label,fontSize:38,color:BRAND.accentDk,opacity:pack,transform:`scale(${.92+.08*pack})`}}>Debug-Paket komplett</div>
</div>};

export const TraceVisual:React.FC = () => {const f=useCurrentFrame();const progress=clamp(interpolate(f,[20,230],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}));const focus=clamp(interpolate(f,[220,330],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}));const nodes=['UI','Handler','State','API'];return <div style={stage}>
  <div style={{position:'absolute',top:210,left:90,right:90,height:260,display:'flex',alignItems:'center',justifyContent:'space-between'}}>{nodes.map((n,i)=>{const active=progress>=i/(nodes.length-1);return <React.Fragment key={n}><div style={{width:165,height:165,borderRadius:34,display:'flex',alignItems:'center',justifyContent:'center',...card,...label,fontSize:36,color:active?BRAND.accentDk:BRAND.ink,borderColor:i===2&&focus>.4?BUG:'rgba(110,69,201,.18)',boxShadow:i===2&&focus>.4?'0 0 0 10px rgba(217,92,106,.10)':'0 24px 70px rgba(26,26,46,.10)'}}>{n}</div>{i<nodes.length-1?<div style={{height:10,flex:1,margin:'0 12px',borderRadius:10,background:'rgba(110,69,201,.10)',overflow:'hidden'}}><div style={{height:'100%',width:`${clamp((progress-i/(nodes.length-1))*3)*100}%`,background:BRAND.accentDk}}/></div>:null}</React.Fragment>})}</div>
  <div style={{position:'absolute',top:570,left:210,right:210,...card,padding:34,opacity:clamp(interpolate(f,[130,220],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}))}}><div style={{...label,fontSize:30,color:'rgba(26,26,46,.62)'}}>Bedingung</div><div style={{marginTop:22,display:'flex',gap:20}}><div style={{flex:1,padding:24,borderRadius:22,background:'rgba(79,157,116,.10)',...label,color:OK}}>items vorhanden</div><div style={{flex:1,padding:24,borderRadius:22,background:'rgba(217,92,106,.10)',...label,color:BUG,border:`2px solid ${focus>.4?BUG:'transparent'}`}}>items fehlt</div></div></div>
  <div style={{position:'absolute',top:865,left:260,right:260,textAlign:'center',...label,fontSize:40,color:BUG,opacity:focus}}>Bruch gefunden</div>
</div>};

export const PatchTestsVisual:React.FC = () => {const f=useCurrentFrame();const patch=clamp(interpolate(f,[0,95],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}));const explain=clamp(interpolate(f,[95,180],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}));const tests=clamp(interpolate(f,[180,340],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}));return <div style={stage}>
  <div style={{position:'absolute',top:95,left:120,right:120,...card,padding:34,opacity:patch}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div style={{...label,color:BRAND.accentDk}}>MINIMALER PATCH</div><div style={{fontFamily:BRAND.font,fontWeight:850,fontSize:28,color:'rgba(26,26,46,.56)'}}>2 Zeilen</div></div><div style={{marginTop:30,fontFamily:'monospace',fontSize:31,lineHeight:1.7}}><div style={{color:BUG,background:'rgba(217,92,106,.08)',padding:'4px 12px',borderRadius:12}}>- save(items.length)</div><div style={{color:OK,background:'rgba(79,157,116,.08)',padding:'4px 12px',borderRadius:12}}>+ save((items ?? []).length)</div></div></div>
  <div style={{position:'absolute',top:470,left:170,right:170,padding:26,...card,opacity:explain,textAlign:'center',...label,fontSize:32}}>Nur die betroffene Stelle ändern</div>
  <div style={{position:'absolute',top:650,left:115,right:115,display:'grid',gap:20}}>{['Speichern','Leere Liste','Andere Ansicht'].map((t,i)=>{const done=tests>(i+1)/3;return <div key={t} style={{...card,height:112,padding:'0 28px',display:'flex',alignItems:'center',justifyContent:'space-between'}}><span style={label}>{t}</span><span style={{...label,color:done?OK:'rgba(26,26,46,.35)'}}>{done?'BESTANDEN':'TEST LÄUFT'}</span></div>})}</div>
</div>};

export const VerifyVisual:React.FC = () => {const f=useCurrentFrame();const click=clamp(interpolate(f,[10,70],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}));const clean=f>70;const tests=clamp(interpolate(f,[120,260],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}));const verified=clamp(interpolate(f,[270,350],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}));return <div style={stage}>
  <div style={{transform:'translateY(-110px) scale(.86)'}}><AppShell broken={!clean} click={click}/></div>
  <div style={{position:'absolute',top:650,left:130,right:130,display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:18}}>{['Bug weg','Tests grün','Rest läuft'].map((t,i)=>{const on=tests>(i+1)/3;return <div key={t} style={{...card,height:145,display:'flex',alignItems:'center',justifyContent:'center',textAlign:'center',...label,fontSize:30,color:on?OK:'rgba(26,26,46,.35)',borderColor:on?'rgba(79,157,116,.45)':'rgba(110,69,201,.18)'}}>{t}</div>})}</div>
  <div style={{position:'absolute',top:875,left:240,right:240,height:150,borderRadius:44,background:'rgba(79,157,116,.12)',border:'3px solid rgba(79,157,116,.55)',display:'flex',alignItems:'center',justifyContent:'center',fontFamily:BRAND.font,fontWeight:950,fontSize:48,color:OK,letterSpacing:1.2,opacity:verified,transform:`scale(${.88+.12*verified})`}}>VERIFIZIERT</div>
</div>};
