import React,{useMemo} from 'react';
import {AbsoluteFill,Html5Audio,Sequence,interpolate,useCurrentFrame} from 'remotion';
import {BRAND} from '../../../brand/brand';
import {AI_APP_WORKFLOW_CHAPTERS,type LongformChapter} from './contract';
import {BranchVisual,BuildVisual,FinishVisual,FlowVisual,HookVisual,RepoVisual,ScopeVisual,TestVisual} from './Visuals';

const visuals:Record<LongformChapter['id'],React.FC>={hook:HookVisual,scope:ScopeVisual,flow:FlowVisual,repo:RepoVisual,build:BuildVisual,test:TestVisual,branch:BranchVisual,finish:FinishVisual};

const Chapter:React.FC<{chapter:LongformChapter;index:number}>=({chapter,index})=>{const frame=useCurrentFrame();const enter=interpolate(frame,[0,18],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});const Visual=visuals[chapter.id];return <AbsoluteFill><div style={{position:'absolute',left:76,top:58,zIndex:50,display:'flex',gap:18,alignItems:'center',opacity:enter}}><div style={{width:54,height:54,borderRadius:18,background:'rgba(185,140,255,.18)',display:'grid',placeItems:'center',fontFamily:BRAND.font,fontWeight:900,fontSize:23,color:BRAND.accentDk}}>{index+1}</div><div style={{fontFamily:BRAND.font,fontWeight:900,fontSize:38,letterSpacing:-1.2,color:BRAND.accentDk}}>{chapter.title}</div></div><Visual/></AbsoluteFill>};

export type LongformAIAppWorkflowProps={voiceoverSrc?:string};
export const LongformAIAppWorkflow:React.FC<LongformAIAppWorkflowProps>=({voiceoverSrc})=>{const chapters=useMemo(()=>AI_APP_WORKFLOW_CHAPTERS,[]);const frame=useCurrentFrame();const total=chapters[chapters.length-1].endFrame;const progress=Math.min(1,frame/total);return <AbsoluteFill style={{background:'radial-gradient(circle at 50% 38%,#FFFFFF 0%,#FAF8FC 62%,#F1EDF6 100%)',color:BRAND.ink,fontFamily:BRAND.font,overflow:'hidden'}}><div style={{position:'absolute',inset:0,background:'linear-gradient(rgba(110,69,201,.018) 1px,transparent 1px),linear-gradient(90deg,rgba(110,69,201,.018) 1px,transparent 1px)',backgroundSize:'80px 80px'}}/>{chapters.map((chapter,index)=><Sequence key={chapter.id} from={chapter.startFrame} durationInFrames={chapter.endFrame-chapter.startFrame}><Chapter chapter={chapter} index={index}/></Sequence>)}<div style={{position:'absolute',left:70,right:70,bottom:34,height:6,borderRadius:9,background:'rgba(26,26,46,.08)',zIndex:100}}><div style={{height:'100%',width:`${progress*100}%`,borderRadius:9,background:BRAND.accentDk}}/></div>{voiceoverSrc?<Html5Audio src={voiceoverSrc}/>:null}</AbsoluteFill>};
