import type {AuthoredVisualScene} from '../../animation-library/authoredProductionGate';

export const AI_APP_WORKFLOW_VISUAL_PROFILES: readonly AuthoredVisualScene[] = [
  {
    sceneId: 'hook',
    visualId: 'longform-app-prompt-blueprint-v2',
    fingerprint: {
      primaryPrimitive: 'typography',
      cameraMotion: 'push',
      depthStyle: 'layered-2d',
      entryMechanism: 'assemble',
      medium: 'remotion-native',
      direction: 'center-out',
      visualFamily: 'prompt-to-system-blueprint',
      layoutFamily: 'prompt-split-radial-app-blueprint',
      motionSignature: 'prompt-enter-split-blueprint-assemble-resolve',
    },
  },
  {
    sceneId: 'scope',
    visualId: 'longform-app-scope-funnel-v2',
    fingerprint: {
      primaryPrimitive: 'illustration',
      cameraMotion: 'locked',
      depthStyle: 'flat',
      entryMechanism: 'mask',
      medium: 'remotion-native',
      direction: 'top-to-bottom',
      visualFamily: 'scope-reduction',
      layoutFamily: 'wide-constraint-funnel',
      motionSignature: 'constraints-enter-extras-prune-scope-lock',
    },
  },
  {
    sceneId: 'flow',
    visualId: 'longform-app-state-route-v2',
    fingerprint: {
      primaryPrimitive: 'path',
      cameraMotion: 'pan',
      depthStyle: 'layered-2d',
      entryMechanism: 'draw',
      medium: 'remotion-native',
      direction: 'left-to-right',
      visualFamily: 'user-state-flow',
      layoutFamily: 'curved-state-route',
      motionSignature: 'route-draw-state-token-travel-resolve',
    },
  },
  {
    sceneId: 'repo',
    visualId: 'longform-app-repo-depth-history-v2',
    fingerprint: {
      primaryPrimitive: 'object',
      cameraMotion: 'orbit',
      depthStyle: 'pseudo-3d',
      entryMechanism: 'depth',
      medium: 'remotion-native',
      direction: 'depth-forward',
      visualFamily: 'repository-memory',
      layoutFamily: 'depth-file-stack-history-line',
      motionSignature: 'files-layer-history-draw-memory-resolve',
    },
  },
  {
    sceneId: 'build',
    visualId: 'longform-app-build-brief-route-v2',
    fingerprint: {
      primaryPrimitive: 'mixed',
      cameraMotion: 'pull',
      depthStyle: 'layered-2d',
      entryMechanism: 'draw',
      medium: 'remotion-native',
      direction: 'left-to-right',
      visualFamily: 'bounded-build-change',
      layoutFamily: 'brief-to-build-route',
      motionSignature: 'brief-fill-change-route-build-confirm',
    },
  },
  {
    sceneId: 'test',
    visualId: 'longform-app-xray-test-repair-v2',
    fingerprint: {
      primaryPrimitive: 'illustration',
      cameraMotion: 'pan',
      depthStyle: 'flat',
      entryMechanism: 'mask',
      medium: 'remotion-native',
      direction: 'left-to-right',
      visualFamily: 'diagnostic-repair',
      layoutFamily: 'wide-app-xray-stage',
      motionSignature: 'scan-detect-localize-patch-recheck',
    },
  },
  {
    sceneId: 'branch',
    visualId: 'longform-app-branch-depth-review-v2',
    fingerprint: {
      primaryPrimitive: 'object',
      cameraMotion: 'push',
      depthStyle: 'pseudo-3d',
      entryMechanism: 'depth',
      medium: 'remotion-native',
      direction: 'mixed',
      visualFamily: 'branch-review-safety',
      layoutFamily: 'split-depth-lanes-review-gate',
      motionSignature: 'main-hold-experiment-split-review-merge',
    },
  },
  {
    sceneId: 'finish',
    visualId: 'longform-app-system-assembly-v2',
    fingerprint: {
      primaryPrimitive: 'nodes',
      cameraMotion: 'orbit',
      depthStyle: 'layered-2d',
      entryMechanism: 'assemble',
      medium: 'remotion-native',
      direction: 'center-out',
      visualFamily: 'verified-system',
      layoutFamily: 'radial-workflow-system',
      motionSignature: 'system-nodes-enter-connect-core-verify',
    },
  },
] as const;
