import React from 'react';
import {interpolate,spring,useCurrentFrame,useVideoConfig} from 'remotion';
import {BRAND} from '../../../brand/brand';

const ink=BRAND.ink, purple=BRAND.accentDk, light=BRAND.bgDeep;
const card:React.CSSProperties={background:'#fff',border:'1px solid rgba(110,69,201,.16)',borderRadius:28,boxShadow:'0 24px 70px rgba(26,26,46,.10)'};
const label:React.CSSProperties={fontFamily:BRAND.font,fontWeight:850,letterSpacing:-.7,color:ink};
const p=(f:number,a:number,b:number)=>interpolate(f,[a,b],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});
const Chip:React.FC<{children:React.ReactNode;accent?:boolean}> = ({children,accent}) => <div style={{padding:'12px 18px',borderRadius:999,background:accent?'rgba(185,140,255,.20)':'#F5F2F8',color:accent?purple:ink,fontFamily:BRAND.font,fontWeight:800,fontSize:24}}>{children}</div>;
const AppWindow:React.FC<{done?:boolean;scale?:number}> = ({done=false,scale=1}) => <div style={{...card,width:680,height:430,transform:`scale(${scale})`,overflow:'hidden'}}><div style={{height:48,background:'#F5F2F8',display:'flex',alignItems:'center',gap:10,padding:'0 20px'}}>{[0,1,2].map(i=><span key={i} style={{width:12,height:12,borderRadius:'50%',background:i===0?'#D9A3A3':i===1?'#E5CF8D':'#A8D7B5'}}/> )}</div><div style={{padding:34}}><div style={{fontFamily:BRAND.font,fontSize:32,fontWeight:900,color:ink,marginBottom:26}}>Aufgaben</div><div style={{display:'flex',gap:14}}><div style={{height:54,flex:1,borderRadius:16,border:'2px solid #E7E1EE',background:'#fff'}}/><div style={{height:54,width:150,borderRadius:16,background:purple,color:'#fff',display:'grid',placeItems:'center',fontFamily:BRAND.font,fontWeight:850}}>Hinzufügen</div></div><div style={{marginTop:30,display:'grid',gap:16}}>{['Landingpage prüfen','Fehler testen','Version sichern'].map((x,i)=><div key={x} style={{height:64,borderRadius:17,background:i===0&&done?'#ECF8F0':'#F8F6FA',display:'flex',alignItems:'center',gap:18,padding:'0 20px',fontFamily:BRAND.font,fontWeight:760,fontSize:24,color:ink}}><span style={{width:24,height:24,borderRadius:7,border:`2px solid ${i===0&&done?'#3A9B64':'#C8BDD3'}`,background:i===0&&done?'#3A9B64':'transparent'}}/>{x}</div>)}</div></div></div>;

export const HookVisual:React.FC=()=>{const f=useCurrentFrame();const cfg=useVideoConfig();const s=spring({frame:f,fps:cfg.fps,config:{damping:18}});const shift=p(f,130,360);const steps=p(f,300,560);return <div style={{position:'absolute',inset:0,display:'flex',alignItems:'center',justifyContent:'center'}}><div style={{position:'absolute',left:160,top:260,width:560,...card,padding:40,transform:`translateX(${-220*shift}px) scale(${1-.08*shift})`,opacity:.98}}><div style={{...label,fontSize:28,color:purple,marginBottom:18}}>PROMPT</div><div style={{...label,fontSize:48,lineHeight:1.05}}>Bau mir eine App.</div><div style={{marginTop:30,display:'flex',gap:10,opacity:.45}}>{[0,1,2,3].map(i=><div key={i} style={{width:95+i*22,height:12,borderRadius:10,background:'#CFC5D8'}}/>)}</div></div><div style={{position:'absolute',right:130,top:215,opacity:.3+.7*shift,transform:`translateX(${180*(1-shift)}px) scale(${.88+.12*s})`}}><AppWindow done={steps>.7}/></div><div style={{position:'absolute',left:680,right:720,top:720,display:'flex',justifyContent:'center',gap:14,opacity:steps}}>{['PROBLEM','FLOW','BUILD','TEST'].map((x,i)=><Chip key={x} accent={i<=Math.floor(steps*4)}>{x}</Chip>)}</div></div>};

export const ScopeVisual:React.FC=()=>{const f=useCurrentFrame();const reveal=p(f,0,250);const prune=p(f,430,760);const items=[['NUTZER','Wer?'],['EINGABE','Was kommt rein?'],['ERGEBNIS','Was soll passieren?']];return <div style={{position:'absolute',inset:0,display:'grid',placeItems:'center'}}><div style={{display:'flex',gap:34,alignItems:'center'}}>{items.map((x,i)=><React.Fragment key={x[0]}><div style={{...card,width:360,height:250,padding:32,opacity:p(f,40+i*70,150+i*70),transform:`translateY(${30*(1-p(f,40+i*70,150+i*70))}px)`}}><div style={{...label,fontSize:26,color:purple}}>{x[0]}</div><div style={{...label,fontSize:42,marginTop:42}}>{x[1]}</div></div>{i<2?<div style={{fontSize:46,color:purple,opacity:reveal}}>→</div>:null}</React.Fragment>)}</div><div style={{position:'absolute',bottom:140,display:'flex',gap:18,opacity:prune}}>{['Chat','Kalender','Team','Statistik','Gamification'].map((x,i)=><div key={x} style={{...card,padding:'16px 22px',fontFamily:BRAND.font,fontSize:22,fontWeight:750,color:'#8D8197',textDecoration:'line-through',transform:`scale(${1-.08*prune})`,opacity:.55}}>{x}</div>)}</div></div>};

export const FlowVisual:React.FC=()=>{const f=useCurrentFrame();const progress=p(f,60,850);const nodes=[['EINGABE',260],['DATEN',650],['AKTION',1040],['ZUSTAND',1430]];return <div style={{position:'absolute',inset:0,display:'grid',placeItems:'center'}}><svg width="1500" height="480" viewBox="0 0 1500 480" style={{position:'absolute'}}><path d="M190 240 H1310" stroke="#E2D8EC" strokeWidth="18" strokeLinecap="round"/><path d="M190 240 H1310" stroke={purple} strokeWidth="18" strokeLinecap="round" strokeDasharray="1120" strokeDashoffset={1120*(1-progress)}/></svg>{nodes.map((x,i)=>{const active=progress>i/4-.03;return <div key={x[0]} style={{position:'absolute',left:x[1]-145,top:330,width:290,height:170,...card,display:'grid',placeItems:'center',transform:`scale(${active?1:.88})`,opacity:active?1:.35}}><div style={{...label,fontSize:30,color:active?purple:ink}}>{x[0]}</div></div>})}<div style={{position:'absolute',right:150,top:180,transform:`scale(${.85+.15*p(f,650,950)})`,opacity:p(f,650,900)}}><AppWindow done={progress>.8} scale={.72}/></div></div>};

export const RepoVisual:React.FC=()=>{const f=useCurrentFrame();const organize=p(f,20,320);const commit=p(f,420,760);const files=['ui/','logic/','data/','components/'];return <div style={{position:'absolute',inset:0,display:'flex',alignItems:'center',justifyContent:'center',gap:100}}><div style={{...card,width:640,height:620,padding:38}}><div style={{...label,fontSize:31,color:purple,marginBottom:30}}>projekt/</div>{files.map((x,i)=><div key={x} style={{height:90,marginBottom:18,borderRadius:20,background:'#F7F4FA',display:'flex',alignItems:'center',padding:'0 26px',gap:18,transform:`translateX(${(1-organize)*(i%2?70:-70)}px)`,opacity:.35+.65*organize}}><span style={{width:34,height:28,borderRadius:7,background:i===0?'#C8A8FA':'#DED4E8'}}/><span style={{...label,fontSize:28}}>{x}</span></div>)}</div><div style={{width:760,height:420,position:'relative'}}><div style={{position:'absolute',left:60,right:60,top:210,height:14,background:'#E3DBEA',borderRadius:20}}/><div style={{position:'absolute',left:60,top:210,height:14,width:`${commit*640}px`,background:purple,borderRadius:20}}/>{[0,1,2,3].map((i)=><div key={i} style={{position:'absolute',left:60+i*210,top:185,width:62,height:62,borderRadius:'50%',background:i<=Math.floor(commit*3)?purple:'#D8CEDF',border:'10px solid #fff',boxShadow:'0 8px 25px rgba(26,26,46,.12)'}}/>)}<div style={{position:'absolute',top:285,left:60,...label,fontSize:28,color:purple,opacity:commit}}>STABILER COMMIT</div></div></div>};

export const BuildVisual:React.FC=()=>{const f=useCurrentFrame();const q=p(f,0,500);const build=p(f,620,1250);const fields=['IST-ZUSTAND','ÄNDERUNG','GRENZE','TEST'];return <div style={{position:'absolute',inset:0,display:'flex',alignItems:'center',justifyContent:'center',gap:90}}><div style={{...card,width:680,padding:34}}><div style={{...label,fontSize:28,color:purple,marginBottom:26}}>GUTER ARBEITSAUFTRAG</div>{fields.map((x,i)=><div key={x} style={{height:82,borderRadius:18,background:i<=Math.floor(q*4)?'rgba(185,140,255,.16)':'#F7F4FA',marginBottom:14,display:'flex',alignItems:'center',padding:'0 24px',...label,fontSize:27,color:i<=Math.floor(q*4)?purple:ink}}>{i+1}. {x}</div>)}</div><div style={{position:'relative',width:820,height:620}}><div style={{position:'absolute',left:70,top:70,opacity:p(f,500,720),transform:`translateX(${-50*(1-p(f,500,720))}px)`}}><Chip accent>KONKRETE AUFGABE</Chip></div><div style={{position:'absolute',right:20,top:130,opacity:p(f,650,820),transform:`scale(${.86+.14*build})`}}><AppWindow done={build>.65} scale={.88}/></div><div style={{position:'absolute',right:130,bottom:20,opacity:p(f,1050,1250)}}><Chip accent>✓ TEST BESTANDEN</Chip></div></div></div>};

export const TestVisual:React.FC=()=>{const f=useCurrentFrame();const fail=p(f,250,520);const reproduce=p(f,520,850);const fix=p(f,850,1180);return <div style={{position:'absolute',inset:0,display:'flex',alignItems:'center',justifyContent:'center',gap:95}}><div style={{transform:'scale(.95)'}}><AppWindow done={fix>.7}/></div><div style={{width:620,height:610,...card,padding:38}}><div style={{...label,fontSize:30,color:purple}}>TESTPFAD</div><div style={{marginTop:32,display:'grid',gap:18}}>{['1  Leere Eingabe','2  Button klicken','3  Zustand prüfen'].map((x,i)=><div key={x} style={{height:82,borderRadius:18,background:reproduce>i/3?'rgba(185,140,255,.16)':'#F7F4FA',display:'flex',alignItems:'center',padding:'0 24px',...label,fontSize:27}}>{x}</div>)}</div><div style={{marginTop:34,height:100,borderRadius:20,background:fix>.75?'#E8F6ED':fail>.4?'#FBECEC':'#F7F4FA',display:'grid',placeItems:'center',...label,fontSize:28,color:fix>.75?'#2E8454':fail>.4?'#B24D4D':ink}}>{fix>.75?'✓ FIX VERIFIZIERT':fail>.4?'FEHLER REPRODUZIERT':'TEST LÄUFT'}</div></div></div>};

export const BranchVisual:React.FC=()=>{const f=useCurrentFrame();const branch=p(f,60,300);const merge=p(f,420,720);return <div style={{position:'absolute',inset:0,display:'grid',placeItems:'center'}}><svg width="1500" height="620" viewBox="0 0 1500 620"><path d="M120 310 H1380" stroke="#D9CFDF" strokeWidth="18" strokeLinecap="round"/><path d="M420 310 C560 310 560 120 720 120 H1000 C1120 120 1120 310 1260 310" stroke={purple} strokeWidth="18" strokeLinecap="round" fill="none" strokeDasharray="1180" strokeDashoffset={1180*(1-branch)}/>{[120,420,1260,1380].map((x,i)=><circle key={x} cx={x} cy="310" r="28" fill={i<3?purple:'#B7A9C1'} stroke="#fff" strokeWidth="10"/>)}<circle cx="760" cy="120" r="28" fill={branch>.5?purple:'#D9CFDF'} stroke="#fff" strokeWidth="10"/><circle cx="1000" cy="120" r="28" fill={merge>.5?'#3A9B64':purple} stroke="#fff" strokeWidth="10"/></svg><div style={{position:'absolute',left:250,top:700}}><Chip>STABIL</Chip></div><div style={{position:'absolute',left:810,top:220,opacity:branch}}><Chip accent>EXPERIMENT</Chip></div><div style={{position:'absolute',right:270,top:700,opacity:merge}}><Chip accent>MERGE</Chip></div></div>};

export const FinishVisual:React.FC=()=>{const f=useCurrentFrame();const checks=p(f,100,620);const pipe=p(f,650,1100);const steps=['PROBLEM','FLOW','REPO','BUILD','TEST','SICHERN'];return <div style={{position:'absolute',inset:0,display:'flex',alignItems:'center',justifyContent:'center',gap:90}}><div style={{transform:'scale(.9)'}}><AppWindow done/></div><div style={{width:780}}><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:16}}>{['NUTZERWEG','ZUSTÄNDE','ÄNDERUNGEN'].map((x,i)=><div key={x} style={{...card,height:130,display:'grid',placeItems:'center',...label,fontSize:24,color:checks>(i+.2)/3?'#2E8454':ink,opacity:.45+.55*checks}}>{checks>(i+.2)/3?'✓ ':''}{x}</div>)}</div><div style={{marginTop:46,display:'flex',flexWrap:'wrap',gap:14,opacity:pipe}}>{steps.map((x,i)=><React.Fragment key={x}><Chip accent={i<=Math.floor(pipe*steps.length)}>{x}</Chip>{i<steps.length-1?<span style={{fontSize:28,color:purple,alignSelf:'center'}}>→</span>:null}</React.Fragment>)}</div></div></div>};
