import type {AuthoredVisualScene} from '../../animation-library/authoredProductionGate';

export const AI_APP_WORKFLOW_VISUAL_PROFILES: readonly AuthoredVisualScene[] = [
  {
    sceneId: 'hook',
    visualId: 'longform-app-prompt-system-hero-v3',
    fingerprint: {
      primaryPrimitive: 'typography',
      cameraMotion: 'push',
      depthStyle: 'layered-2d',
      entryMechanism: 'assemble',
      medium: 'remotion-native',
      direction: 'center-out',
      visualFamily: 'prompt-to-system-hero',
      layoutFamily: 'editorial-prompt-blueprint-core',
      motionSignature: 'prompt-fracture-blueprints-core-resolve',
    },
  },
  {
    sceneId: 'scope',
    visualId: 'longform-app-scope-pruning-core-v3',
    fingerprint: {
      primaryPrimitive: 'illustration',
      cameraMotion: 'pull',
      depthStyle: 'layered-2d',
      entryMechanism: 'morph',
      medium: 'remotion-native',
      direction: 'outside-in',
      visualFamily: 'scope-pruning',
      layoutFamily: 'wide-pruning-field-core-lock',
      motionSignature: 'feature-flood-prune-compress-core-lock',
    },
  },
  {
    sceneId: 'flow',
    visualId: 'longform-app-state-track-v3',
    fingerprint: {
      primaryPrimitive: 'path',
      cameraMotion: 'pan',
      depthStyle: 'layered-2d',
      entryMechanism: 'draw',
      medium: 'remotion-native',
      direction: 'left-to-right',
      visualFamily: 'state-track',
      layoutFamily: 'wide-serpentine-state-track',
      motionSignature: 'track-establish-token-travel-state-transform',
    },
  },
  {
    sceneId: 'repo',
    visualId: 'longform-app-exploded-repo-memory-v3',
    fingerprint: {
      primaryPrimitive: 'object',
      cameraMotion: 'orbit',
      depthStyle: 'pseudo-3d',
      entryMechanism: 'depth',
      medium: 'remotion-native',
      direction: 'depth-forward',
      visualFamily: 'repository-memory',
      layoutFamily: 'exploded-file-stack-history-stage',
      motionSignature: 'files-reveal-depth-spread-history-resolve',
    },
  },
  {
    sceneId: 'build',
    visualId: 'longform-app-bounded-build-core-v3',
    fingerprint: {
      primaryPrimitive: 'mixed',
      cameraMotion: 'pull',
      depthStyle: 'layered-2d',
      entryMechanism: 'assemble',
      medium: 'remotion-native',
      direction: 'left-to-right',
      visualFamily: 'bounded-build',
      layoutFamily: 'constraints-to-large-build-core',
      motionSignature: 'constraints-enter-route-feed-build-verify',
    },
  },
  {
    sceneId: 'test',
    visualId: 'longform-app-xray-repair-stage-v3',
    fingerprint: {
      primaryPrimitive: 'ui',
      cameraMotion: 'pan',
      depthStyle: 'layered-2d',
      entryMechanism: 'mask',
      medium: 'remotion-native',
      direction: 'left-to-right',
      visualFamily: 'diagnostic-repair',
      layoutFamily: 'full-width-app-xray-repair-stage',
      motionSignature: 'app-enter-scan-detect-patch-verify',
    },
  },
  {
    sceneId: 'branch',
    visualId: 'longform-app-depth-branch-gate-v3',
    fingerprint: {
      primaryPrimitive: 'object',
      cameraMotion: 'push',
      depthStyle: 'pseudo-3d',
      entryMechanism: 'depth',
      medium: 'remotion-native',
      direction: 'mixed',
      visualFamily: 'branch-review-safety',
      layoutFamily: 'large-depth-lanes-review-gate',
      motionSignature: 'main-anchor-branch-split-work-review-merge',
    },
  },
  {
    sceneId: 'finish',
    visualId: 'longform-app-dark-system-assembly-v3',
    fingerprint: {
      primaryPrimitive: 'nodes',
      cameraMotion: 'orbit',
      depthStyle: 'layered-2d',
      entryMechanism: 'assemble',
      medium: 'remotion-native',
      direction: 'center-out',
      visualFamily: 'verified-system-finale',
      layoutFamily: 'dark-radial-system-hero',
      motionSignature: 'chapter-nodes-gather-core-lock-verify',
    },
  },
] as const;
