import React,{useMemo} from 'react';
import {AbsoluteFill,Html5Audio,Sequence,interpolate,useCurrentFrame} from 'remotion';
import {BRAND} from '../../../brand/brand';
import {AGENT_LOOP_CHAPTERS,type AgentLoopChapter,type AgentLoopChapterId} from './contract';
import {AnatomyVisual,CompareVisual,ExampleVisual,FitVisual,GuardrailsVisual,HookVisual,LoopVisual,RisksVisual,ToolsVisual} from './Visuals';

const visualByChapter:Record<AgentLoopChapterId,React.FC<{beats:number[]}>>={hook:HookVisual,compare:CompareVisual,anatomy:AnatomyVisual,loop:LoopVisual,example:ExampleVisual,tools:ToolsVisual,risks:RisksVisual,guardrails:GuardrailsVisual,fit:FitVisual};

const ChapterLayer:React.FC<{chapter:AgentLoopChapter;index:number}>=({chapter,index})=>{const frame=useCurrentFrame();const enter=interpolate(frame,[0,18,90,120],[0,1,1,0],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});const Visual=visualByChapter[chapter.id];return <AbsoluteFill><div style={{position:'absolute',left:72,top:52,zIndex:80,display:'flex',alignItems:'center',gap:16,opacity:enter}}><div style={{width:50,height:50,borderRadius:16,background:'rgba(185,140,255,.18)',display:'grid',placeItems:'center',fontFamily:BRAND.font,fontWeight:900,fontSize:21,color:BRAND.accentDk}}>{index+1}</div><div style={{fontFamily:BRAND.font,fontWeight:900,fontSize:36,letterSpacing:-1.1,color:BRAND.accentDk}}>{chapter.title}</div></div><Visual beats={chapter.beatFrames}/></AbsoluteFill>};

export type LongformAgentLoopProps={voiceoverSrc?:string};
export const LongformAgentLoop:React.FC<LongformAgentLoopProps>=({voiceoverSrc})=>{const chapters=useMemo(()=>AGENT_LOOP_CHAPTERS,[]);const frame=useCurrentFrame();const total=chapters.at(-1)?.endFrame??1;const progress=Math.min(1,frame/total);return <AbsoluteFill style={{background:'radial-gradient(circle at 50% 38%,#FFFFFF 0%,#FAF8FC 62%,#F1EDF6 100%)',color:BRAND.ink,fontFamily:BRAND.font,overflow:'hidden'}}><div style={{position:'absolute',inset:0,background:'linear-gradient(rgba(110,69,201,.018) 1px,transparent 1px),linear-gradient(90deg,rgba(110,69,201,.018) 1px,transparent 1px)',backgroundSize:'80px 80px'}}/>{chapters.map((chapter,index)=><Sequence key={chapter.id} from={chapter.startFrame} durationInFrames={chapter.endFrame-chapter.startFrame} name={`${chapter.id}-${chapter.beatFrames.length}-beats`}><ChapterLayer chapter={chapter} index={index}/></Sequence>)}<div style={{position:'absolute',left:70,right:70,bottom:34,height:6,borderRadius:9,background:'rgba(26,26,46,.08)',zIndex:100}}><div style={{height:'100%',width:`${progress*100}%`,borderRadius:9,background:BRAND.accentDk}}/></div>{voiceoverSrc?<Html5Audio src={voiceoverSrc}/>:null}</AbsoluteFill>};
