import React from 'react';
import {interpolate,spring,useCurrentFrame,useVideoConfig} from 'remotion';
import {BRAND} from '../../../brand/brand';

const ink=BRAND.ink,purple=BRAND.accentDk,accent=BRAND.accent,green='#31875A',red='#B64D58',muted='#8D8197';
const card:React.CSSProperties={background:'#fff',border:'1px solid rgba(110,69,201,.16)',borderRadius:28,boxShadow:'0 24px 70px rgba(26,26,46,.10)'};
const label:React.CSSProperties={fontFamily:BRAND.font,fontWeight:850,letterSpacing:-.7,color:ink};
const p=(f:number,a:number,b:number)=>interpolate(f,[a,b],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});
const on=(f:number,at:number)=>p(f,at,at+55);
const beatCount=(f:number,beats:number[])=>beats.filter(b=>f>=b).length;

const Pill:React.FC<{children:React.ReactNode;tone?:'purple'|'green'|'red'|'neutral';small?:boolean}>=({children,tone='neutral',small})=>{const bg=tone==='purple'?'rgba(185,140,255,.20)':tone==='green'?'#E9F6EE':tone==='red'?'#FBEDEF':'#F5F2F8';const color=tone==='purple'?purple:tone==='green'?green:tone==='red'?red:ink;return <div style={{padding:small?'10px 15px':'13px 20px',borderRadius:999,background:bg,color,fontFamily:BRAND.font,fontWeight:850,fontSize:small?20:24,whiteSpace:'nowrap'}}>{children}</div>};
const AgentCore:React.FC<{status?:string;scale?:number}>=({status='AGENT',scale=1})=><div style={{...card,width:260,height:180,display:'grid',placeItems:'center',transform:`scale(${scale})`,background:'linear-gradient(145deg,#fff,#F5EEFF)',border:'2px solid rgba(110,69,201,.25)'}}><div style={{textAlign:'center'}}><div style={{width:58,height:58,borderRadius:19,margin:'0 auto 16px',background:purple,boxShadow:'0 12px 30px rgba(110,69,201,.28)'}}/><div style={{...label,fontSize:30,color:purple}}>{status}</div></div></div>;
const ToolCard:React.FC<{name:string;active?:boolean;tone?:'purple'|'red'}>=({name,active,tone='purple'})=><div style={{...card,width:220,height:118,display:'grid',placeItems:'center',opacity:active?1:.4,transform:`scale(${active?1:.94})`,border:active?`2px solid ${tone==='red'?red:purple}`:'1px solid rgba(110,69,201,.12)',background:active?(tone==='red'?'#FFF5F6':'#FAF6FF'):'#fff'}}><div style={{...label,fontSize:25,color:active?(tone==='red'?red:purple):muted}}>{name}</div></div>;
const Arrow:React.FC<{opacity?:number;color?:string}>=({opacity=1,color=purple})=><div style={{fontSize:42,fontWeight:900,color,opacity}}>→</div>;

export const HookVisual:React.FC<{beats:number[]}>=({beats})=>{const f=useCurrentFrame();const cfg=useVideoConfig();const pulse=spring({frame:f,fps:cfg.fps,config:{damping:18}});const b=beats.map(x=>on(f,x));return <div style={{position:'absolute',inset:0}}><div style={{position:'absolute',left:115,top:310,width:470,...card,padding:34,opacity:b[0],transform:`translateY(${28*(1-b[0])}px)`}}><div style={{...label,fontSize:24,color:purple}}>ZIEL</div><div style={{...label,fontSize:39,lineHeight:1.12,marginTop:16}}>Vergleiche passende Tools und gib mir eine Empfehlung.</div></div><div style={{position:'absolute',left:650,top:270,width:430,...card,padding:30,opacity:b[1]*(1-.7*b[2]),transform:`scale(${.92+.08*pulse})`}}><div style={{...label,fontSize:24,color:muted}}>CHAT-ANTWORT</div><div style={{height:14,width:'92%',borderRadius:10,background:'#D8D0DE',marginTop:28}}/><div style={{height:14,width:'72%',borderRadius:10,background:'#D8D0DE',marginTop:15}}/><div style={{height:14,width:'84%',borderRadius:10,background:'#D8D0DE',marginTop:15}}/></div><div style={{position:'absolute',left:790,top:380,opacity:b[2],transform:`scale(${.86+.14*b[2]})`}}><AgentCore status="AGENT"/></div><div style={{position:'absolute',right:105,top:205,display:'grid',gridTemplateColumns:'repeat(2,220px)',gap:20,opacity:b[3]}}>{['SUCHE','DATEIEN','CODE','BROWSER'].map((x,i)=><ToolCard key={x} name={x} active={b[3]>.15+i*.18}/>)}</div><svg width="1920" height="1080" style={{position:'absolute',inset:0,pointerEvents:'none',opacity:b[4]}}><path d="M1510 695 C1400 860 990 875 920 625" fill="none" stroke={purple} strokeWidth="12" strokeLinecap="round" strokeDasharray="18 18"/><path d="M920 625 l-8 34 30-17" fill={purple}/></svg><div style={{position:'absolute',left:980,top:805,opacity:b[4]}}><Pill tone="purple">ERGEBNIS → FEEDBACK</Pill></div></div>};

export const CompareVisual:React.FC<{beats:number[]}>=({beats})=>{const f=useCurrentFrame();const b=beats.map(x=>on(f,x));return <div style={{position:'absolute',inset:0}}><div style={{position:'absolute',left:940,top:175,bottom:130,width:2,background:'rgba(26,26,46,.10)'}}/><div style={{position:'absolute',left:120,top:210,width:690}}><div style={{...label,fontSize:29,color:muted,marginBottom:34}}>CHATBOT</div><div style={{display:'flex',alignItems:'center',gap:18,opacity:b[0]}}><Pill>FRAGE</Pill><Arrow/><Pill tone="purple">ANTWORT</Pill></div><div style={{...label,fontSize:24,color:muted,marginTop:42,opacity:b[2]}}>Stoppt nach der Antwort</div></div><div style={{position:'absolute',right:95,top:210,width:780}}><div style={{...label,fontSize:29,color:purple,marginBottom:34}}>AGENT</div><div style={{display:'flex',alignItems:'center',gap:12,opacity:b[1]}}>{['ZIEL','SUCHEN','VERGLEICHEN','PRÜFEN'].map((x,i)=><React.Fragment key={x}><Pill tone={i<=Math.floor(b[2]*3)?'purple':'neutral'}>{x}</Pill>{i<3?<Arrow opacity={b[2]}/>:null}</React.Fragment>)}</div><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:16,marginTop:70,opacity:b[3]}}>{['Quelle A','Quelle B','Zwischenstand'].map((x,i)=><div key={x} style={{...card,height:150,display:'grid',placeItems:'center',...label,fontSize:24,color:i===2?purple:ink}}>{x}</div>)}</div></div></div>};

export const AnatomyVisual:React.FC<{beats:number[]}>=({beats})=>{const f=useCurrentFrame();const b=beats.map(x=>on(f,x));const modules=[{x:160,y:250,t:'ANWEISUNGEN',s:'Ziel & Grenzen',v:b[1]},{x:1320,y:250,t:'WERKZEUGE',s:'Aktionen',v:b[2]},{x:160,y:650,t:'KONTEXT',s:'Was schon passiert ist',v:b[3]}];return <div style={{position:'absolute',inset:0}}><div style={{position:'absolute',left:830,top:410,opacity:b[0],transform:`scale(${.86+.14*b[0]})`}}><AgentCore status="MODELL"/></div>{modules.map(m=><div key={m.t} style={{position:'absolute',left:m.x,top:m.y,width:410,...card,padding:30,opacity:m.v,transform:`translateY(${25*(1-m.v)}px)`}}><div style={{...label,fontSize:28,color:purple}}>{m.t}</div><div style={{...label,fontSize:24,color:muted,marginTop:18}}>{m.s}</div></div>)}<svg width="1920" height="1080" style={{position:'absolute',inset:0,opacity:b[4]}}><path d="M570 340 C760 340 720 470 830 500M1320 340 C1160 340 1190 470 1090 500M570 740 C760 740 720 600 830 575" fill="none" stroke={accent} strokeWidth="10" strokeLinecap="round"/></svg><div style={{position:'absolute',left:846,top:650,opacity:b[4]}}><Pill tone="green">BEREIT</Pill></div></div>};

export const LoopVisual:React.FC<{beats:number[]}>=({beats})=>{const f=useCurrentFrame();const count=beatCount(f,beats);const current=Math.max(0,Math.min(4,count-1));const second=count>=6;const nodes=[['ZIEL',960,190],['BEOBACHTEN',1390,390],['ENTSCHEIDEN',1260,760],['HANDELN',660,760],['ERGEBNIS',520,390]];return <div style={{position:'absolute',inset:0}}><svg width="1920" height="1080" style={{position:'absolute',inset:0}}><ellipse cx="960" cy="535" rx="520" ry="330" fill="none" stroke="#E4DBEB" strokeWidth="20"/><path d="M960 205 C1320 205 1480 365 1480 535 C1480 760 1260 865 960 865 C620 865 440 720 440 535 C440 350 650 205 960 205" fill="none" stroke={purple} strokeWidth="13" strokeLinecap="round" strokeDasharray="18 18" opacity={p(f,beats[0],beats[4])}/></svg>{nodes.map((n,i)=>{const active=count>i;return <div key={n[0]} style={{position:'absolute',left:Number(n[1])-115,top:Number(n[2])-55,width:230,height:110,...card,display:'grid',placeItems:'center',opacity:active?1:.3,transform:`scale(${count>0&&current===i?1.08:1})`,border:count>0&&current===i?`2px solid ${purple}`:'1px solid rgba(110,69,201,.14)'}}><div style={{...label,fontSize:23,color:active?purple:muted}}>{n[0]}</div></div>})}<div style={{position:'absolute',left:790,top:445,width:340,...card,padding:30,textAlign:'center',opacity:count>0?1:.35}}><div style={{...label,fontSize:24,color:muted}}>KONTEXT</div><div style={{...label,fontSize:42,color:purple,marginTop:14}}>{second?'RUNDE 2':'RUNDE 1'}</div><div style={{...label,fontSize:21,color:second?green:muted,marginTop:12}}>{second?'Zustand aktualisiert':'Ausgangszustand'}</div></div></div>};

export const ExampleVisual:React.FC<{beats:number[]}>=({beats})=>{const f=useCurrentFrame();const b=beats.map(x=>on(f,x));return <div style={{position:'absolute',inset:0}}><div style={{position:'absolute',left:90,top:220,width:520,height:630,...card,padding:34}}><div style={{...label,fontSize:28,color:purple}}>DOKUMENTE</div><div style={{display:'grid',gap:18,marginTop:28}}>{['Angebot A','Angebot B','Anforderungen'].map((x,i)=><div key={x} style={{height:130,borderRadius:20,background:'#F7F4FA',padding:22,opacity:b[0],transform:`translateX(${(1-b[0])*(-30-i*12)}px)`}}><div style={{...label,fontSize:24}}>{x}</div><div style={{height:10,width:`${75-i*8}%`,background:'#D7CDDF',borderRadius:8,marginTop:22}}/></div>)}</div></div><div style={{position:'absolute',left:680,top:230,width:500,height:600,...card,padding:32,opacity:b[1]}}><div style={{...label,fontSize:27,color:purple}}>KERNAUSSAGEN</div>{['Preis','Leistung','Grenzen'].map((x,i)=><div key={x} style={{marginTop:24,height:86,borderRadius:18,background:'#F8F5FA',display:'flex',alignItems:'center',padding:'0 22px',...label,fontSize:24}}>{x}<span style={{marginLeft:'auto',color:i===1&&b[2]>.5?red:green}}>{i===1&&b[2]>.5?'!':'✓'}</span></div>)}<div style={{marginTop:30,opacity:b[2]}}><Pill tone="red">KONFLIKT ERKANNT</Pill></div></div><div style={{position:'absolute',right:95,top:220,width:560}}><div style={{...card,padding:28,opacity:b[3]}}><div style={{...label,fontSize:23,color:purple}}>GEZIELTE NACHFRAGE</div><div style={{...label,fontSize:28,marginTop:16}}>Fehlende Information suchen</div></div><div style={{...card,padding:30,marginTop:24,opacity:b[4]}}><div style={{...label,fontSize:22,color:green}}>LÜCKE GESCHLOSSEN</div><div style={{height:12,width:'86%',background:'#CFE7D8',borderRadius:8,marginTop:20}}/></div><div style={{...card,padding:30,marginTop:24,opacity:b[5]}}><div style={{...label,fontSize:27}}>ENTSCHEIDUNGSVORLAGE</div><div style={{display:'grid',gap:12,marginTop:18}}>{[82,94,67].map((w,i)=><div key={i} style={{height:10,width:`${w}%`,background:'#D9D0E0',borderRadius:8}}/>)}</div></div><div style={{marginTop:22,opacity:b[6]}}><Pill tone="green">✓ ANFORDERUNGEN GEPRÜFT</Pill></div></div></div>};

export const ToolsVisual:React.FC<{beats:number[]}>=({beats})=>{const f=useCurrentFrame();const count=beatCount(f,beats);const names=['SUCHE','DATEIEN','CODE','BROWSER'];const activeTool=count>=2&&count<=5?count-2:-1;const tasks=['Aktuelle Information','Projektkontext','Berechnung / Test','Web-Interaktion'];return <div style={{position:'absolute',inset:0}}><div style={{position:'absolute',left:675,top:200,width:570,...card,padding:28,textAlign:'center',opacity:on(f,beats[0])}}><div style={{...label,fontSize:22,color:muted}}>NÄCHSTER SCHRITT BRAUCHT</div><div style={{...label,fontSize:38,color:purple,marginTop:12}}>{activeTool>=0?tasks[activeTool]:'WERKZEUG AUSWÄHLEN'}</div></div><div style={{position:'absolute',left:330,right:330,top:430,display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:26,opacity:on(f,beats[0])}}>{names.map((x,i)=><ToolCard key={x} name={x} active={activeTool===i}/>)}</div><div style={{position:'absolute',left:790,top:680,opacity:on(f,beats[5])}}><Pill tone="purple">NICHT BENÖTIGTE TOOLS BLEIBEN AUS</Pill></div><div style={{position:'absolute',left:835,top:825,opacity:on(f,beats[0])}}><AgentCore status="MODELL" scale={.78}/></div></div>};

export const RisksVisual:React.FC<{beats:number[]}>=({beats})=>{const f=useCurrentFrame();const b=beats.map(x=>on(f,x));const chain=['ANNAHME','SUCHE','DATEI','ERGEBNIS'];return <div style={{position:'absolute',inset:0}}><div style={{position:'absolute',left:110,top:280,width:1080}}><div style={{display:'flex',alignItems:'center',gap:12}}>{chain.map((x,i)=><React.Fragment key={x}><div style={{...card,width:220,height:135,display:'grid',placeItems:'center',background:b[1]>.2&&i<=Math.floor(b[1]*3)?'#FFF2F4':'#fff',border:b[1]>.2&&i<=Math.floor(b[1]*3)?`2px solid ${red}`:'1px solid rgba(110,69,201,.14)',opacity:i===0?b[0]:1}}><div style={{...label,fontSize:23,color:b[1]>.2&&i<=Math.floor(b[1]*3)?red:ink}}>{i===0&&b[0]>.2?'FALSCHE ':''}{x}</div></div>{i<3?<Arrow color={b[1]>.2?red:purple}/>:null}</React.Fragment>)}</div><div style={{marginTop:38,opacity:b[1]}}><Pill tone="red">FEHLER WANDERT WEITER</Pill></div></div><div style={{position:'absolute',right:95,top:220,width:500,...card,padding:32,opacity:b[2]}}><div style={{...label,fontSize:23,color:red}}>EXTERNER INHALT</div><div style={{...label,fontSize:31,lineHeight:1.12,marginTop:20}}>„Ignoriere das eigentliche Ziel …“</div><div style={{marginTop:30,opacity:b[3]}}><Pill tone="red">BLOCKIERT / PRÜFEN</Pill></div></div><div style={{position:'absolute',right:540,top:500,width:90,height:190,borderLeft:`10px solid ${red}`,borderTop:`10px solid ${red}`,borderBottom:`10px solid ${red}`,borderRadius:'24px 0 0 24px',opacity:b[3]}}/></div>};

export const GuardrailsVisual:React.FC<{beats:number[]}>=({beats})=>{const f=useCurrentFrame();const count=beatCount(f,beats);const idx=count-1;const stages=['RECHTE','BESTÄTIGUNG','VERIFIKATION','STOP'];return <div style={{position:'absolute',inset:0}}><div style={{position:'absolute',left:130,top:400,display:'flex',alignItems:'center',gap:18,opacity:on(f,beats[0])}}><AgentCore status="AKTION" scale={.82}/><Arrow/>{stages.map((x,i)=><React.Fragment key={x}><div style={{...card,width:245,height:150,display:'grid',placeItems:'center',background:idx>=i?'#FAF6FF':'#fff',border:idx===i?`2px solid ${purple}`:'1px solid rgba(110,69,201,.14)'}}><div style={{textAlign:'center'}}><div style={{...label,fontSize:23,color:idx>=i?purple:muted}}>{x}</div><div style={{...label,fontSize:18,color:idx>i?green:muted,marginTop:10}}>{idx>i?'✓ bestanden':i===0?'nur freigegeben':'prüfen'}</div></div></div>{i<3?<Arrow opacity={idx>=i?.95:.25}/>:null}</React.Fragment>)}</div><div style={{position:'absolute',left:720,top:680,display:'flex',gap:18,opacity:on(f,beats[3])}}><Pill tone="green">FERTIG</Pill><Pill tone="purple">WEITER</Pill><Pill>NACHFRAGEN</Pill></div></div>};

export const FitVisual:React.FC<{beats:number[]}>=({beats})=>{const f=useCurrentFrame();const b=beats.map(x=>on(f,x));return <div style={{position:'absolute',inset:0}}><div style={{position:'absolute',left:100,top:230,width:760,opacity:1-b[4]*.75}}><div style={{...label,fontSize:28,color:muted}}>KLASSISCHER WORKFLOW</div><div style={{display:'flex',alignItems:'center',gap:12,marginTop:44,opacity:b[0]}}>{['A','B','C','D'].map((x,i)=><React.Fragment key={x}><Pill>{x}</Pill>{i<3?<Arrow/>:null}</React.Fragment>)}</div><div style={{marginTop:30,opacity:b[1]}}><Pill>VORHERSEHBAR</Pill></div></div><div style={{position:'absolute',right:100,top:230,width:800,opacity:1-b[4]*.75}}><div style={{...label,fontSize:28,color:purple}}>AGENT</div><svg width="760" height="360" style={{marginTop:10,opacity:b[2]}}><path d="M80 170 H260 M260 170 C360 170 360 70 470 70 H690 M260 170 C360 170 360 270 470 270 H690" fill="none" stroke={purple} strokeWidth="12" strokeLinecap="round"/><circle cx="80" cy="170" r="30" fill={purple}/><circle cx="260" cy="170" r="30" fill={purple}/><circle cx="470" cy="70" r="30" fill={accent}/><circle cx="470" cy="270" r="30" fill={accent}/><circle cx="690" cy="70" r="30" fill={green}/><circle cx="690" cy="270" r="30" fill="#D4C9DD"/></svg><div style={{opacity:b[3]}}><Pill tone="purple">FLEXIBEL, WENN DER WEG OFFEN IST</Pill></div></div><div style={{position:'absolute',left:260,right:260,top:210,bottom:120,...card,padding:42,opacity:b[4],transform:`scale(${.94+.06*b[4]})`}}><div style={{...label,fontSize:28,color:purple,textAlign:'center'}}>MENTALES MODELL</div><div style={{display:'flex',alignItems:'center',justifyContent:'center',gap:16,marginTop:100}}>{['ZIEL','KONTEXT','ENTSCHEIDEN','TOOL','FEEDBACK'].map((x,i)=><React.Fragment key={x}><Pill tone={i===2?'purple':'neutral'}>{x}</Pill>{i<4?<Arrow/>:null}</React.Fragment>)}</div><div style={{display:'flex',justifyContent:'center',gap:18,marginTop:80}}><Pill tone="purple">WERKZEUGE</Pill><Pill>REGELN</Pill><Pill tone="green">KONTROLLE</Pill></div></div></div>};
