import React from 'react';
import {interpolate,spring,useCurrentFrame,useVideoConfig} from 'remotion';
import {BRAND} from '../../../brand/brand';
import {Keyword,Pop,Rise} from './Motion';

const ink=BRAND.ink,purple=BRAND.accentDk,accent=BRAND.accent,green='#31875A',red='#B64D58',muted='#8D8197';
const card:React.CSSProperties={background:'#fff',border:'1px solid rgba(110,69,201,.16)',borderRadius:28,boxShadow:'0 24px 70px rgba(26,26,46,.10)'};
const label:React.CSSProperties={fontFamily:BRAND.font.body,fontWeight:850,letterSpacing:-.7,color:ink};
const p=(f:number,a:number,b:number)=>interpolate(f,[a,b],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});
const on=(f:number,at:number)=>p(f,at,at+55);
// Verteilt die Sprechpausen eines Kapitels auf die Zustaende einer Szene.
// Jedes Element bekommt damit seinen eigenen Sprechmoment, statt dass eine
// ganze Gruppe auf einen Schlag erscheint.
const step=(beats:number[],index:number,total:number):number=>{
  if(beats.length===0)return 0;
  const i=Math.round(index*(beats.length-1)/Math.max(1,total-1));
  return beats[Math.min(beats.length-1,Math.max(0,i))];
};
// Wie rise, aber direkt an einen verteilten Zustand gekoppelt.
const riseAt=(f:number,beats:number[],index:number,total:number,dy=30)=>rise(f,step(beats,index,total),dy);
const onAt=(f:number,beats:number[],index:number,total:number)=>on(f,step(beats,index,total));
const rise=(f:number,at:number,dy=30)=>{const t=on(f,at);return{opacity:t,transform:`translateY(${(1-t)*dy}px)`}};
const beatCount=(f:number,beats:number[])=>beats.filter(b=>f>=b).length;

const Pill:React.FC<{children:React.ReactNode;tone?:'purple'|'green'|'red'|'neutral';small?:boolean}>=({children,tone='neutral',small})=>{const bg=tone==='purple'?'rgba(185,140,255,.20)':tone==='green'?'#E9F6EE':tone==='red'?'#FBEDEF':'#F5F2F8';const color=tone==='purple'?purple:tone==='green'?green:tone==='red'?red:ink;return <div style={{padding:small?'10px 15px':'13px 20px',borderRadius:999,background:bg,color,fontFamily:BRAND.font.body,fontWeight:850,fontSize:small?20:24,whiteSpace:'nowrap'}}>{children}</div>};
const AgentCore:React.FC<{status?:string;scale?:number}>=({status='AGENT',scale=1})=><div style={{...card,width:260,height:180,display:'grid',placeItems:'center',transform:`scale(${scale})`,background:'linear-gradient(145deg,#fff,#F5EEFF)',border:'2px solid rgba(110,69,201,.25)'}}><div style={{textAlign:'center'}}><div style={{width:58,height:58,borderRadius:19,margin:'0 auto 16px',background:purple,boxShadow:'0 12px 30px rgba(110,69,201,.28)'}}/><div style={{...label,fontSize:30,color:purple}}>{status}</div></div></div>;
const ToolCard:React.FC<{name:string;active?:boolean;tone?:'purple'|'red'}>=({name,active,tone='purple'})=><div style={{...card,width:220,height:118,display:'grid',placeItems:'center',opacity:1,transform:`scale(${active?1:.94})`,border:active?`2px solid ${tone==='red'?red:purple}`:'2px solid rgba(110,69,201,.28)',background:active?(tone==='red'?'#FFF5F6':'#FAF6FF'):'#EFEAF6'}}><div style={{...label,fontSize:25,color:active?(tone==='red'?red:purple):'#6F6480'}}>{name}</div></div>;
const Arrow:React.FC<{opacity?:number;color?:string}>=({opacity=1,color=purple})=><div style={{fontSize:42,fontWeight:900,color,opacity}}>→</div>;

export const HookVisual:React.FC<{beats:number[]}>=({beats})=>{const f=useCurrentFrame();const cfg=useVideoConfig();const pulse=spring({frame:f,fps:cfg.fps,config:{damping:18}});const N=5;const bAt=(i:number)=>step(beats,i,N);const b=Array.from({length:N},(_,i)=>on(f,bAt(i)));return <div style={{position:'absolute',inset:0}}><div style={{position:'absolute',left:115,top:310,width:470,...card,padding:34,opacity:b[0],transform:`translateY(${28*(1-b[0])}px)`}}><div style={{...label,fontSize:24,color:purple}}>ZIEL</div><div style={{...label,fontSize:39,lineHeight:1.12,marginTop:16}}>Vergleiche passende Tools und gib mir eine Empfehlung.</div></div><div style={{position:'absolute',left:650,top:270,width:430,...card,padding:30,opacity:b[1]*Math.max(0,1-b[2]*1.3),transform:`scale(${.92+.08*pulse})`}}><div style={{...label,fontSize:24,color:muted}}>CHAT-ANTWORT</div><div style={{height:14,width:'92%',borderRadius:10,background:'#D8D0DE',marginTop:28}}/><div style={{height:14,width:'72%',borderRadius:10,background:'#D8D0DE',marginTop:15}}/><div style={{height:14,width:'84%',borderRadius:10,background:'#D8D0DE',marginTop:15}}/></div><div style={{position:'absolute',left:790,top:380,opacity:b[2],transform:`scale(${.86+.14*b[2]})`}}><AgentCore status="AGENT"/></div><div style={{position:'absolute',right:105,top:205,display:'grid',gridTemplateColumns:'repeat(2,220px)',gap:20,...rise(f,bAt(3))}}>{['SUCHE','DATEIEN','CODE','BROWSER'].map((x,i)=><ToolCard key={x} name={x} active={b[3]>.15+i*.18}/>)}</div><svg width="1920" height="1080" style={{position:'absolute',inset:0,pointerEvents:'none',...rise(f,bAt(4))}}><path d="M1500 660 C1420 792 1010 800 936 640" fill="none" stroke={purple} strokeWidth="12" strokeLinecap="round" strokeDasharray="18 18"/><path d="M920 625 l-8 34 30-17" fill={purple}/></svg><div style={{position:'absolute',left:1010,top:838,...rise(f,bAt(4))}}><Pill tone="purple">ERGEBNIS → FEEDBACK</Pill></div><div style={{position:'absolute',left:115,top:700,width:640,...rise(f,bAt(3))}}><div style={{...card,padding:'32px 36px'}}><div style={{...label,fontSize:22,color:purple,letterSpacing:1.6}}>DER UNTERSCHIED</div><div style={{...label,fontSize:30,color:muted,marginTop:14,lineHeight:1.26}}>Ein Chatbot antwortet. Ein Agent <span style={{color:purple}}>arbeitet weiter</span>, bis das Ziel erreicht ist.</div></div></div></div>};

export const CompareVisual:React.FC<{beats:number[]}>=({beats})=>{const f=useCurrentFrame();
  // 13 einzeln gesprochene Zustaende; jeder sitzt auf einer echten Sprechpause.
  const N=13; const at=(i:number)=>step(beats,i,N);
  const chain=['ZIEL','SUCHEN','VERGLEICHEN','PRÜFEN'];
  const stopPulse=1+Math.sin(Math.max(0,f-at(4)-40)/9)*0.02;
  return <div style={{position:'absolute',inset:0}}>
    <div style={{position:'absolute',left:940,top:120,bottom:120,width:2,background:'linear-gradient(rgba(26,26,46,0),rgba(26,26,46,.12),rgba(26,26,46,0))'}}/>

    <div style={{position:'absolute',left:120,top:104,width:700}}>
      <Rise at={at(0)} from="left"><div style={{...label,fontSize:30,color:muted,letterSpacing:2}}>CHATBOT</div></Rise>
      <div style={{display:'flex',alignItems:'center',gap:18,marginTop:74}}>
        <Rise at={at(1)} from="left"><Pill>FRAGE</Pill></Rise>
        <Rise at={at(2)} from="left"><Arrow/></Rise>
        <Pop at={at(3)}><Pill tone="purple">ANTWORT</Pill></Pop>
      </div>
      <Rise at={at(4)} style={{marginTop:104}}>
        <div style={{...card,padding:'34px 38px',borderStyle:'dashed',borderColor:'rgba(26,26,46,.18)',transform:`scale(${stopPulse})`}}>
          <div style={{...label,fontSize:27,color:muted}}>Danach passiert <Keyword at={at(4)+22} size={27} tone="warn">nichts</Keyword> mehr.</div>
        </div>
      </Rise>
      <Rise at={at(5)} style={{marginTop:76}}>
        <div style={{...label,fontSize:25,color:muted}}>Ein Schritt. Ein Ergebnis.</div>
      </Rise>
    </div>

    <div style={{position:'absolute',right:95,top:104,width:790}}>
      <Rise at={at(6)} from="right"><div style={{...label,fontSize:30,color:purple,letterSpacing:2}}>AGENT</div></Rise>
      <div style={{display:'flex',alignItems:'center',gap:11,marginTop:74,flexWrap:'wrap'}}>
        {chain.map((x,i)=><React.Fragment key={x}>
          <Pop at={at(7+i)}><Pill tone={f>=at(7+i)+18?'purple':'neutral'} small>{x}</Pill></Pop>
          {i<chain.length-1?<Rise at={at(7+i)+16} from="left" distance={12}><Arrow/></Rise>:null}
        </React.Fragment>)}
      </div>
      <div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:16,marginTop:104}}>
        {['Quelle A','Quelle B','Zwischenstand'].map((x,i)=><Rise key={x} at={at(11)+i*20}>
          <div style={{...card,height:188,display:'grid',placeItems:'center',...label,fontSize:23,color:i===2?purple:ink,borderColor:i===2?'rgba(110,69,201,.35)':'rgba(110,69,201,.16)'}}>{x}</div>
        </Rise>)}
      </div>
      <Rise at={at(12)} style={{marginTop:76}}>
        <div style={{...label,fontSize:25,color:muted}}>Mehrere Schritte. Ein <Keyword at={at(12)+24} size={25}>geprüftes</Keyword> Ergebnis.</div>
      </Rise>
    </div>
  </div>};

export const AnatomyVisual:React.FC<{beats:number[]}>=({beats})=>{const f=useCurrentFrame();const N=5;const bAt=(i:number)=>step(beats,i,N);const b=Array.from({length:N},(_,i)=>on(f,bAt(i)));const modules=[{x:160,y:250,t:'ANWEISUNGEN',s:'Ziel & Grenzen',v:b[1]},{x:1320,y:250,t:'WERKZEUGE',s:'Aktionen',v:b[2]},{x:160,y:650,t:'KONTEXT',s:'Was schon passiert ist',v:b[3]}];return <div style={{position:'absolute',inset:0}}><div style={{position:'absolute',left:830,top:410,opacity:b[0],transform:`scale(${.86+.14*b[0]})`}}><AgentCore status="MODELL"/></div>{modules.map(m=><div key={m.t} style={{position:'absolute',left:m.x,top:m.y,width:410,...card,padding:30,opacity:m.v,transform:`translateY(${25*(1-m.v)}px)`}}><div style={{...label,fontSize:28,color:purple}}>{m.t}</div><div style={{...label,fontSize:24,color:muted,marginTop:18}}>{m.s}</div></div>)}<svg width="1920" height="1080" style={{position:'absolute',inset:0,...rise(f,bAt(4))}}><path d="M570 340 C760 340 720 470 830 500M1320 340 C1160 340 1190 470 1090 500M570 740 C760 740 720 600 830 575" fill="none" stroke={accent} strokeWidth="10" strokeLinecap="round"/></svg><div style={{position:'absolute',left:846,top:650,...rise(f,bAt(4))}}><Pill tone="green">BEREIT</Pill></div></div>};

export const LoopVisual:React.FC<{beats:number[]}>=({beats})=>{const f=useCurrentFrame();const hits=beats.filter(x=>f>=x).length;const current=hits===0?0:(hits-1)%5;const round=Math.max(1,Math.ceil(hits/5));const second=round>=2;const nodes=[['ZIEL',960,190],['BEOBACHTEN',1390,390],['ENTSCHEIDEN',1260,760],['HANDELN',660,760],['ERGEBNIS',520,390]];return <div style={{position:'absolute',inset:0}}><svg width="1920" height="1080" style={{position:'absolute',inset:0}}><ellipse cx="960" cy="535" rx="520" ry="330" fill="none" stroke="#E4DBEB" strokeWidth="20"/><path d="M960 205 C1320 205 1480 365 1480 535 C1480 760 1260 865 960 865 C620 865 440 720 440 535 C440 350 650 205 960 205" fill="none" stroke={purple} strokeWidth="13" strokeLinecap="round" strokeDasharray="18 18" opacity={p(f,beats[0],beats[4])}/></svg>{nodes.map((n,i)=>{const active=hits>0&&((round>1)||i<=current);return <div key={n[0]} style={{position:'absolute',left:Number(n[1])-115,top:Number(n[2])-55,width:230,height:110,...card,display:'grid',placeItems:'center',opacity:active?1:.3,transform:`scale(${hits>0&&current===i?1.08:1})`,border:hits>0&&current===i?`2px solid ${purple}`:'1px solid rgba(110,69,201,.14)'}}><div style={{...label,fontSize:23,color:active?purple:muted}}>{n[0]}</div></div>})}<div style={{position:'absolute',left:790,top:445,width:340,...card,padding:30,textAlign:'center',opacity:hits>0?1:.35}}><div style={{...label,fontSize:24,color:muted}}>KONTEXT</div><div style={{...label,fontSize:42,color:purple,marginTop:14}}>{second?'RUNDE 2':'RUNDE 1'}</div><div style={{...label,fontSize:21,color:second?green:muted,marginTop:12}}>{second?'Zustand aktualisiert':'Ausgangszustand'}</div></div></div>};

export const ExampleVisual:React.FC<{beats:number[]}>=({beats})=>{const f=useCurrentFrame();const N=7;const bAt=(i:number)=>step(beats,i,N);const b=Array.from({length:N},(_,i)=>on(f,bAt(i)));return <div style={{position:'absolute',inset:0}}><div style={{position:'absolute',left:90,top:220,width:520,height:630,...card,padding:34}}><div style={{...label,fontSize:28,color:purple}}>DOKUMENTE</div><div style={{display:'grid',gap:18,marginTop:28}}>{['Angebot A','Angebot B','Anforderungen'].map((x,i)=><div key={x} style={{height:130,borderRadius:20,background:'#F7F4FA',padding:22,opacity:b[0],transform:`translateX(${(1-b[0])*(-30-i*12)}px)`}}><div style={{...label,fontSize:24}}>{x}</div><div style={{height:10,width:`${75-i*8}%`,background:'#D7CDDF',borderRadius:8,marginTop:22}}/></div>)}</div></div><div style={{position:'absolute',left:680,top:230,width:500,height:600,...card,padding:32,...rise(f,bAt(1))}}><div style={{...label,fontSize:27,color:purple}}>KERNAUSSAGEN</div>{['Preis','Leistung','Grenzen'].map((x,i)=><div key={x} style={{marginTop:24,height:86,borderRadius:18,background:'#F8F5FA',display:'flex',alignItems:'center',padding:'0 22px',...label,fontSize:24}}>{x}<span style={{marginLeft:'auto',color:i===1&&b[2]>.5?red:green}}>{i===1&&b[2]>.5?'!':'✓'}</span></div>)}<div style={{marginTop:30,...rise(f,bAt(2))}}><Pill tone="red">KONFLIKT ERKANNT</Pill></div></div><div style={{position:'absolute',right:95,top:220,width:560}}><div style={{...card,padding:28,...rise(f,bAt(3))}}><div style={{...label,fontSize:23,color:purple}}>GEZIELTE NACHFRAGE</div><div style={{...label,fontSize:28,marginTop:16}}>Fehlende Information suchen</div></div><div style={{...card,padding:30,marginTop:24,...rise(f,bAt(4))}}><div style={{...label,fontSize:22,color:green}}>LÜCKE GESCHLOSSEN</div><div style={{height:12,width:'86%',background:'#CFE7D8',borderRadius:8,marginTop:20}}/></div><div style={{...card,padding:30,marginTop:24,...rise(f,bAt(5))}}><div style={{...label,fontSize:27}}>ENTSCHEIDUNGSVORLAGE</div><div style={{display:'grid',gap:12,marginTop:18}}>{[82,94,67].map((w,i)=><div key={i} style={{height:10,width:`${w}%`,background:'#D9D0E0',borderRadius:8}}/>)}</div></div><div style={{marginTop:22,...rise(f,bAt(6))}}><Pill tone="green">✓ ANFORDERUNGEN GEPRÜFT</Pill></div></div></div>};

export const ToolsVisual:React.FC<{beats:number[]}>=({beats})=>{const f=useCurrentFrame();const hits=beats.filter(x=>f>=x).length;const names=['SUCHE','DATEIEN','CODE','BROWSER'];const activeTool=hits<2?-1:(hits-2)%5===4?-1:(hits-2)%5;const tasks=['Aktuelle Information','Projektkontext','Berechnung / Test','Web-Interaktion'];return <div style={{position:'absolute',inset:0}}><div style={{position:'absolute',left:675,top:200,width:570,...card,padding:28,textAlign:'center',opacity:on(f,beats[0])}}><div style={{...label,fontSize:22,color:muted}}>NÄCHSTER SCHRITT BRAUCHT</div><div style={{...label,fontSize:38,color:purple,marginTop:12}}>{activeTool>=0?tasks[activeTool]:'WERKZEUG AUSWÄHLEN'}</div></div><div style={{position:'absolute',left:330,right:330,top:430,display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:26,opacity:on(f,beats[0])}}>{names.map((x,i)=><ToolCard key={x} name={x} active={activeTool===i}/>)}</div><div style={{position:'absolute',left:700,top:628,opacity:on(f,beats[5])}}><Pill tone="purple">NICHT BENÖTIGTE TOOLS BLEIBEN AUS</Pill></div><div style={{position:'absolute',left:835,top:742,opacity:on(f,beats[0])}}><AgentCore status="MODELL" scale={.78}/></div></div>};

export const RisksVisual:React.FC<{beats:number[]}>=({beats})=>{const f=useCurrentFrame();const N=4;const bAt=(i:number)=>step(beats,i,N);const b=Array.from({length:N},(_,i)=>on(f,bAt(i)));const chain=['ANNAHME','SUCHE','DATEI','ERGEBNIS'];return <div style={{position:'absolute',inset:0}}><div style={{position:'absolute',left:110,top:280,width:1080}}><div style={{display:'flex',alignItems:'center',gap:12}}>{chain.map((x,i)=><React.Fragment key={x}><div style={{...card,width:220,height:135,display:'grid',placeItems:'center',background:b[1]>.2&&i<=Math.floor(b[1]*3)?'#FFF2F4':'#fff',border:b[1]>.2&&i<=Math.floor(b[1]*3)?`2px solid ${red}`:'1px solid rgba(110,69,201,.14)',opacity:i===0?b[0]:1}}><div style={{...label,fontSize:23,color:b[1]>.2&&i<=Math.floor(b[1]*3)?red:ink}}>{i===0&&b[0]>.2?'FALSCHE ':''}{x}</div></div>{i<3?<Arrow color={b[1]>.2?red:purple}/>:null}</React.Fragment>)}</div><div style={{marginTop:38,...rise(f,bAt(1))}}><Pill tone="red">FEHLER WANDERT WEITER</Pill></div></div><div style={{position:'absolute',right:95,top:220,width:500,...card,padding:32,...rise(f,bAt(2))}}><div style={{...label,fontSize:23,color:red}}>EXTERNER INHALT</div><div style={{...label,fontSize:31,lineHeight:1.12,marginTop:20}}>„Ignoriere das eigentliche Ziel …“</div><div style={{marginTop:30,...rise(f,bAt(3))}}><Pill tone="red">BLOCKIERT / PRÜFEN</Pill></div></div><div style={{position:'absolute',left:110,right:95,top:640,display:'flex',justifyContent:'space-between',gap:40}}><div style={{flex:1,...card,padding:'30px 34px',...rise(f,bAt(1))}}><div style={{...label,fontSize:22,color:red,letterSpacing:1.5}}>FOLGEFEHLER</div><div style={{...label,fontSize:27,color:muted,marginTop:14,lineHeight:1.25}}>Ein falscher Schritt am Anfang steckt in jedem Ergebnis danach.</div></div><div style={{flex:1,...card,padding:'30px 34px',...rise(f,bAt(3))}}><div style={{...label,fontSize:22,color:red,letterSpacing:1.5}}>FREMDE ANWEISUNG</div><div style={{...label,fontSize:27,color:muted,marginTop:14,lineHeight:1.25}}>Text aus einer Quelle ist Inhalt, niemals ein Befehl.</div></div></div></div>};

export const GuardrailsVisual:React.FC<{beats:number[]}>=({beats})=>{const f=useCurrentFrame();const hits=beats.filter(x=>f>=x).length;const idx=Math.min(3,Math.max(-1,Math.floor((hits-1)*4/Math.max(1,beats.length-1))));const stages=['RECHTE','BESTÄTIGUNG','VERIFIKATION','STOP'];return <div style={{position:'absolute',inset:0}}><div style={{position:'absolute',left:130,top:400,display:'flex',alignItems:'center',gap:18,opacity:on(f,beats[0])}}><AgentCore status="AKTION" scale={.82}/><Arrow/>{stages.map((x,i)=><React.Fragment key={x}><div style={{...card,width:245,height:150,display:'grid',placeItems:'center',background:idx>=i?'#FAF6FF':'#fff',border:idx===i?`2px solid ${purple}`:'1px solid rgba(110,69,201,.14)'}}><div style={{textAlign:'center'}}><div style={{...label,fontSize:23,color:idx>=i?purple:muted}}>{x}</div><div style={{...label,fontSize:18,color:idx>i?green:muted,marginTop:10}}>{idx>i?'✓ bestanden':i===0?'nur freigegeben':'prüfen'}</div></div></div>{i<3?<Arrow opacity={idx>=i?.95:.25}/>:null}</React.Fragment>)}</div><div style={{position:'absolute',left:720,top:680,display:'flex',gap:18,opacity:on(f,beats[3])}}><Pill tone="green">FERTIG</Pill><Pill tone="purple">WEITER</Pill><Pill>NACHFRAGEN</Pill></div></div>};

export const FitVisual:React.FC<{beats:number[]}>=({beats})=>{const f=useCurrentFrame();const N=5;const bAt=(i:number)=>step(beats,i,N);const b=Array.from({length:N},(_,i)=>on(f,bAt(i)));return <div style={{position:'absolute',inset:0}}><div style={{position:'absolute',left:100,top:230,width:760,opacity:Math.max(0,1-b[4]*1.25)}}><div style={{...label,fontSize:28,color:muted}}>KLASSISCHER WORKFLOW</div><div style={{display:'flex',alignItems:'center',gap:12,marginTop:44,...rise(f,bAt(0))}}>{['A','B','C','D'].map((x,i)=><React.Fragment key={x}><Pill>{x}</Pill>{i<3?<Arrow/>:null}</React.Fragment>)}</div><div style={{marginTop:30,...rise(f,bAt(1))}}><Pill>VORHERSEHBAR</Pill></div></div><div style={{position:'absolute',right:100,top:230,width:800,opacity:Math.max(0,1-b[4]*1.25)}}><div style={{...label,fontSize:28,color:purple}}>AGENT</div><svg width="760" height="360" style={{marginTop:10,...rise(f,bAt(2))}}><path d="M80 170 H260 M260 170 C360 170 360 70 470 70 H690 M260 170 C360 170 360 270 470 270 H690" fill="none" stroke={purple} strokeWidth="12" strokeLinecap="round"/><circle cx="80" cy="170" r="30" fill={purple}/><circle cx="260" cy="170" r="30" fill={purple}/><circle cx="470" cy="70" r="30" fill={accent}/><circle cx="470" cy="270" r="30" fill={accent}/><circle cx="690" cy="70" r="30" fill={green}/><circle cx="690" cy="270" r="30" fill="#D4C9DD"/></svg><div style={{...rise(f,bAt(3))}}><Pill tone="purple">FLEXIBEL, WENN DER WEG OFFEN IST</Pill></div></div><div style={{position:'absolute',left:300,right:300,top:250,...card,padding:'46px 42px',opacity:b[4],transform:`scale(${.94+.06*b[4]})`}}><div style={{...label,fontSize:28,color:purple,textAlign:'center'}}>MENTALES MODELL</div><div style={{display:'flex',alignItems:'center',justifyContent:'center',gap:16,marginTop:58}}>{['ZIEL','KONTEXT','ENTSCHEIDEN','TOOL','FEEDBACK'].map((x,i)=><React.Fragment key={x}><Pill tone={i===2?'purple':'neutral'}>{x}</Pill>{i<4?<Arrow/>:null}</React.Fragment>)}</div><div style={{display:'flex',justifyContent:'center',gap:18,marginTop:46}}><Pill tone="purple">WERKZEUGE</Pill><Pill>REGELN</Pill><Pill tone="green">KONTROLLE</Pill></div></div></div>};
