import type {AnimationLibraryEntry} from './schema';
import {animationLibraryDocumentSchema} from './schema';

type Direction = AnimationLibraryEntry['primaryDirection'];
type Energy = AnimationLibraryEntry['energy'];
type Density = AnimationLibraryEntry['density'];
type Complexity = AnimationLibraryEntry['complexity'];

type VariantSeed = {
  slug: string;
  title: string;
  description: string;
  layout: string;
  motion: string;
  novelty: string;
  patterns: string[];
  primitives: string[];
  transitionIn: string[];
  transitionOut: string[];
  camera: string;
  direction: Direction;
  energy: Energy;
  density: Density;
  complexity: Complexity;
  status?: AnimationLibraryEntry['status'];
  avoidWhen?: string[];
  clarity?: number;
  noveltyScore?: number;
  confidence?: number;
};

type FamilySeed = {
  family: string;
  tags: string[];
  variants: VariantSeed[];
};

const FAMILY_SEEDS: FamilySeed[] = [
  {
    family: 'tokenization',
    tags: ['token', 'text', 'word', 'language', 'segment', 'prompt'],
    variants: [
      {
        slug: 'magnetic-phrase-slicer',
        title: 'Magnetic Phrase Slicer',
        description: 'A complete sentence locks into place, then invisible semantic blades separate phrases into magnetically aligned token groups.',
        layout: 'wide-sentence-to-lanes',
        motion: 'sentence-lock-slice-lanes-magnetic-settle',
        novelty: 'semantic-slicing',
        patterns: ['whole-to-parts', 'language-segmentation'],
        primitives: ['kinetic-type', 'slice-lines', 'magnetic-snap'],
        transitionIn: ['text-stream', 'document-edge'],
        transitionOut: ['token-lanes', 'falling-blocks'],
        camera: 'locked-front-with-short-depth-push',
        direction: 'center-out',
        energy: 'dynamic',
        density: 'balanced',
        complexity: 'medium',
        status: 'prototype',
      },
      {
        slug: 'syllable-conveyor',
        title: 'Syllable Conveyor',
        description: 'Text travels across a compact conveyor while separators detect reusable language pieces and sort them into transparent bins.',
        layout: 'horizontal-conveyor-bins',
        motion: 'text-conveyor-detect-cut-sort',
        novelty: 'industrial-language-machine',
        patterns: ['process-explanation', 'sorting'],
        primitives: ['conveyor', 'scanner', 'sorting-bins'],
        transitionIn: ['belt-entry', 'left-stream'],
        transitionOut: ['sorted-bins', 'machine-output'],
        camera: 'slight-isometric-machine-view',
        direction: 'left-to-right',
        energy: 'measured',
        density: 'balanced',
        complexity: 'medium',
      },
      {
        slug: 'character-mosaic-collapse',
        title: 'Character Mosaic Collapse',
        description: 'Individual letters form a readable mosaic before collapsing into compact token tiles with visible grouping logic.',
        layout: 'letter-wall-to-token-grid',
        motion: 'letters-build-read-collapse-group',
        novelty: 'typographic-mosaic',
        patterns: ['many-to-few', 'compression'],
        primitives: ['letter-grid', 'tile-morph', 'group-outline'],
        transitionIn: ['pixel-field', 'letter-rain'],
        transitionOut: ['tile-grid', 'matrix-cells'],
        camera: 'front-grid-with-micro-zoom',
        direction: 'outside-in',
        energy: 'dynamic',
        density: 'dense',
        complexity: 'high',
      },
      {
        slug: 'contextual-token-river',
        title: 'Contextual Token River',
        description: 'Words float as a river and merge or split depending on neighboring context, showing that token boundaries are not always intuitive.',
        layout: 'curved-river-channel',
        motion: 'words-flow-neighbors-pull-split-merge',
        novelty: 'fluid-tokenization',
        patterns: ['context-dependence', 'adaptive-grouping'],
        primitives: ['flow-path', 'word-capsules', 'merge-split'],
        transitionIn: ['ribbon-flow', 'curved-path'],
        transitionOut: ['particle-current', 'token-stream'],
        camera: 'top-down-river-follow',
        direction: 'mixed',
        energy: 'calm',
        density: 'balanced',
        complexity: 'high',
      },
    ],
  },
  {
    family: 'data-transformation',
    tags: ['data', 'vector', 'number', 'convert', 'encode', 'representation'],
    variants: [
      {
        slug: 'vector-prism-converter',
        title: 'Vector Prism Converter',
        description: 'Labeled inputs pass through a transparent prism and emerge as separated numeric dimensions with consistent color coding.',
        layout: 'input-prism-output-spectrum',
        motion: 'labels-enter-prism-refract-dimensions',
        novelty: 'data-refraction',
        patterns: ['input-to-representation', 'transformation'],
        primitives: ['prism', 'numeric-rays', 'label-capsules'],
        transitionIn: ['single-input', 'light-beam'],
        transitionOut: ['vector-rays', 'spectrum-lines'],
        camera: 'three-quarter-prism-view',
        direction: 'left-to-right',
        energy: 'measured',
        density: 'balanced',
        complexity: 'medium',
        status: 'prototype',
      },
      {
        slug: 'matrix-waterfall-encoder',
        title: 'Matrix Waterfall Encoder',
        description: 'Readable information falls through stacked encoding membranes and becomes a compact matrix without using generic code rain.',
        layout: 'vertical-membrane-stack',
        motion: 'content-falls-membranes-quantize-matrix',
        novelty: 'encoding-waterfall',
        patterns: ['layered-conversion', 'abstraction'],
        primitives: ['membranes', 'matrix-grid', 'falling-content'],
        transitionIn: ['top-drop', 'document-fall'],
        transitionOut: ['matrix-floor', 'grid-zoom'],
        camera: 'vertical-cutaway',
        direction: 'top-to-bottom',
        energy: 'dynamic',
        density: 'dense',
        complexity: 'high',
      },
      {
        slug: 'binary-weave-loom',
        title: 'Binary Weave Loom',
        description: 'Multiple data strands cross through a digital loom and form one stable encoded fabric with visible source contributions.',
        layout: 'loom-with-crossing-strands',
        motion: 'strands-enter-weave-tighten-fabric',
        novelty: 'data-textile',
        patterns: ['many-to-one', 'encoding'],
        primitives: ['ribbons', 'loom-bars', 'woven-grid'],
        transitionIn: ['parallel-lines', 'multi-source'],
        transitionOut: ['fabric-fold', 'grid-sheet'],
        camera: 'angled-loom-closeup',
        direction: 'mixed',
        energy: 'measured',
        density: 'dense',
        complexity: 'high',
      },
      {
        slug: 'representation-morph-cascade',
        title: 'Representation Morph Cascade',
        description: 'The same concept successively morphs from word to icon to coordinates to vector, making abstraction levels explicit.',
        layout: 'diagonal-representation-cascade',
        motion: 'word-icon-coordinate-vector-morph',
        novelty: 'multi-form-morph',
        patterns: ['stepwise-abstraction', 'same-thing-different-form'],
        primitives: ['shape-morph', 'coordinate-grid', 'vector-card'],
        transitionIn: ['word-focus', 'object-focus'],
        transitionOut: ['vector-launch', 'coordinate-tunnel'],
        camera: 'diagonal-follow-pan',
        direction: 'bottom-to-top',
        energy: 'dynamic',
        density: 'minimal',
        complexity: 'high',
      },
    ],
  },
  {
    family: 'semantic-space',
    tags: ['meaning', 'embedding', 'similarity', 'cluster', 'concept', 'semantic'],
    variants: [
      {
        slug: 'meaning-terrain',
        title: 'Meaning Terrain',
        description: 'Concepts occupy peaks and valleys on a topographic meaning map where distance and elevation communicate similarity and specificity.',
        layout: 'topographic-landscape',
        motion: 'terrain-rises-labels-settle-camera-glide',
        novelty: 'semantic-topography',
        patterns: ['distance-means-similarity', 'concept-landscape'],
        primitives: ['contour-lines', 'label-pins', 'terrain-shading'],
        transitionIn: ['flat-grid', 'map-unfold'],
        transitionOut: ['contour-collapse', 'path-trace'],
        camera: 'low-angle-landscape-glide',
        direction: 'depth-forward',
        energy: 'calm',
        density: 'balanced',
        complexity: 'high',
        status: 'prototype',
      },
      {
        slug: 'magnetic-concept-constellation',
        title: 'Magnetic Concept Constellation',
        description: 'Concept stars pull toward related ideas and repel unrelated ones until stable constellations form with readable relationship lines.',
        layout: 'full-field-constellation',
        motion: 'stars-enter-attract-repel-lock-orbits',
        novelty: 'semantic-astronomy',
        patterns: ['clustering', 'similarity'],
        primitives: ['star-nodes', 'gravity-lines', 'orbit-rings'],
        transitionIn: ['particle-field', 'dark-to-light-points'],
        transitionOut: ['constellation-thread', 'orbit-zoom'],
        camera: 'slow-orbital-parallax',
        direction: 'circular',
        energy: 'calm',
        density: 'balanced',
        complexity: 'high',
      },
      {
        slug: 'semantic-lens-focus',
        title: 'Semantic Lens Focus',
        description: 'A movable lens reveals hidden neighborhoods of related terms while unrelated terms blur outside the focal region.',
        layout: 'wide-field-moving-lens',
        motion: 'lens-scan-focus-neighborhood-isolate',
        novelty: 'meaning-optics',
        patterns: ['focus-and-context', 'local-similarity'],
        primitives: ['magnifier', 'blur-field', 'term-cloud'],
        transitionIn: ['search-cursor', 'spotlight'],
        transitionOut: ['focused-cluster', 'lens-portal'],
        camera: 'locked-field-lens-motion',
        direction: 'mixed',
        energy: 'measured',
        density: 'dense',
        complexity: 'medium',
      },
      {
        slug: 'concept-neighborhood-elevator',
        title: 'Concept Neighborhood Elevator',
        description: 'The viewer moves through stacked semantic floors, each floor representing a broader or narrower level of meaning.',
        layout: 'vertical-semantic-floors',
        motion: 'camera-rise-floors-expand-specificity-shift',
        novelty: 'semantic-building',
        patterns: ['general-to-specific', 'hierarchy'],
        primitives: ['floor-plates', 'concept-labels', 'depth-fog'],
        transitionIn: ['floor-open', 'vertical-lift'],
        transitionOut: ['roof-release', 'top-down-map'],
        camera: 'elevator-rise',
        direction: 'bottom-to-top',
        energy: 'measured',
        density: 'balanced',
        complexity: 'high',
      },
    ],
  },
  {
    family: 'relationship-network',
    tags: ['attention', 'relationship', 'graph', 'connection', 'dependency', 'context'],
    variants: [
      {
        slug: 'dependency-bridge-builder',
        title: 'Dependency Bridge Builder',
        description: 'Separated words construct weighted bridge segments toward the terms they depend on, with weak bridges dissolving.',
        layout: 'islands-and-bridges',
        motion: 'islands-separate-bridges-grow-load-test',
        novelty: 'relationship-infrastructure',
        patterns: ['dependency', 'strong-vs-weak-links'],
        primitives: ['islands', 'bridge-segments', 'weight-pulses'],
        transitionIn: ['node-islands', 'gap-open'],
        transitionOut: ['bridge-path', 'network-pan'],
        camera: 'angled-map-view',
        direction: 'outside-in',
        energy: 'dynamic',
        density: 'balanced',
        complexity: 'high',
        status: 'prototype',
      },
      {
        slug: 'graph-bloom',
        title: 'Graph Bloom',
        description: 'A central concept grows branches, sub-branches, and weighted leaves while irrelevant growth prunes itself away.',
        layout: 'organic-radial-graph',
        motion: 'seed-grow-branch-weight-prune',
        novelty: 'organic-knowledge-graph',
        patterns: ['relationship-expansion', 'pruning'],
        primitives: ['bezier-branches', 'node-leaves', 'prune-dissolve'],
        transitionIn: ['seed-point', 'central-pulse'],
        transitionOut: ['branch-follow', 'leaf-particles'],
        camera: 'gentle-radial-push',
        direction: 'center-out',
        energy: 'measured',
        density: 'dense',
        complexity: 'high',
      },
      {
        slug: 'relevance-pulse-map',
        title: 'Relevance Pulse Map',
        description: 'Signals travel across a word map and return with different strengths, revealing which relationships carry the most relevance.',
        layout: 'distributed-signal-map',
        motion: 'signal-send-propagate-return-amplify',
        novelty: 'network-echo',
        patterns: ['attention-weight', 'signal-strength'],
        primitives: ['nodes', 'pulse-rings', 'return-signals'],
        transitionIn: ['single-pulse', 'radar-ring'],
        transitionOut: ['strongest-signal', 'path-highlight'],
        camera: 'top-down-network',
        direction: 'circular',
        energy: 'dynamic',
        density: 'balanced',
        complexity: 'medium',
      },
      {
        slug: 'context-thread-braider',
        title: 'Context Thread Braider',
        description: 'Separate contextual threads braid into one interpretation, while removing one strand visibly changes the final meaning.',
        layout: 'parallel-threads-to-braid',
        motion: 'threads-enter-braid-tighten-remove-reform',
        novelty: 'context-braiding',
        patterns: ['many-contexts-one-result', 'dependency'],
        primitives: ['ribbons', 'braid-paths', 'result-knot'],
        transitionIn: ['parallel-streams', 'multi-source'],
        transitionOut: ['single-rope', 'knot-release'],
        camera: 'side-follow-braid',
        direction: 'left-to-right',
        energy: 'measured',
        density: 'balanced',
        complexity: 'high',
      },
    ],
  },
  {
    family: 'probability',
    tags: ['probability', 'prediction', 'candidate', 'confidence', 'next-token', 'uncertainty'],
    variants: [
      {
        slug: 'probability-fluid-columns',
        title: 'Probability Fluid Columns',
        description: 'Candidate words sit above fluid columns whose levels shift as context arrives, making changing probability visible without a static chart.',
        layout: 'three-fluid-columns',
        motion: 'context-drop-fluid-levels-shift-winner-overflow',
        novelty: 'probability-fluid',
        patterns: ['dynamic-ranking', 'uncertainty'],
        primitives: ['liquid-fill', 'candidate-labels', 'context-droplets'],
        transitionIn: ['droplet-fall', 'vertical-fill'],
        transitionOut: ['winner-overflow', 'liquid-stream'],
        camera: 'front-laboratory-view',
        direction: 'bottom-to-top',
        energy: 'dynamic',
        density: 'minimal',
        complexity: 'high',
        status: 'prototype',
      },
      {
        slug: 'candidate-orbit-selection',
        title: 'Candidate Orbit Selection',
        description: 'Possible next words orbit a sentence core at radii determined by probability until one spirals inward and locks into place.',
        layout: 'central-sentence-orbits',
        motion: 'candidates-orbit-radius-shift-spiral-select',
        novelty: 'probability-orbits',
        patterns: ['candidate-selection', 'relative-confidence'],
        primitives: ['orbit-paths', 'word-capsules', 'core-sentence'],
        transitionIn: ['central-core', 'particle-orbit'],
        transitionOut: ['selected-word', 'spiral-in'],
        camera: 'slight-orbital-parallax',
        direction: 'circular',
        energy: 'dynamic',
        density: 'balanced',
        complexity: 'medium',
      },
      {
        slug: 'confidence-weather-map',
        title: 'Confidence Weather Map',
        description: 'Candidate regions behave like a weather map: confidence pressure builds, fronts collide, and one stable region dominates.',
        layout: 'probability-weather-field',
        motion: 'pressure-zones-grow-fronts-collide-clear',
        novelty: 'uncertainty-weather',
        patterns: ['uncertainty-landscape', 'competition'],
        primitives: ['contour-zones', 'front-lines', 'candidate-pins'],
        transitionIn: ['map-fade', 'cloud-field'],
        transitionOut: ['clear-zone', 'front-sweep'],
        camera: 'top-down-map-zoom',
        direction: 'mixed',
        energy: 'calm',
        density: 'dense',
        complexity: 'high',
      },
      {
        slug: 'predictive-domino-fork',
        title: 'Predictive Domino Fork',
        description: 'One partial sentence reaches a fork of domino chains; context changes chain stability before the winning continuation falls cleanly.',
        layout: 'forked-domino-tracks',
        motion: 'prompt-arrives-tracks-test-winner-falls',
        novelty: 'prediction-dominoes',
        patterns: ['next-step-choice', 'causal-probability'],
        primitives: ['dominoes', 'fork-tracks', 'stability-wobble'],
        transitionIn: ['single-domino', 'path-split'],
        transitionOut: ['falling-chain', 'impact-word'],
        camera: 'low-track-follow',
        direction: 'depth-forward',
        energy: 'impact',
        density: 'balanced',
        complexity: 'medium',
      },
    ],
  },
  {
    family: 'model-processing',
    tags: ['model', 'layer', 'transformer', 'processing', 'inference', 'expert'],
    variants: [
      {
        slug: 'residual-river',
        title: 'Residual River',
        description: 'A main information stream flows through processing gates while side channels add residual information back into the current.',
        layout: 'main-river-with-side-channels',
        motion: 'stream-flow-gates-side-merge-refine',
        novelty: 'residual-hydraulics',
        patterns: ['iterative-refinement', 'residual-connection'],
        primitives: ['flow-ribbons', 'gates', 'merge-currents'],
        transitionIn: ['data-stream', 'river-source'],
        transitionOut: ['refined-stream', 'channel-rise'],
        camera: 'top-down-river-follow',
        direction: 'left-to-right',
        energy: 'measured',
        density: 'balanced',
        complexity: 'high',
        status: 'prototype',
      },
      {
        slug: 'transformer-tunnel',
        title: 'Transformer Tunnel',
        description: 'Information travels through a tunnel of distinct processing rings, changing one visible property at every ring.',
        layout: 'depth-ring-tunnel',
        motion: 'input-enter-rings-transform-exit',
        novelty: 'model-tunnel',
        patterns: ['layered-processing', 'progressive-change'],
        primitives: ['rings', 'input-core', 'property-markers'],
        transitionIn: ['portal-entry', 'depth-push'],
        transitionOut: ['tunnel-exit', 'forward-launch'],
        camera: 'first-person-tunnel',
        direction: 'depth-forward',
        energy: 'dynamic',
        density: 'balanced',
        complexity: 'high',
      },
      {
        slug: 'expert-routing-switchboard',
        title: 'Expert Routing Switchboard',
        description: 'A router sends different parts of an input to specialized expert modules, then recombines their strongest contributions.',
        layout: 'central-router-expert-modules',
        motion: 'input-split-route-experts-return-merge',
        novelty: 'mixture-of-experts-switchboard',
        patterns: ['specialization', 'routing'],
        primitives: ['router', 'module-cells', 'signal-packets'],
        transitionIn: ['single-input', 'central-pulse'],
        transitionOut: ['merged-result', 'packet-stream'],
        camera: 'isometric-control-board',
        direction: 'center-out',
        energy: 'dynamic',
        density: 'dense',
        complexity: 'high',
      },
      {
        slug: 'model-layer-book',
        title: 'Model Layer Book',
        description: 'Transparent processing pages turn one by one, each annotating and refining the same information without presenting a generic stack.',
        layout: 'open-transparent-book',
        motion: 'pages-turn-annotate-refine-resolve',
        novelty: 'layered-book',
        patterns: ['sequential-refinement', 'layer-explanation'],
        primitives: ['glass-pages', 'annotations', 'input-markers'],
        transitionIn: ['page-open', 'document-fold'],
        transitionOut: ['book-close', 'result-card'],
        camera: 'three-quarter-book-view',
        direction: 'right-to-left',
        energy: 'calm',
        density: 'balanced',
        complexity: 'medium',
      },
    ],
  },
  {
    family: 'generation',
    tags: ['generate', 'answer', 'output', 'word-by-word', 'completion', 'response'],
    variants: [
      {
        slug: 'answer-loom',
        title: 'Answer Loom',
        description: 'Context threads enter a loom and each shuttle pass adds one new word to a growing answer ribbon.',
        layout: 'loom-and-output-ribbon',
        motion: 'context-threads-shuttle-word-weave-ribbon',
        novelty: 'language-weaving',
        patterns: ['word-by-word-generation', 'context-to-output'],
        primitives: ['loom', 'word-shuttle', 'sentence-ribbon'],
        transitionIn: ['context-threads', 'parallel-lines'],
        transitionOut: ['answer-ribbon', 'fabric-unroll'],
        camera: 'side-loom-view',
        direction: 'left-to-right',
        energy: 'measured',
        density: 'balanced',
        complexity: 'high',
        status: 'prototype',
      },
      {
        slug: 'sentence-ribbon-fold',
        title: 'Sentence Ribbon Fold',
        description: 'A blank ribbon advances through prediction points and folds each chosen word into a readable sentence structure.',
        layout: 'horizontal-folding-ribbon',
        motion: 'ribbon-advance-choice-fold-word-lock',
        novelty: 'folded-language',
        patterns: ['sequential-output', 'construction'],
        primitives: ['ribbon', 'fold-points', 'word-labels'],
        transitionIn: ['blank-strip', 'line-grow'],
        transitionOut: ['folded-sentence', 'ribbon-swipe'],
        camera: 'angled-table-follow',
        direction: 'left-to-right',
        energy: 'dynamic',
        density: 'minimal',
        complexity: 'medium',
      },
      {
        slug: 'predictive-type-orchestra',
        title: 'Predictive Type Orchestra',
        description: 'Candidate word sections behave like an orchestra; only the strongest section plays, adding its word to the final phrase.',
        layout: 'semicircle-candidate-sections',
        motion: 'sections-ready-conductor-cue-word-soundwave',
        novelty: 'generation-orchestra',
        patterns: ['candidate-selection', 'sequential-generation'],
        primitives: ['section-arcs', 'conductor-pulse', 'word-waves'],
        transitionIn: ['semicircle-open', 'pulse-cue'],
        transitionOut: ['soundwave-word', 'center-line'],
        camera: 'wide-stage-push',
        direction: 'outside-in',
        energy: 'impact',
        density: 'dense',
        complexity: 'high',
      },
      {
        slug: 'response-constellation-write',
        title: 'Response Constellation Write',
        description: 'Selected concept stars descend from a semantic sky and align into words, then words align into a complete answer.',
        layout: 'upper-constellation-lower-sentence',
        motion: 'stars-select-descend-form-words-align',
        novelty: 'cosmic-generation',
        patterns: ['concept-to-language', 'many-to-sequence'],
        primitives: ['star-points', 'letter-morph', 'sentence-baseline'],
        transitionIn: ['constellation', 'particle-field'],
        transitionOut: ['sentence-glow', 'baseline-sweep'],
        camera: 'vertical-tilt-down',
        direction: 'top-to-bottom',
        energy: 'calm',
        density: 'balanced',
        complexity: 'high',
      },
    ],
  },
  {
    family: 'risk-contrast',
    tags: ['risk', 'hallucination', 'wrong', 'verify', 'truth', 'confidence'],
    variants: [
      {
        slug: 'confidence-glass-crack',
        title: 'Confidence Glass Crack',
        description: 'A polished confident statement appears on glass; evidence pressure reveals hidden fractures and separates wording from truth.',
        layout: 'single-glass-statement',
        motion: 'statement-polish-pressure-crack-evidence-reveal',
        novelty: 'confidence-fracture',
        patterns: ['appearance-vs-reality', 'verification'],
        primitives: ['glass-panel', 'crack-paths', 'evidence-tags'],
        transitionIn: ['clean-card', 'shine-pass'],
        transitionOut: ['crack-spread', 'fragment-fall'],
        camera: 'close-front-with-impact-push',
        direction: 'center-out',
        energy: 'impact',
        density: 'minimal',
        complexity: 'medium',
        status: 'prototype',
      },
      {
        slug: 'hallucination-mirage',
        title: 'Hallucination Mirage',
        description: 'A convincing answer appears as a stable object in the distance but distorts and disappears when a source marker approaches.',
        layout: 'depth-desert-mirage',
        motion: 'answer-appears-approach-distort-source-test',
        novelty: 'truth-mirage',
        patterns: ['plausible-but-false', 'source-check'],
        primitives: ['heat-distortion', 'answer-monument', 'source-marker'],
        transitionIn: ['horizon-glow', 'depth-fade'],
        transitionOut: ['distortion-collapse', 'warning-marker'],
        camera: 'slow-depth-approach',
        direction: 'depth-forward',
        energy: 'calm',
        density: 'minimal',
        complexity: 'high',
      },
      {
        slug: 'source-checkpoint-gates',
        title: 'Source Checkpoint Gates',
        description: 'Claims travel through source, date, and evidence gates; unsupported claims are redirected before reaching the final answer.',
        layout: 'three-checkpoint-track',
        motion: 'claims-travel-gates-check-redirect-pass',
        novelty: 'verification-checkpoints',
        patterns: ['quality-control', 'fact-checking'],
        primitives: ['gates', 'claim-packets', 'redirect-lanes'],
        transitionIn: ['track-entry', 'packet-stream'],
        transitionOut: ['verified-output', 'green-gate-open'],
        camera: 'isometric-track-follow',
        direction: 'left-to-right',
        energy: 'dynamic',
        density: 'balanced',
        complexity: 'medium',
      },
      {
        slug: 'truth-shadow-comparison',
        title: 'Truth Shadow Comparison',
        description: 'A confident answer casts a shadow that reveals missing evidence, contradictions, or outdated information behind the visible statement.',
        layout: 'foreground-statement-shadow-wall',
        motion: 'statement-rise-light-shift-shadow-reveal',
        novelty: 'evidence-shadow',
        patterns: ['hidden-risk', 'visible-vs-hidden'],
        primitives: ['light-source', 'statement-object', 'shadow-icons'],
        transitionIn: ['light-on', 'object-rise'],
        transitionOut: ['shadow-expand', 'warning-wipe'],
        camera: 'side-lighting-view',
        direction: 'right-to-left',
        energy: 'measured',
        density: 'balanced',
        complexity: 'high',
      },
    ],
  },
  {
    family: 'comparison',
    tags: ['compare', 'versus', 'difference', 'better', 'faster', 'choice'],
    variants: [
      {
        slug: 'benchmark-racetrack',
        title: 'Benchmark Racetrack',
        description: 'Competing options move through metric-specific track sections, so speed, cost, and quality each affect a different part of the race.',
        layout: 'multi-segment-racetrack',
        motion: 'competitors-launch-metrics-affect-overtake-finish',
        novelty: 'multi-metric-race',
        patterns: ['comparison', 'tradeoff'],
        primitives: ['tracks', 'competitor-markers', 'metric-zones'],
        transitionIn: ['start-lights', 'parallel-entry'],
        transitionOut: ['finish-line', 'winner-zoom'],
        camera: 'track-side-follow',
        direction: 'left-to-right',
        energy: 'impact',
        density: 'balanced',
        complexity: 'high',
        status: 'prototype',
      },
      {
        slug: 'difference-magnifier',
        title: 'Difference Magnifier',
        description: 'Two similar options overlap until a moving lens isolates the small details that materially change the outcome.',
        layout: 'overlap-with-moving-lens',
        motion: 'options-align-lens-scan-differences-expand',
        novelty: 'comparison-optics',
        patterns: ['subtle-difference', 'feature-comparison'],
        primitives: ['overlap-cards', 'magnifier', 'difference-markers'],
        transitionIn: ['two-options', 'overlap-morph'],
        transitionOut: ['highlighted-difference', 'lens-portal'],
        camera: 'locked-front',
        direction: 'mixed',
        energy: 'measured',
        density: 'balanced',
        complexity: 'medium',
      },
      {
        slug: 'tradeoff-seesaw-landscape',
        title: 'Tradeoff Seesaw Landscape',
        description: 'Changing one metric physically reshapes a landscape and tilts the two options, showing that no option wins every dimension.',
        layout: 'two-platform-landscape',
        motion: 'metric-adjust-landscape-shift-platforms-tilt',
        novelty: 'tradeoff-terrain',
        patterns: ['tradeoff', 'multi-dimensional-choice'],
        primitives: ['platforms', 'terrain', 'metric-sliders'],
        transitionIn: ['split-platforms', 'ground-rise'],
        transitionOut: ['chosen-platform', 'terrain-fold'],
        camera: 'wide-isometric-view',
        direction: 'mixed',
        energy: 'dynamic',
        density: 'balanced',
        complexity: 'high',
      },
      {
        slug: 'parallel-worlds-split',
        title: 'Parallel Worlds Split',
        description: 'One starting situation divides into two synchronized worlds, each evolving under a different tool, method, or decision.',
        layout: 'mirrored-worlds',
        motion: 'single-start-split-parallel-evolve-rejoin',
        novelty: 'scenario-comparison',
        patterns: ['before-after-alternatives', 'choice-consequence'],
        primitives: ['world-panels', 'shared-origin', 'result-portals'],
        transitionIn: ['single-scene', 'center-split'],
        transitionOut: ['world-rejoin', 'result-focus'],
        camera: 'synchronized-dual-pan',
        direction: 'center-out',
        energy: 'dynamic',
        density: 'dense',
        complexity: 'high',
      },
    ],
  },
  {
    family: 'ranking',
    tags: ['ranking', 'top', 'order', 'best', 'score', 'priority'],
    variants: [
      {
        slug: 'dynamic-podium-rise',
        title: 'Dynamic Podium Rise',
        description: 'Candidates rise from a common floor while live score changes reshape podium heights before the final order locks.',
        layout: 'adaptive-podium',
        motion: 'candidates-enter-scores-shift-podium-lock',
        novelty: 'living-podium',
        patterns: ['top-list', 'ranking-change'],
        primitives: ['podium-blocks', 'candidate-icons', 'score-counters'],
        transitionIn: ['floor-grid', 'candidates-drop'],
        transitionOut: ['winner-rise', 'podium-collapse'],
        camera: 'low-front-push',
        direction: 'bottom-to-top',
        energy: 'impact',
        density: 'balanced',
        complexity: 'medium',
        status: 'prototype',
      },
      {
        slug: 'priority-orbit-stack',
        title: 'Priority Orbit Stack',
        description: 'Items orbit a central goal and move inward according to priority, forming a compact ordered stack at the center.',
        layout: 'orbit-to-center-stack',
        motion: 'items-orbit-score-inward-stack',
        novelty: 'orbital-ranking',
        patterns: ['priority', 'ranking'],
        primitives: ['orbit-rings', 'item-capsules', 'central-stack'],
        transitionIn: ['item-field', 'orbit-start'],
        transitionOut: ['ordered-stack', 'center-zoom'],
        camera: 'top-down-orbit',
        direction: 'circular',
        energy: 'dynamic',
        density: 'balanced',
        complexity: 'medium',
      },
      {
        slug: 'ranking-ladder-climb',
        title: 'Ranking Ladder Climb',
        description: 'Candidates climb a visible ladder as criteria appear, with slips and overtakes explaining why positions change.',
        layout: 'vertical-ladder-lanes',
        motion: 'candidates-climb-criteria-hit-slip-overtake',
        novelty: 'competitive-ladder',
        patterns: ['ordered-list', 'criteria-impact'],
        primitives: ['ladder', 'candidate-markers', 'criteria-gates'],
        transitionIn: ['bottom-entry', 'ladder-unfold'],
        transitionOut: ['top-position', 'vertical-launch'],
        camera: 'vertical-follow',
        direction: 'bottom-to-top',
        energy: 'dynamic',
        density: 'dense',
        complexity: 'high',
      },
      {
        slug: 'constellation-rank-align',
        title: 'Constellation Rank Align',
        description: 'Scattered candidates form a constellation whose vertical position and brightness encode rank without using bars or cards.',
        layout: 'ranked-star-field',
        motion: 'candidates-scatter-score-glow-align',
        novelty: 'celestial-ranking',
        patterns: ['ranking', 'relative-score'],
        primitives: ['stars', 'guidelines', 'score-glow'],
        transitionIn: ['particle-field', 'stars-appear'],
        transitionOut: ['top-star', 'light-trail'],
        camera: 'slow-field-drift',
        direction: 'outside-in',
        energy: 'calm',
        density: 'balanced',
        complexity: 'medium',
      },
    ],
  },
  {
    family: 'process-flow',
    tags: ['process', 'steps', 'workflow', 'pipeline', 'sequence', 'automation'],
    variants: [
      {
        slug: 'subway-workflow-map',
        title: 'Subway Workflow Map',
        description: 'A workflow behaves like a subway network where inputs travel through stations, transfers, and branch decisions to reach an outcome.',
        layout: 'metro-map-network',
        motion: 'line-draw-packet-travel-transfer-arrive',
        novelty: 'workflow-transit',
        patterns: ['multi-step-process', 'branching-workflow'],
        primitives: ['metro-lines', 'stations', 'travel-packet'],
        transitionIn: ['map-unfold', 'line-draw'],
        transitionOut: ['arrival-station', 'line-continue'],
        camera: 'top-down-map-pan',
        direction: 'mixed',
        energy: 'measured',
        density: 'dense',
        complexity: 'high',
        status: 'prototype',
      },
      {
        slug: 'automation-conveyor-cells',
        title: 'Automation Conveyor Cells',
        description: 'An input moves through specialized cells that each perform one visible operation before handing it to the next.',
        layout: 'modular-conveyor-cells',
        motion: 'input-travel-cell-action-handoff-output',
        novelty: 'factory-workflow',
        patterns: ['sequential-automation', 'step-by-step'],
        primitives: ['conveyor', 'work-cells', 'handoff-arms'],
        transitionIn: ['input-drop', 'belt-start'],
        transitionOut: ['finished-output', 'belt-exit'],
        camera: 'isometric-factory-follow',
        direction: 'left-to-right',
        energy: 'dynamic',
        density: 'balanced',
        complexity: 'high',
      },
      {
        slug: 'workflow-domino-logic',
        title: 'Workflow Domino Logic',
        description: 'Each process step activates the next only after its condition becomes valid, making dependencies explicit through controlled domino motion.',
        layout: 'conditional-domino-route',
        motion: 'step-ready-condition-check-domino-trigger',
        novelty: 'dependency-dominoes',
        patterns: ['dependency', 'sequential-trigger'],
        primitives: ['dominoes', 'condition-gates', 'status-lights'],
        transitionIn: ['first-trigger', 'single-step'],
        transitionOut: ['final-impact', 'result-rise'],
        camera: 'low-route-follow',
        direction: 'depth-forward',
        energy: 'impact',
        density: 'balanced',
        complexity: 'medium',
      },
      {
        slug: 'circular-feedback-workshop',
        title: 'Circular Feedback Workshop',
        description: 'A result returns through review and improvement stations, visibly changing on each loop until quality stabilizes.',
        layout: 'circular-workshop-loop',
        motion: 'draft-travel-review-mark-improve-repeat',
        novelty: 'iterative-workshop',
        patterns: ['feedback-loop', 'iteration'],
        primitives: ['loop-track', 'review-tools', 'version-object'],
        transitionIn: ['loop-draw', 'draft-entry'],
        transitionOut: ['quality-lock', 'loop-open'],
        camera: 'top-down-circular',
        direction: 'circular',
        energy: 'measured',
        density: 'balanced',
        complexity: 'high',
      },
    ],
  },
  {
    family: 'input-output',
    tags: ['input', 'output', 'result', 'transform', 'cause', 'effect'],
    variants: [
      {
        slug: 'cause-effect-bridge',
        title: 'Cause Effect Bridge',
        description: 'An input creates bridge segments across a gap; each segment represents a transformation required to reach the output.',
        layout: 'input-cliff-output-cliff',
        motion: 'input-arrive-segments-build-cross-result',
        novelty: 'transformation-bridge',
        patterns: ['input-to-output', 'cause-effect'],
        primitives: ['cliffs', 'bridge-segments', 'input-object'],
        transitionIn: ['gap-open', 'input-land'],
        transitionOut: ['output-cross', 'bridge-pan'],
        camera: 'side-depth-view',
        direction: 'left-to-right',
        energy: 'dynamic',
        density: 'minimal',
        complexity: 'medium',
        status: 'prototype',
      },
      {
        slug: 'transformation-portal',
        title: 'Transformation Portal',
        description: 'A clearly labeled input enters a portal whose internal rings expose transformation stages before a visibly different result exits.',
        layout: 'portal-cutaway',
        motion: 'input-enter-rings-transform-output-exit',
        novelty: 'cutaway-portal',
        patterns: ['input-output', 'hidden-process'],
        primitives: ['portal-rings', 'input-object', 'output-object'],
        transitionIn: ['object-approach', 'portal-open'],
        transitionOut: ['object-exit', 'light-burst'],
        camera: 'side-cutaway',
        direction: 'left-to-right',
        energy: 'impact',
        density: 'balanced',
        complexity: 'high',
      },
      {
        slug: 'funnel-compression-output',
        title: 'Funnel Compression Output',
        description: 'Many noisy inputs enter a funnel that filters, groups, and compresses them into one concise result.',
        layout: 'wide-input-funnel-single-output',
        motion: 'many-enter-filter-group-compress-release',
        novelty: 'semantic-compression-funnel',
        patterns: ['many-to-one', 'summarization'],
        primitives: ['funnel', 'input-particles', 'filter-membranes'],
        transitionIn: ['wide-field', 'many-inputs'],
        transitionOut: ['single-output', 'focused-beam'],
        camera: 'front-cutaway',
        direction: 'top-to-bottom',
        energy: 'measured',
        density: 'dense',
        complexity: 'medium',
      },
      {
        slug: 'machine-blueprint-reveal',
        title: 'Machine Blueprint Reveal',
        description: 'A black-box result opens into a blueprint view that traces how the input caused each internal state change.',
        layout: 'closed-box-to-blueprint',
        motion: 'box-operate-open-xray-trace-close',
        novelty: 'explainable-machine',
        patterns: ['black-box-explanation', 'cause-effect'],
        primitives: ['machine-shell', 'blueprint-lines', 'state-nodes'],
        transitionIn: ['black-box', 'input-insert'],
        transitionOut: ['blueprint-collapse', 'result-focus'],
        camera: 'front-xray-push',
        direction: 'center-out',
        energy: 'measured',
        density: 'dense',
        complexity: 'high',
      },
    ],
  },
  {
    family: 'error-detection',
    tags: ['error', 'debug', 'anomaly', 'failure', 'fix', 'warning'],
    variants: [
      {
        slug: 'anomaly-xray-scanner',
        title: 'Anomaly X-Ray Scanner',
        description: 'A normal-looking process passes through an X-ray plane that reveals hidden anomalies, their origin, and their downstream effect.',
        layout: 'process-with-moving-xray',
        motion: 'process-run-xray-scan-anomaly-highlight-trace',
        novelty: 'debug-xray',
        patterns: ['hidden-error', 'root-cause'],
        primitives: ['xray-plane', 'process-object', 'anomaly-marker'],
        transitionIn: ['scanner-enter', 'process-run'],
        transitionOut: ['error-focus', 'repair-path'],
        camera: 'side-scanner-view',
        direction: 'left-to-right',
        energy: 'dynamic',
        density: 'balanced',
        complexity: 'high',
        status: 'prototype',
      },
      {
        slug: 'broken-path-repair',
        title: 'Broken Path Repair',
        description: 'A signal follows a route until it reaches a broken segment; diagnostics isolate the break and reconstruct the route visibly.',
        layout: 'single-route-with-break',
        motion: 'signal-travel-stop-diagnose-repair-resume',
        novelty: 'repair-narrative',
        patterns: ['error-path', 'fix'],
        primitives: ['route-line', 'signal-pulse', 'repair-pieces'],
        transitionIn: ['signal-entry', 'line-draw'],
        transitionOut: ['signal-resume', 'green-path'],
        camera: 'top-down-route-follow',
        direction: 'left-to-right',
        energy: 'impact',
        density: 'minimal',
        complexity: 'medium',
      },
      {
        slug: 'red-flag-cascade',
        title: 'Red Flag Cascade',
        description: 'One small upstream issue triggers a visible cascade of warnings, then isolating the root flag stops all downstream alerts.',
        layout: 'tiered-cascade',
        motion: 'root-error-pulse-flags-cascade-isolate-clear',
        novelty: 'failure-cascade',
        patterns: ['downstream-impact', 'root-cause'],
        primitives: ['tiers', 'warning-flags', 'cascade-lines'],
        transitionIn: ['single-warning', 'top-pulse'],
        transitionOut: ['cascade-clear', 'root-marker'],
        camera: 'vertical-follow-down',
        direction: 'top-to-bottom',
        energy: 'impact',
        density: 'dense',
        complexity: 'medium',
      },
      {
        slug: 'debugger-time-scrub',
        title: 'Debugger Time Scrub',
        description: 'A process timeline scrubs backward from failure to the first frame where state diverges from the expected path.',
        layout: 'timeline-with-state-panels',
        motion: 'failure-freeze-scrub-back-divergence-mark-replay',
        novelty: 'temporal-debugging',
        patterns: ['find-first-error', 'timeline-analysis'],
        primitives: ['timeline', 'state-snapshots', 'scrubber'],
        transitionIn: ['failure-freeze', 'timeline-open'],
        transitionOut: ['corrected-replay', 'timeline-forward'],
        camera: 'locked-editor-view',
        direction: 'right-to-left',
        energy: 'measured',
        density: 'dense',
        complexity: 'high',
      },
    ],
  },
  {
    family: 'retrieval-search',
    tags: ['search', 'retrieval', 'rag', 'document', 'evidence', 'knowledge'],
    variants: [
      {
        slug: 'knowledge-magnet',
        title: 'Knowledge Magnet',
        description: 'A query becomes a shaped magnetic field that attracts only relevant evidence fragments from a large document space.',
        layout: 'query-center-document-field',
        motion: 'query-charge-field-bend-fragments-attract-rank',
        novelty: 'semantic-magnetism',
        patterns: ['retrieval', 'relevance-filtering'],
        primitives: ['query-core', 'document-fragments', 'field-lines'],
        transitionIn: ['query-drop', 'field-activate'],
        transitionOut: ['evidence-stack', 'fragments-merge'],
        camera: 'top-down-field-push',
        direction: 'outside-in',
        energy: 'dynamic',
        density: 'dense',
        complexity: 'high',
        status: 'prototype',
      },
      {
        slug: 'archive-spotlight-search',
        title: 'Archive Spotlight Search',
        description: 'A moving spotlight scans shelves of documents, opens promising sources, and extracts the exact lines that support the answer.',
        layout: 'depth-archive-shelves',
        motion: 'spotlight-scan-source-open-lines-extract',
        novelty: 'retrieval-archive',
        patterns: ['search', 'evidence-extraction'],
        primitives: ['shelves', 'spotlight', 'document-pages'],
        transitionIn: ['dark-archive', 'light-on'],
        transitionOut: ['quote-strip', 'source-card'],
        camera: 'aisle-dolly',
        direction: 'depth-forward',
        energy: 'calm',
        density: 'dense',
        complexity: 'high',
      },
      {
        slug: 'query-radar-sweep',
        title: 'Query Radar Sweep',
        description: 'A query radar scans a knowledge field; relevant sources respond with stronger echoes and move into a ranked evidence ring.',
        layout: 'radar-knowledge-field',
        motion: 'radar-sweep-echoes-strength-rank-ring',
        novelty: 'retrieval-radar',
        patterns: ['search', 'relevance-ranking'],
        primitives: ['radar', 'source-points', 'echo-rings'],
        transitionIn: ['pulse-center', 'radar-start'],
        transitionOut: ['selected-echoes', 'ring-collapse'],
        camera: 'top-down-radar',
        direction: 'circular',
        energy: 'dynamic',
        density: 'balanced',
        complexity: 'medium',
      },
      {
        slug: 'evidence-fishing-lines',
        title: 'Evidence Fishing Lines',
        description: 'A query casts multiple lines into different sources; weak matches release while supported evidence is reeled into the answer.',
        layout: 'query-deck-source-depths',
        motion: 'lines-cast-hook-test-release-reel',
        novelty: 'retrieval-fishing',
        patterns: ['multi-source-search', 'selection'],
        primitives: ['query-hook', 'source-zones', 'evidence-cards'],
        transitionIn: ['line-cast', 'source-water'],
        transitionOut: ['evidence-reel', 'answer-assemble'],
        camera: 'side-depth-view',
        direction: 'depth-forward',
        energy: 'measured',
        density: 'balanced',
        complexity: 'high',
      },
    ],
  },
  {
    family: 'security-privacy',
    tags: ['security', 'privacy', 'encryption', 'permission', 'data', 'protection'],
    variants: [
      {
        slug: 'encryption-vault-layers',
        title: 'Encryption Vault Layers',
        description: 'Sensitive data travels through multiple cryptographic shells before entering a vault, with each layer showing its protective role.',
        layout: 'concentric-vault-shells',
        motion: 'data-enter-shells-encrypt-lock-vault',
        novelty: 'layered-encryption-vault',
        patterns: ['protection-layers', 'encryption'],
        primitives: ['vault', 'cipher-shells', 'data-core'],
        transitionIn: ['data-core', 'rings-close'],
        transitionOut: ['vault-lock', 'shield-pulse'],
        camera: 'depth-center-push',
        direction: 'outside-in',
        energy: 'impact',
        density: 'balanced',
        complexity: 'high',
        status: 'prototype',
      },
      {
        slug: 'permission-gate-city',
        title: 'Permission Gate City',
        description: 'Requests move through a city of permission gates where identity, role, and scope determine which route remains open.',
        layout: 'permission-city-map',
        motion: 'request-enter-gates-check-route-open-deny',
        novelty: 'access-control-city',
        patterns: ['authorization', 'conditional-access'],
        primitives: ['gates', 'request-packets', 'route-map'],
        transitionIn: ['request-entry', 'city-lights'],
        transitionOut: ['approved-route', 'denied-barrier'],
        camera: 'isometric-city-follow',
        direction: 'mixed',
        energy: 'dynamic',
        density: 'dense',
        complexity: 'high',
      },
      {
        slug: 'data-leak-containment',
        title: 'Data Leak Containment',
        description: 'Escaping data particles reveal a leak, while segmented barriers close around the breach and restore the protected boundary.',
        layout: 'protected-container-breach',
        motion: 'data-flow-leak-detect-barriers-close-recover',
        novelty: 'breach-containment',
        patterns: ['security-failure', 'mitigation'],
        primitives: ['container', 'data-particles', 'barrier-segments'],
        transitionIn: ['normal-flow', 'breach-flash'],
        transitionOut: ['sealed-boundary', 'status-green'],
        camera: 'cutaway-container-view',
        direction: 'center-out',
        energy: 'impact',
        density: 'balanced',
        complexity: 'medium',
      },
      {
        slug: 'privacy-redaction-wave',
        title: 'Privacy Redaction Wave',
        description: 'A privacy wave passes over a document, selectively masking personal data while preserving the information needed for the task.',
        layout: 'full-document-scan',
        motion: 'document-reveal-wave-scan-redact-preserve',
        novelty: 'selective-redaction-wave',
        patterns: ['privacy', 'data-minimization'],
        primitives: ['document', 'scan-wave', 'redaction-bars'],
        transitionIn: ['document-open', 'scan-start'],
        transitionOut: ['safe-document', 'mask-dissolve'],
        camera: 'top-down-document',
        direction: 'top-to-bottom',
        energy: 'measured',
        density: 'dense',
        complexity: 'medium',
      },
    ],
  },
  {
    family: 'scale-performance',
    tags: ['performance', 'latency', 'scale', 'throughput', 'load', 'speed'],
    variants: [
      {
        slug: 'latency-tunnel-race',
        title: 'Latency Tunnel Race',
        description: 'Identical requests race through differently structured tunnels, revealing where latency accumulates and which design removes bottlenecks.',
        layout: 'parallel-depth-tunnels',
        motion: 'requests-launch-tunnels-slow-zones-overtake',
        novelty: 'latency-tunnel',
        patterns: ['speed-comparison', 'bottleneck'],
        primitives: ['tunnels', 'request-pulses', 'latency-zones'],
        transitionIn: ['start-gate', 'parallel-pulses'],
        transitionOut: ['fast-exit', 'time-counter'],
        camera: 'dual-tunnel-follow',
        direction: 'depth-forward',
        energy: 'impact',
        density: 'balanced',
        complexity: 'high',
        status: 'prototype',
      },
      {
        slug: 'load-balancing-city',
        title: 'Load Balancing City',
        description: 'Incoming traffic enters a service city and reroutes dynamically as buildings approach capacity.',
        layout: 'isometric-service-city',
        motion: 'traffic-arrive-load-rise-router-shift-stabilize',
        novelty: 'infrastructure-city',
        patterns: ['load-balancing', 'distributed-systems'],
        primitives: ['service-buildings', 'traffic-packets', 'router-hub'],
        transitionIn: ['traffic-stream', 'city-wake'],
        transitionOut: ['balanced-grid', 'network-zoom'],
        camera: 'isometric-city-orbit',
        direction: 'center-out',
        energy: 'dynamic',
        density: 'dense',
        complexity: 'high',
      },
      {
        slug: 'throughput-pipe-pressure',
        title: 'Throughput Pipe Pressure',
        description: 'Data pressure moves through pipes of different widths, showing throughput, congestion, and the effect of parallel channels.',
        layout: 'pipe-network-cutaway',
        motion: 'packets-flow-pressure-build-parallel-open-clear',
        novelty: 'throughput-hydraulics',
        patterns: ['capacity', 'bottleneck'],
        primitives: ['pipes', 'packets', 'pressure-gauges'],
        transitionIn: ['packet-flow', 'pipe-entry'],
        transitionOut: ['pressure-release', 'wide-channel'],
        camera: 'side-cutaway',
        direction: 'left-to-right',
        energy: 'dynamic',
        density: 'balanced',
        complexity: 'medium',
      },
      {
        slug: 'scaling-staircase',
        title: 'Scaling Staircase',
        description: 'Demand climbs a staircase while capacity modules deploy ahead of it, making under-scaling and over-scaling immediately visible.',
        layout: 'demand-capacity-staircase',
        motion: 'demand-rise-capacity-deploy-gap-close',
        novelty: 'elastic-scaling-stairs',
        patterns: ['scaling', 'capacity-planning'],
        primitives: ['stairs', 'demand-wave', 'capacity-blocks'],
        transitionIn: ['baseline-rise', 'first-step'],
        transitionOut: ['balanced-plateau', 'upward-launch'],
        camera: 'side-elevation-follow',
        direction: 'bottom-to-top',
        energy: 'measured',
        density: 'minimal',
        complexity: 'medium',
      },
    ],
  },
  {
    family: 'cost-efficiency',
    tags: ['cost', 'price', 'budget', 'efficiency', 'token-cost', 'resource'],
    variants: [
      {
        slug: 'budget-leak-meter',
        title: 'Budget Leak Meter',
        description: 'A visible budget reservoir drains through specific waste leaks until optimizations seal them and preserve value.',
        layout: 'budget-tank-with-leaks',
        motion: 'budget-fill-leaks-open-drain-seal-recover',
        novelty: 'cost-leak-hydraulics',
        patterns: ['waste', 'cost-optimization'],
        primitives: ['tank', 'leak-pipes', 'cost-counter'],
        transitionIn: ['budget-fill', 'counter-rise'],
        transitionOut: ['sealed-tank', 'savings-badge'],
        camera: 'front-cutaway',
        direction: 'top-to-bottom',
        energy: 'dynamic',
        density: 'balanced',
        complexity: 'medium',
        status: 'prototype',
      },
      {
        slug: 'token-cost-conveyor',
        title: 'Token Cost Conveyor',
        description: 'Prompt and output tokens travel across a price conveyor where unnecessary pieces are removed and the cost counter responds instantly.',
        layout: 'dual-token-conveyor',
        motion: 'tokens-enter-count-price-filter-total-drop',
        novelty: 'token-economics-machine',
        patterns: ['usage-cost', 'optimization'],
        primitives: ['token-tiles', 'conveyor', 'price-counter'],
        transitionIn: ['token-stream', 'belt-start'],
        transitionOut: ['cost-total', 'receipt-strip'],
        camera: 'isometric-conveyor',
        direction: 'left-to-right',
        energy: 'measured',
        density: 'dense',
        complexity: 'medium',
      },
      {
        slug: 'value-seesaw',
        title: 'Value Seesaw',
        description: 'Cost and result quality sit on a seesaw whose balance changes as features, speed, and reliability are adjusted.',
        layout: 'metric-seesaw',
        motion: 'cost-load-quality-load-adjust-balance',
        novelty: 'value-balance',
        patterns: ['cost-benefit', 'tradeoff'],
        primitives: ['seesaw', 'metric-weights', 'value-marker'],
        transitionIn: ['center-pivot', 'weights-drop'],
        transitionOut: ['balance-lock', 'chosen-side'],
        camera: 'front-low-view',
        direction: 'mixed',
        energy: 'measured',
        density: 'minimal',
        complexity: 'low',
      },
      {
        slug: 'resource-packing-puzzle',
        title: 'Resource Packing Puzzle',
        description: 'Tasks pack into limited compute space; inefficient shapes waste capacity until a better arrangement uses the same budget more effectively.',
        layout: 'compute-container-puzzle',
        motion: 'tasks-drop-gaps-show-repack-fit',
        novelty: 'efficiency-packing',
        patterns: ['resource-efficiency', 'optimization'],
        primitives: ['container', 'task-shapes', 'capacity-grid'],
        transitionIn: ['empty-grid', 'tasks-fall'],
        transitionOut: ['perfect-fit', 'grid-compress'],
        camera: 'top-down-puzzle',
        direction: 'top-to-bottom',
        energy: 'dynamic',
        density: 'dense',
        complexity: 'medium',
      },
    ],
  },
  {
    family: 'time-change',
    tags: ['time', 'timeline', 'evolution', 'version', 'before-after', 'change'],
    variants: [
      {
        slug: 'timeline-microscope',
        title: 'Timeline Microscope',
        description: 'A broad timeline zooms into one critical period, revealing the smaller changes hidden between major milestones.',
        layout: 'macro-to-micro-timeline',
        motion: 'timeline-draw-focus-lens-zoom-events-expand',
        novelty: 'temporal-microscope',
        patterns: ['history', 'hidden-change'],
        primitives: ['timeline', 'focus-lens', 'event-markers'],
        transitionIn: ['line-draw', 'date-entry'],
        transitionOut: ['focused-event', 'time-portal'],
        camera: 'horizontal-zoom',
        direction: 'left-to-right',
        energy: 'measured',
        density: 'dense',
        complexity: 'medium',
        status: 'prototype',
      },
      {
        slug: 'version-evolution-tree',
        title: 'Version Evolution Tree',
        description: 'A product or model grows as a branching version tree where features appear, merge, and disappear across generations.',
        layout: 'horizontal-version-tree',
        motion: 'trunk-grow-versions-branch-features-merge',
        novelty: 'evolutionary-versioning',
        patterns: ['product-evolution', 'version-history'],
        primitives: ['tree-branches', 'version-nodes', 'feature-leaves'],
        transitionIn: ['seed-version', 'trunk-grow'],
        transitionOut: ['latest-version', 'branch-zoom'],
        camera: 'horizontal-tree-pan',
        direction: 'left-to-right',
        energy: 'calm',
        density: 'dense',
        complexity: 'high',
      },
      {
        slug: 'before-after-clock-face',
        title: 'Before After Clock Face',
        description: 'A clock hand sweeps between two states while the surrounding environment transforms continuously instead of using a static split screen.',
        layout: 'central-clock-transforming-world',
        motion: 'hand-sweep-world-morph-milestones-lock',
        novelty: 'temporal-world-morph',
        patterns: ['before-after', 'change-over-time'],
        primitives: ['clock', 'environment-layers', 'milestone-ticks'],
        transitionIn: ['clock-form', 'state-before'],
        transitionOut: ['state-after', 'hand-launch'],
        camera: 'locked-center-with-world-morph',
        direction: 'circular',
        energy: 'dynamic',
        density: 'balanced',
        complexity: 'high',
      },
      {
        slug: 'decay-renewal-cycle',
        title: 'Decay Renewal Cycle',
        description: 'Information visibly ages, loses confidence, receives a fresh update, and returns to a reliable state in a repeating cycle.',
        layout: 'circular-age-cycle',
        motion: 'fresh-age-fade-update-renew',
        novelty: 'knowledge-lifecycle',
        patterns: ['staleness', 'update-cycle'],
        primitives: ['cycle-ring', 'confidence-color', 'update-pulse'],
        transitionIn: ['fresh-state', 'cycle-start'],
        transitionOut: ['renewed-state', 'update-wave'],
        camera: 'top-down-cycle',
        direction: 'circular',
        energy: 'calm',
        density: 'minimal',
        complexity: 'medium',
      },
    ],
  },
  {
    family: 'human-ai-collaboration',
    tags: ['human', 'ai', 'collaboration', 'agent', 'feedback', 'team'],
    variants: [
      {
        slug: 'human-ai-relay',
        title: 'Human AI Relay',
        description: 'A task passes between human judgment and AI speed like a relay baton, with each participant handling the stage they do best.',
        layout: 'alternating-relay-track',
        motion: 'task-run-handoff-transform-handoff-finish',
        novelty: 'collaboration-relay',
        patterns: ['division-of-labor', 'human-in-the-loop'],
        primitives: ['relay-track', 'task-baton', 'role-zones'],
        transitionIn: ['task-start', 'first-runner'],
        transitionOut: ['joint-finish', 'result-banner'],
        camera: 'track-side-follow',
        direction: 'left-to-right',
        energy: 'impact',
        density: 'balanced',
        complexity: 'medium',
        status: 'prototype',
      },
      {
        slug: 'feedback-sculpting',
        title: 'Feedback Sculpting',
        description: 'AI produces a rough form and human feedback tools reshape it across iterations until the result reaches the target silhouette.',
        layout: 'central-sculpture-tool-ring',
        motion: 'rough-form-feedback-tools-shape-refine',
        novelty: 'iterative-sculpture',
        patterns: ['feedback-loop', 'co-creation'],
        primitives: ['morphing-object', 'feedback-tools', 'target-outline'],
        transitionIn: ['rough-shape', 'tool-ring'],
        transitionOut: ['final-form', 'outline-lock'],
        camera: 'slow-orbit-sculpture',
        direction: 'circular',
        energy: 'measured',
        density: 'balanced',
        complexity: 'high',
      },
      {
        slug: 'multi-agent-roundtable',
        title: 'Multi Agent Roundtable',
        description: 'Specialized agents contribute distinct evidence cards around a table before a coordinator resolves conflicts and assembles one answer.',
        layout: 'roundtable-agent-seats',
        motion: 'agents-contribute-cards-conflict-resolve-merge',
        novelty: 'agent-deliberation',
        patterns: ['multi-agent', 'specialized-team'],
        primitives: ['agent-seats', 'evidence-cards', 'coordinator-core'],
        transitionIn: ['seats-light', 'task-center'],
        transitionOut: ['merged-answer', 'table-collapse'],
        camera: 'top-down-roundtable-orbit',
        direction: 'outside-in',
        energy: 'dynamic',
        density: 'dense',
        complexity: 'high',
      },
      {
        slug: 'copilot-dual-track',
        title: 'Copilot Dual Track',
        description: 'Human intent and AI execution move on synchronized tracks, reconnecting at checkpoints where approval or correction is required.',
        layout: 'parallel-human-ai-tracks',
        motion: 'intent-track-execution-track-checkpoints-sync',
        novelty: 'dual-track-copilot',
        patterns: ['assisted-work', 'approval-loop'],
        primitives: ['parallel-tracks', 'intent-marker', 'execution-marker'],
        transitionIn: ['two-tracks', 'shared-start'],
        transitionOut: ['tracks-merge', 'approved-output'],
        camera: 'top-down-track-follow',
        direction: 'left-to-right',
        energy: 'measured',
        density: 'balanced',
        complexity: 'medium',
      },
    ],
  },
  {
    family: 'decision-logic',
    tags: ['decision', 'logic', 'if-then', 'choice', 'evidence', 'tradeoff'],
    variants: [
      {
        slug: 'decision-tree-burst',
        title: 'Decision Tree Burst',
        description: 'One question bursts into a controlled decision tree; invalid branches fold away while the valid route stays illuminated.',
        layout: 'radial-decision-tree',
        motion: 'question-seed-branches-burst-tests-prune-route',
        novelty: 'decision-firework',
        patterns: ['branching-logic', 'rule-evaluation'],
        primitives: ['branch-paths', 'condition-nodes', 'route-light'],
        transitionIn: ['question-core', 'branch-seed'],
        transitionOut: ['chosen-route', 'branch-collapse'],
        camera: 'radial-push-out',
        direction: 'center-out',
        energy: 'impact',
        density: 'dense',
        complexity: 'high',
        status: 'prototype',
      },
      {
        slug: 'if-then-gate-array',
        title: 'If Then Gate Array',
        description: 'Conditions arrive as signals at logic gates, opening only the route whose complete rule set is satisfied.',
        layout: 'logic-gate-array',
        motion: 'signals-arrive-gates-test-route-open',
        novelty: 'visual-logic-circuit',
        patterns: ['conditional-logic', 'decision'],
        primitives: ['logic-gates', 'signal-pulses', 'route-lines'],
        transitionIn: ['signals-enter', 'circuit-light'],
        transitionOut: ['open-route', 'result-pulse'],
        camera: 'top-down-circuit',
        direction: 'left-to-right',
        energy: 'dynamic',
        density: 'dense',
        complexity: 'medium',
      },
      {
        slug: 'evidence-jury',
        title: 'Evidence Jury',
        description: 'Evidence items take positions around a decision chamber, gain or lose credibility, and collectively tip the final verdict.',
        layout: 'circular-evidence-chamber',
        motion: 'evidence-enter-credibility-shift-deliberate-verdict',
        novelty: 'decision-jury',
        patterns: ['evidence-weighting', 'judgment'],
        primitives: ['evidence-seats', 'credibility-rings', 'verdict-core'],
        transitionIn: ['chamber-open', 'evidence-entry'],
        transitionOut: ['verdict-stamp', 'center-focus'],
        camera: 'slow-roundtable-orbit',
        direction: 'outside-in',
        energy: 'measured',
        density: 'balanced',
        complexity: 'high',
      },
      {
        slug: 'tradeoff-landscape-route',
        title: 'Tradeoff Landscape Route',
        description: 'A decision marker navigates a terrain shaped by cost, risk, speed, and quality, revealing why the best route depends on priorities.',
        layout: 'multi-metric-terrain-route',
        motion: 'metrics-shape-terrain-routes-compare-select',
        novelty: 'decision-geography',
        patterns: ['multi-criteria-decision', 'tradeoff'],
        primitives: ['terrain', 'route-lines', 'metric-beacons'],
        transitionIn: ['map-rise', 'decision-marker'],
        transitionOut: ['route-select', 'destination-glow'],
        camera: 'isometric-terrain-glide',
        direction: 'depth-forward',
        energy: 'calm',
        density: 'dense',
        complexity: 'high',
      },
    ],
  },
  {
    family: 'context-window',
    tags: ['context', 'window', 'memory', 'prompt', 'limit', 'conversation'],
    variants: [
      {
        slug: 'context-window-train',
        title: 'Context Window Train',
        description: 'Conversation cars enter a fixed-length train; new cars push the oldest context out while priority cars can be retained.',
        layout: 'horizontal-train-window',
        motion: 'cars-enter-window-shift-old-exit-pin',
        novelty: 'context-train',
        patterns: ['limited-memory', 'sliding-window'],
        primitives: ['train-cars', 'window-frame', 'priority-pins'],
        transitionIn: ['message-cars', 'track-entry'],
        transitionOut: ['old-car-exit', 'window-zoom'],
        camera: 'side-track-follow',
        direction: 'right-to-left',
        energy: 'dynamic',
        density: 'balanced',
        complexity: 'medium',
        status: 'prototype',
      },
      {
        slug: 'memory-shelf-carousel',
        title: 'Memory Shelf Carousel',
        description: 'Context items rotate through a bounded shelf carousel while retrieval brings relevant older items back into the active section.',
        layout: 'circular-memory-shelves',
        motion: 'items-load-carousel-rotate-retrieve-focus',
        novelty: 'memory-carousel',
        patterns: ['active-context', 'retrieval'],
        primitives: ['shelves', 'message-cards', 'retrieval-arm'],
        transitionIn: ['cards-enter', 'carousel-start'],
        transitionOut: ['selected-memory', 'card-focus'],
        camera: 'three-quarter-carousel-view',
        direction: 'circular',
        energy: 'measured',
        density: 'dense',
        complexity: 'high',
      },
      {
        slug: 'context-capacity-elevator',
        title: 'Context Capacity Elevator',
        description: 'Messages occupy elevator floors until capacity is reached; summarization compresses multiple floors into one compact memory block.',
        layout: 'vertical-capacity-building',
        motion: 'messages-fill-floors-capacity-hit-compress',
        novelty: 'context-building',
        patterns: ['capacity-limit', 'summarization'],
        primitives: ['floors', 'message-blocks', 'compression-press'],
        transitionIn: ['building-rise', 'messages-enter'],
        transitionOut: ['summary-block', 'elevator-exit'],
        camera: 'vertical-cutaway',
        direction: 'bottom-to-top',
        energy: 'measured',
        density: 'dense',
        complexity: 'high',
      },
      {
        slug: 'attention-spotlight-stage',
        title: 'Attention Spotlight Stage',
        description: 'The full context remains on stage while a moving spotlight activates only the words most relevant to the current generation step.',
        layout: 'wide-context-stage',
        motion: 'context-enter-spotlight-search-highlight-shift',
        novelty: 'context-theater',
        patterns: ['active-context', 'relevance'],
        primitives: ['word-stage', 'spotlight', 'focus-rings'],
        transitionIn: ['stage-open', 'context-lines'],
        transitionOut: ['focused-words', 'spotlight-wipe'],
        camera: 'wide-stage-pan',
        direction: 'mixed',
        energy: 'calm',
        density: 'dense',
        complexity: 'medium',
      },
    ],
  },
  {
    family: 'learning-update',
    tags: ['learning', 'update', 'feedback', 'new-information', 'knowledge', 'adapt'],
    variants: [
      {
        slug: 'knowledge-tree-graft',
        title: 'Knowledge Tree Graft',
        description: 'New verified information is grafted onto a knowledge tree, while outdated branches are marked and safely superseded rather than silently erased.',
        layout: 'versioned-knowledge-tree',
        motion: 'new-fact-arrive-verify-graft-old-mark-supersede',
        novelty: 'versioned-learning-tree',
        patterns: ['knowledge-update', 'supersession'],
        primitives: ['tree', 'fact-leaves', 'version-tags'],
        transitionIn: ['new-fact-orbit', 'tree-focus'],
        transitionOut: ['updated-branch', 'revision-pulse'],
        camera: 'slow-tree-orbit',
        direction: 'center-out',
        energy: 'measured',
        density: 'dense',
        complexity: 'high',
        status: 'prototype',
      },
      {
        slug: 'belief-ledger-revision',
        title: 'Belief Ledger Revision',
        description: 'Facts enter a versioned ledger where confidence, source quality, and recency determine whether they append, challenge, or supersede existing knowledge.',
        layout: 'ledger-with-version-columns',
        motion: 'fact-enter-score-compare-append-supersede',
        novelty: 'knowledge-ledger',
        patterns: ['fact-update', 'confidence'],
        primitives: ['ledger-rows', 'confidence-bars', 'source-stamps'],
        transitionIn: ['fact-card', 'ledger-open'],
        transitionOut: ['revision-stamp', 'row-highlight'],
        camera: 'top-down-ledger',
        direction: 'top-to-bottom',
        energy: 'calm',
        density: 'dense',
        complexity: 'medium',
      },
      {
        slug: 'feedback-weight-tuning',
        title: 'Feedback Weight Tuning',
        description: 'User and render feedback move visible scoring weights, changing which animation candidates rise in future selections.',
        layout: 'weight-console-candidate-field',
        motion: 'feedback-arrive-weights-shift-candidates-reorder',
        novelty: 'creative-brain-tuning',
        patterns: ['learning-from-feedback', 'selection-update'],
        primitives: ['weight-sliders', 'feedback-cards', 'candidate-nodes'],
        transitionIn: ['feedback-drop', 'console-wake'],
        transitionOut: ['new-ranking', 'selected-candidate'],
        camera: 'isometric-console',
        direction: 'mixed',
        energy: 'dynamic',
        density: 'dense',
        complexity: 'high',
      },
      {
        slug: 'stale-fact-renewal-cycle',
        title: 'Stale Fact Renewal Cycle',
        description: 'Knowledge cards age visibly, trigger a refresh check, and either renew with evidence or retire when newer information is stronger.',
        layout: 'circular-fact-lifecycle',
        motion: 'fact-age-refresh-search-renew-or-retire',
        novelty: 'fact-lifecycle',
        patterns: ['freshness', 'knowledge-maintenance'],
        primitives: ['fact-cards', 'age-rings', 'refresh-pulse'],
        transitionIn: ['fact-card', 'clock-ring'],
        transitionOut: ['renewed-card', 'retired-dissolve'],
        camera: 'top-down-cycle',
        direction: 'circular',
        energy: 'measured',
        density: 'balanced',
        complexity: 'medium',
      },
    ],
  },
];

const DEFAULT_AVOID = ['when the spoken sentence has no semantic relation to this visual family'];

const entries: AnimationLibraryEntry[] = FAMILY_SEEDS.flatMap((familySeed) =>
  familySeed.variants.map((variant, variantIndex) => ({
    animationId: `${familySeed.family}-${variant.slug}-v1`,
    version: 1,
    title: variant.title,
    description: variant.description,
    status: variant.status ?? 'concept',
    visualFamily: familySeed.family,
    layoutFamily: variant.layout,
    motionSignature: variant.motion,
    noveltyGroup: variant.novelty,
    semanticTags: [...new Set([...familySeed.tags, ...variant.patterns])],
    explanationPatterns: variant.patterns,
    avoidWhen: variant.avoidWhen ?? DEFAULT_AVOID,
    primitiveTags: variant.primitives,
    transitionInTags: variant.transitionIn,
    transitionOutTags: variant.transitionOut,
    cameraStyle: variant.camera,
    primaryDirection: variant.direction,
    energy: variant.energy,
    density: variant.density,
    complexity: variant.complexity,
    durationSeconds: {
      min: variant.complexity === 'low' ? 2.4 : 3.2,
      max: variant.complexity === 'high' ? 8.5 : 6.5,
    },
    qualityPrior: {
      semanticClarity: variant.clarity ?? 78 + (variantIndex % 3) * 4,
      novelty: variant.noveltyScore ?? 84 + ((variantIndex + 1) % 4) * 3,
      productionConfidence:
        variant.confidence ?? (variant.status === 'prototype' ? 64 : 42),
    },
  })),
);

export const ANIMATION_LIBRARY = animationLibraryDocumentSchema.parse({
  version: 1,
  updatedAt: '2026-08-04T10:24:00.000Z',
  entries,
});

export const ANIMATION_LIBRARY_ENTRIES = ANIMATION_LIBRARY.entries;

export const getAnimationLibraryEntry = (
  animationId: string,
): AnimationLibraryEntry | undefined =>
  ANIMATION_LIBRARY_ENTRIES.find((entry) => entry.animationId === animationId);

export const getAnimationFamilyEntries = (
  visualFamily: string,
): AnimationLibraryEntry[] =>
  ANIMATION_LIBRARY_ENTRIES.filter(
    (entry) => entry.visualFamily === visualFamily,
  );
