import React from 'react';
import {AbsoluteFill,Easing,Sequence,interpolate,spring,useCurrentFrame,useVideoConfig} from 'remotion';
import {BRAND} from '../../../brand/brand';
import {CameraStage} from '../../animation-library/creativeMotionPrimitives';
import {AIModelChip,IconTile,SemanticIcon,ServerStack,TerminalMock} from '../../visual-system/SemanticVisualKit';
import {BrandAnchor,InfoChip,KineticConnector,SceneBackdrop,TechIcon,type TechIconName} from '../../visual-system/TechVisualKit';
import {REEL_CAPTION_SAFE} from '../captionSafe';
import {CLAUDE_OPUS55_SCENES,CLAUDE_OPUS55_SUBTITLES,type ClaudeOpus55Cue,type ClaudeOpus55Scene} from './contract';

const GOOD='#2B8A68';const RISK='#B5415C';const GOLD='#D29A2E';
const clamp=(v:number)=>Math.max(0,Math.min(1,v));
const ease=(frame:number,from:number,to:number)=>interpolate(frame,[from,Math.max(from+1,to)],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.bezier(.16,1,.3,1)});
const sceneIcon=(icon:string):TechIconName=>(['zap','code','gauge','terminal','search','workflow','sparkles'].includes(icon)?icon:'sparkles') as TechIconName;

const Header:React.FC<{scene:ClaudeOpus55Scene}>=({scene})=>{const frame=useCurrentFrame();const {fps}=useVideoConfig();const enter=spring({frame,fps,config:{damping:18,stiffness:150,mass:.75}});return <div style={{position:'absolute',left:60,right:60,top:70,zIndex:80,display:'flex',alignItems:'center',justifyContent:'center',gap:15,opacity:enter,transform:`translateY(${(1-enter)*-18}px)`}}><div style={{width:58,height:58,borderRadius:19,display:'flex',alignItems:'center',justifyContent:'center',background:BRAND.ink,color:'#fff',boxShadow:'0 15px 38px rgba(26,26,46,.2)'}}><TechIcon name={sceneIcon(scene.icon)} size={32} color="#fff"/></div><div style={{fontSize:scene.headline.length>27?37:43,lineHeight:1.02,fontWeight:950,letterSpacing:-1.2,color:BRAND.ink,textAlign:'center'}}>{scene.headline}</div></div>};

const CaptionLayer:React.FC<{showCaptions:boolean}>=({showCaptions})=>{const frame=useCurrentFrame();if(!showCaptions)return null;const cue=CLAUDE_OPUS55_SUBTITLES.find(c=>frame>=c.startFrame&&frame<c.endFrame) as ClaudeOpus55Cue|undefined;if(!cue)return null;const words=cue.text.split(/\s+/).filter(Boolean);const local=clamp((frame-cue.startFrame)/Math.max(1,cue.endFrame-cue.startFrame));const active=Math.min(words.length-1,Math.floor(local*words.length));return <div style={{position:'absolute',left:REEL_CAPTION_SAFE.horizontalInset,right:REEL_CAPTION_SAFE.horizontalInset,bottom:REEL_CAPTION_SAFE.bottom,zIndex:300,display:'flex',justifyContent:'center'}}><div style={{maxWidth:REEL_CAPTION_SAFE.maxWidth,textAlign:'center',fontSize:48,lineHeight:1.08,fontWeight:950,letterSpacing:-1.25,color:BRAND.ink}}>{words.map((w,i)=><React.Fragment key={`${w}-${i}`}><span style={{color:i===active?BRAND.accentDk:BRAND.ink}}>{w}</span>{i<words.length-1?' ':''}</React.Fragment>)}</div></div>};

const CostBlock:React.FC<{x:number;y:number;delay?:number}>=({x,y,delay=0})=>{const frame=useCurrentFrame();const {fps}=useVideoConfig();const enter=spring({frame:Math.max(0,frame-delay),fps,config:{damping:12,stiffness:200,mass:.8}});return <div style={{position:'absolute',left:x,top:y,width:430,height:240,borderRadius:42,background:'linear-gradient(145deg,#171421,#35224F)',border:'4px solid rgba(185,140,255,.65)',boxShadow:'0 36px 110px rgba(26,26,46,.34)',color:'#fff',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',transform:`translateY(${(1-enter)*-120}px) rotate(${(1-enter)*-5}deg) scale(${.82+.18*enter})`,opacity:enter,zIndex:35}}><div style={{fontSize:88,fontWeight:1000,letterSpacing:-4,color:'#D8C1FF'}}>−40 %</div><div style={{fontSize:25,fontWeight:900,letterSpacing:.5}}>TYPISCHE KOSTEN</div></div>};

const HookScene:React.FC=()=>{const frame=useCurrentFrame();const oldOut=ease(frame,25,92);return <CameraStage mode="push" startFrame={0} endFrame={170} intensity={.85}><SceneBackdrop intensity={1.05}/><BrandAnchor brand="claude" x={58} y={174} accent delay={0}/><InfoChip label="NEUES SPITZENMODELL" icon="zap" x={648} y={176} width={370} accent delay={5}/><div style={{position:'absolute',left:70-oldOut*240,top:520,width:310,height:180,borderRadius:38,background:'#fff',border:'3px solid rgba(181,65,92,.25)',boxShadow:'0 20px 55px rgba(26,26,46,.12)',display:'flex',alignItems:'center',justifyContent:'center',gap:14,opacity:1-oldOut*.78,transform:`rotate(${-6-oldOut*8}deg)`}}><SemanticIcon name="cpu" size={48} color={RISK}/><div style={{fontSize:39,fontWeight:950,color:RISK}}>OPUS 5</div></div><AIModelChip label="OPUS 5.5" x={300} y={450} width={620} height={280} delay={4} status="NEW"/><CostBlock x={325} y={790} delay={18}/><IconTile name="rocket" label="MEHR TEMPO" x={130} y={1080} size={180} delay={72} strong/><IconTile name="cpu" label="FRONTIER" x={450} y={1110} size={170} delay={86}/><IconTile name="check" label="FABLE ≈" x={770} y={1080} size={180} delay={100}/></CameraStage>};

const CompareScene:React.FC=()=>{const frame=useCurrentFrame();const close=ease(frame,30,110);return <CameraStage mode="pan-right" startFrame={0} endFrame={170} intensity={.55}><SceneBackdrop intensity={.85}/><BrandAnchor brand="claude" x={58} y={178} compact delay={2}/><AIModelChip label="OPUS 5.5" x={60+close*55} y={500} width={440} height={230} delay={8}/><AIModelChip label="FABLE 5.1" x={580-close*55} y={500} width={440} height={230} delay={18}/><div style={{position:'absolute',left:420,top:785,width:240,height:160,borderRadius:80,background:BRAND.ink,color:'#fff',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',boxShadow:'0 28px 75px rgba(26,26,46,.25)',transform:`scale(${.82+.18*ease(frame,50,95)})`}}><div style={{fontSize:70,fontWeight:1000}}>≈</div><div style={{fontSize:20,fontWeight:900}}>MOST WORK</div></div><KineticConnector from={{x:340,y:780}} to={{x:540,y:850}} startFrame={35} endFrame={90} width={7}/><KineticConnector from={{x:740,y:780}} to={{x:540,y:850}} startFrame={42} endFrame={98} width={7}/><IconTile name="cpu" label="LEISTUNG" x={175} y={1050} size={180} delay={78}/><IconTile name="check" label="ÄHNLICH" x={725} y={1050} size={180} delay={92} strong/></CameraStage>};

const PriceSlab:React.FC<{x:number;y:number;oldPrice:string;newPrice:string;label:string;delay:number}>=({x,y,oldPrice,newPrice,label,delay})=>{const frame=useCurrentFrame();const p=ease(frame,delay,delay+70);return <div style={{position:'absolute',left:x,top:y,width:390,height:360,borderRadius:42,background:'linear-gradient(155deg,#fff,#F0E7FF)',border:'3px solid rgba(110,69,201,.22)',boxShadow:'0 30px 90px rgba(26,26,46,.16)',overflow:'hidden'}}><div style={{position:'absolute',left:32,top:28,fontSize:24,fontWeight:950,color:BRAND.accentDk}}>{label}</div><div style={{position:'absolute',left:45,top:100,fontSize:66,fontWeight:950,color:RISK,opacity:1-p,transform:`translateY(${-p*55}px) scale(${1-p*.18})`,textDecoration:'line-through'}}>{oldPrice}</div><div style={{position:'absolute',left:45,top:165,fontSize:108,fontWeight:1000,color:BRAND.ink,letterSpacing:-4,transform:`translateY(${(1-p)*90}px) scale(${.75+.25*p})`,opacity:p}}>{newPrice}</div><div style={{position:'absolute',right:28,bottom:28,width:82,height:82,borderRadius:24,background:BRAND.ink,display:'flex',alignItems:'center',justifyContent:'center'}}><SemanticIcon name="api" size={44} color="#B98CFF"/></div></div>};

const PricingScene:React.FC=()=>{const frame=useCurrentFrame();return <CameraStage mode="push" startFrame={0} endFrame={170} intensity={.5}><SceneBackdrop intensity={.76}/><BrandAnchor brand="claude" x={58} y={178} compact delay={2}/><InfoChip label="PRO 1M TOKENS" icon="code" x={730} y={180} width={285} delay={8}/><PriceSlab x={110} y={510} oldPrice="$5" newPrice="$4" label="INPUT" delay={20}/><PriceSlab x={580} y={510} oldPrice="$25" newPrice="$20" label="OUTPUT" delay={42}/><div style={{position:'absolute',left:120,top:1010,width:840,height:150,borderRadius:38,background:BRAND.ink,color:'#fff',display:'flex',alignItems:'center',justifyContent:'space-around',boxShadow:'0 26px 76px rgba(26,26,46,.25)',opacity:ease(frame,70,115)}}><div style={{display:'flex',alignItems:'center',gap:14}}><SemanticIcon name="database" size={42} color="#B98CFF"/><span style={{fontSize:27,fontWeight:950}}>INPUT ↓</span></div><div style={{width:3,height:70,background:'rgba(255,255,255,.18)'}}/><div style={{display:'flex',alignItems:'center',gap:14}}><SemanticIcon name="api" size={42} color="#B98CFF"/><span style={{fontSize:27,fontWeight:950}}>OUTPUT ↓</span></div></div></CameraStage>};

const SpeedScene:React.FC=()=>{const frame=useCurrentFrame();const fast=ease(frame,38,118);const slow=ease(frame,38,150);return <CameraStage mode="parallax" startFrame={0} endFrame={170} intensity={.55}><SceneBackdrop intensity={.9}/><BrandAnchor brand="claude" x={58} y={178} compact delay={2}/><ServerStack x={90} y={500} width={360} rows={4} delay={8}/><div style={{position:'absolute',left:500,top:510,fontSize:23,fontWeight:950,color:BRAND.ink}}>OPUS 5</div><div style={{position:'absolute',left:500,top:720,fontSize:23,fontWeight:950,color:BRAND.accentDk}}>OPUS 5.5</div><div style={{position:'absolute',left:500,top:565,width:450,height:18,borderRadius:18,background:'rgba(181,65,92,.12)'}}/><div style={{position:'absolute',left:500,top:775,width:450,height:18,borderRadius:18,background:'rgba(110,69,201,.12)'}}/>{[0,1,2].map(i=><div key={`s${i}`} style={{position:'absolute',left:500+slow*(260+i*45),top:535+i*22,width:92,height:54,borderRadius:17,background:'#F6E6EA',border:'2px solid rgba(181,65,92,.18)',opacity:ease(frame,20+i*10,50+i*10)}}/>)}{[0,1,2].map(i=><div key={`f${i}`} style={{position:'absolute',left:500+fast*(360+i*42),top:745+i*22,width:92,height:54,borderRadius:17,background:'#E9DCFF',border:'2px solid rgba(110,69,201,.25)',opacity:ease(frame,18+i*8,46+i*8),boxShadow:'0 12px 30px rgba(110,69,201,.12)'}}/>)}<div style={{position:'absolute',left:530,top:970,width:420,height:230,borderRadius:44,background:BRAND.ink,color:'#fff',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',boxShadow:'0 32px 100px rgba(26,26,46,.3)',transform:`scale(${.82+.18*ease(frame,68,115)})`,opacity:ease(frame,60,92)}}><div style={{fontSize:82,fontWeight:1000,color:'#D8C1FF'}}>&gt;30 %</div><div style={{fontSize:25,fontWeight:950}}>SCHNELLERE AUSGABE</div></div><IconTile name="rocket" label="OUTPUT" x={120} y={1080} size={170} delay={95} strong/></CameraStage>};

const CodingScene:React.FC=()=>{const frame=useCurrentFrame();const active=frame<65?0:frame<115?1:2;return <CameraStage mode="push" startFrame={0} endFrame={170} intensity={.6}><SceneBackdrop intensity={.72}/><BrandAnchor brand="claude" x={58} y={178} compact delay={2}/><TerminalMock x={150} y={430} width={780} height={480} delay={8} activeLine={active} lines={['claude migrate --codebase','claude audit --all','claude agent --workflow']}/><IconTile name="code" label="MIGRATION" x={120} y={1030} size={190} delay={60}/><IconTile name="shield" label="AUDIT" x={445} y={1070} size={190} delay={82} strong/><IconTile name="boxes" label="AGENTEN" x={770} y={1030} size={190} delay={104}/><AIModelChip label="OPUS 5.5" x={650} y={300} width={330} height={150} delay={32} status="CODING"/></CameraStage>};

const EvidenceScene:React.FC=()=>{const frame=useCurrentFrame();const focus=ease(frame,35,115);return <CameraStage mode="pull" startFrame={0} endFrame={170} intensity={.58}><SceneBackdrop intensity={.7}/><BrandAnchor brand="claude" x={58} y={178} compact delay={2}/><div style={{position:'absolute',left:100,top:480,width:380,height:250,borderRadius:42,background:BRAND.ink,color:'#fff',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',gap:20,boxShadow:'0 28px 80px rgba(26,26,46,.25)',transform:`translateX(${(1-focus)*-90}px)`,opacity:ease(frame,10,45)}}><SemanticIcon name="shield" size={68} color="#B98CFF"/><div style={{fontSize:32,fontWeight:950,textAlign:'center'}}>ANTHROPIC<br/>TESTS</div></div><div style={{position:'absolute',left:600,top:480,width:380,height:250,borderRadius:42,background:'#fff',color:BRAND.ink,border:'3px solid rgba(110,69,201,.24)',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',gap:20,boxShadow:'0 28px 80px rgba(26,26,46,.16)',transform:`translateX(${(1-focus)*90}px)`,opacity:ease(frame,22,56)}}><SemanticIcon name="check" size={68} color={BRAND.accentDk}/><div style={{fontSize:32,fontWeight:950,textAlign:'center'}}>PARTNER<br/>EVALS</div></div><div style={{position:'absolute',left:355,top:790,width:370,height:370,borderRadius:'50%',border:'18px solid rgba(110,69,201,.22)',boxShadow:'0 30px 80px rgba(26,26,46,.14)',transform:`scale(${.72+.28*focus})`,display:'flex',alignItems:'center',justifyContent:'center'}}><div style={{width:230,height:230,borderRadius:'50%',background:'rgba(255,255,255,.94)',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',gap:14}}><SemanticIcon name="alert" size={62} color={GOLD}/><div style={{fontSize:34,fontWeight:1000,color:BRAND.ink}}>KONTEXT</div></div></div><div style={{position:'absolute',left:665,top:1065,width:250,height:28,borderRadius:18,background:BRAND.accentDk,transform:`rotate(38deg) scaleX(${focus})`,transformOrigin:'left center'}}/></CameraStage>};

const VerdictPillar:React.FC<{x:number;label:string;sub:string;icon:'server'|'rocket'|'check';delay:number;strong?:boolean}>=({x,label,sub,icon,delay,strong=false})=>{const frame=useCurrentFrame();const p=ease(frame,delay,delay+45);return <div style={{position:'absolute',left:x,top:840+(1-p)*80,width:260,height:320,borderRadius:42,background:strong?BRAND.ink:'#fff',color:strong?'#fff':BRAND.ink,border:'3px solid rgba(110,69,201,.22)',boxShadow:'0 28px 80px rgba(26,26,46,.18)',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',gap:22,opacity:p}}><SemanticIcon name={icon} size={62} color={strong?'#D8C1FF':BRAND.accentDk}/><div style={{fontSize:40,fontWeight:1000}}>{label}</div><div style={{fontSize:21,fontWeight:850,opacity:.72,textAlign:'center'}}>{sub}</div></div>};

const VerdictScene:React.FC=()=>{const frame=useCurrentFrame();return <CameraStage mode="pull" startFrame={0} endFrame={170} intensity={.65}><SceneBackdrop intensity={.9}/><BrandAnchor brand="claude" x={58} y={178} compact delay={2}/><AIModelChip label="OPUS 5.5" x={255} y={420} width={570} height={260} delay={8} status="VERDICT"/><VerdictPillar x={80} label="KOSTEN ↓" sub="40 % typisch" icon="server" delay={38}/><VerdictPillar x={410} label="TEMPO ↑" sub=">30 % Output" icon="rocket" delay={58} strong/><VerdictPillar x={740} label="FABLE ≈" sub="most work" icon="check" delay={78}/><div style={{position:'absolute',left:180,top:1240,width:720,height:104,borderRadius:32,background:'linear-gradient(90deg,#6E45C9,#1A1A2E)',color:'#fff',display:'flex',alignItems:'center',justifyContent:'center',gap:18,boxShadow:'0 24px 70px rgba(26,26,46,.25)',opacity:ease(frame,105,145),transform:`translateY(${(1-ease(frame,105,145))*35}px)`}}><TechIcon name="terminal" size={42} color="#fff"/><span style={{fontSize:31,fontWeight:1000}}>SEHR SPANNEND FÜR CODING</span></div></CameraStage>};

const visualByScene:Record<string,React.FC>={'claude55-01':HookScene,'claude55-02':CompareScene,'claude55-03':PricingScene,'claude55-04':SpeedScene,'claude55-05':CodingScene,'claude55-06':EvidenceScene,'claude55-07':VerdictScene};

export const ReelClaudeOpus55:React.FC<{showCaptions?:boolean}>=({showCaptions=true})=><AbsoluteFill style={{background:'#fff',fontFamily:'Inter,Arial,sans-serif',overflow:'hidden'}}>{CLAUDE_OPUS55_SCENES.map(scene=>{const Visual=visualByScene[scene.sceneId];return <Sequence key={scene.sceneId} from={scene.startFrame} durationInFrames={scene.endFrame-scene.startFrame}><AbsoluteFill><Visual/><Header scene={scene}/></AbsoluteFill></Sequence>})}<CaptionLayer showCaptions={showCaptions}/></AbsoluteFill>;
