import type {AuthoredVisualScene} from '../../animation-library/authoredProductionGate';

export const CLAUDE_OPUS55_VISUAL_PROFILES: readonly AuthoredVisualScene[] = [
  {sceneId:'claude55-01',visualId:'claude55-cost-impact-v1',fingerprint:{primaryPrimitive:'object',cameraMotion:'push',depthStyle:'pseudo-3d',entryMechanism:'assemble',medium:'remotion-native',direction:'center-out',visualFamily:'model-cost-impact',layoutFamily:'hero-chip-cost-slam',motionSignature:'old-chip-eject-new-chip-dock-cost-slam'}},
  {sceneId:'claude55-02',visualId:'claude55-fable-compare-v1',fingerprint:{primaryPrimitive:'mixed',cameraMotion:'pan',depthStyle:'layered-2d',entryMechanism:'slide',medium:'remotion-native',direction:'outside-in',visualFamily:'model-comparison',layoutFamily:'dual-model-balance',motionSignature:'chips-enter-gap-close-equality-lock'}},
  {sceneId:'claude55-03',visualId:'claude55-price-transform-v1',fingerprint:{primaryPrimitive:'object',cameraMotion:'push',depthStyle:'pseudo-3d',entryMechanism:'assemble',medium:'remotion-native',direction:'left-to-right',visualFamily:'price-transformation',layoutFamily:'dual-price-slabs',motionSignature:'old-price-recede-new-price-snap-arrows'}},
  {sceneId:'claude55-04',visualId:'claude55-speed-flow-v1',fingerprint:{primaryPrimitive:'nodes',cameraMotion:'parallax',depthStyle:'pseudo-3d',entryMechanism:'draw',medium:'remotion-native',direction:'left-to-right',visualFamily:'server-output-race',layoutFamily:'server-two-lanes',motionSignature:'servers-build-packets-race-speed-lock'}},
  {sceneId:'claude55-05',visualId:'claude55-coding-terminal-v1',fingerprint:{primaryPrimitive:'ui',cameraMotion:'push',depthStyle:'pseudo-3d',entryMechanism:'assemble',medium:'remotion-native',direction:'top-to-bottom',visualFamily:'coding-terminal',layoutFamily:'terminal-job-dock',motionSignature:'terminal-build-lines-highlight-icons-dock'}},
  {sceneId:'claude55-06',visualId:'claude55-evidence-zoom-v1',fingerprint:{primaryPrimitive:'mixed',cameraMotion:'pull',depthStyle:'layered-2d',entryMechanism:'draw',medium:'remotion-native',direction:'outside-in',visualFamily:'evidence-review',layoutFamily:'source-lens-split',motionSignature:'source-blocks-enter-lens-focus-context-warning'}},
  {sceneId:'claude55-07',visualId:'claude55-final-verdict-v1',fingerprint:{primaryPrimitive:'chart',cameraMotion:'pull',depthStyle:'pseudo-3d',entryMechanism:'assemble',medium:'remotion-native',direction:'center-out',visualFamily:'three-factor-verdict',layoutFamily:'model-three-pillars',motionSignature:'model-rise-pillars-lock-coding-dock-verdict'}}
] as const;
