import React from 'react';
import {interpolate,useCurrentFrame} from 'remotion';
import {AnswerCard,ProbabilityBar,PromptCard,ResultBadge,SceneShell,Stage,prog} from './components';
import {localAnswerBeat,localAnswerResult,type AnswerSceneId} from './sync';
import {answerPalette,answerShadows} from './style';
const bp=(scene:AnswerSceneId,beat:string,frame:number)=>prog(frame,localAnswerBeat(scene,beat),localAnswerResult(scene,beat));

export const Scene01SameQuestion:React.FC=()=>{const frame=useCurrentFrame();const question=bp('scene-01','s1-question',frame);const split=bp('scene-01','s1-split',frame);const topY=interpolate(split,[0,1],[0,-185]);const bottomY=interpolate(split,[0,1],[0,185]);return <SceneShell title="Gleiche Frage, andere Antwort?"><Stage emphasis={split}><PromptCard text="DIESELBE FRAGE" style={{position:'absolute',left:230,top:245,transform:`translateX(${interpolate(question,[0,1],[-260,0])}px) scale(${.9+question*.1})`}}/><div style={{position:'absolute',left:450,top:455,width:120,height:120,borderRadius:34,border:`5px solid ${answerPalette.accent}`,background:answerPalette.accentSoft,transform:'rotate(45deg)',boxShadow:answerShadows.accent,opacity:question}}/><svg viewBox="0 0 1010 760" style={{position:'absolute',inset:0,width:'100%',height:'100%'}}><path d="M510 470 C510 540 310 530 250 610" fill="none" stroke={answerPalette.accent} strokeWidth="16" strokeLinecap="round" opacity={split}/><path d="M510 470 C510 540 710 530 770 610" fill="none" stroke={answerPalette.danger} strokeWidth="16" strokeLinecap="round" opacity={split}/></svg><AnswerCard label="ANTWORT A" tone="success" opacity={split} style={{position:'absolute',left:80,top:520,transform:`translateY(${topY}px) scale(${.88+split*.12})`}}/><AnswerCard label="ANTWORT B" tone="accent" opacity={split} style={{position:'absolute',right:80,top:520,transform:`translateY(${bottomY}px) scale(${.88+split*.12})`}}/><ResultBadge text="GLEICHER START · ZWEI MÖGLICHE WEGE" visible={split} style={{position:'absolute',left:265,bottom:40}}/></Stage></SceneShell>;};

export const Scene02Probabilities:React.FC=()=>{const frame=useCurrentFrame();const options=bp('scene-02','s2-options',frame);const probs=bp('scene-02','s2-probabilities',frame);const words=['klar','direkt','präzise','einfach'];const values=[.76,.58,.42,.25];return <SceneShell title="Die KI bewertet mehrere nächste Wörter"><Stage emphasis={probs}><PromptCard text="Der nächste Begriff könnte …" style={{position:'absolute',left:245,top:70,transform:`scale(${.92+options*.08})`}}/><div style={{position:'absolute',left:150,right:150,top:300,display:'flex',flexDirection:'column',gap:28}}>{words.map((word,index)=><ProbabilityBar key={word} label={word.toUpperCase()} value={values[index]*options} active={index===0&&probs>.2} />)}</div><div style={{position:'absolute',left:80,right:80,bottom:70,height:8,background:`linear-gradient(90deg,transparent,${answerPalette.accent},transparent)`,opacity:probs}}/></Stage></SceneShell>;};

export const Scene03RandomChoice:React.FC=()=>{const frame=useCurrentFrame();const random=bp('scene-03','s3-random',frame);const branches=bp('scene-03','s3-branches',frame);const selectorX=interpolate(random,[0,1],[160,700]);const targets=[{x:180,y:520,c:answerPalette.success},{x:440,y:420,c:answerPalette.accent},{x:700,y:540,c:answerPalette.warning}];return <SceneShell title="Eine kleine Zufallskomponente wählt den Weg"><Stage emphasis={branches}><div style={{position:'absolute',left:475,top:95,width:74,height:74,borderRadius:'50%',background:answerPalette.accent,boxShadow:'0 0 54px rgba(109,58,219,.55)',transform:`translateX(${selectorX-475}px) scale(${.8+random*.2})`}}/><svg viewBox="0 0 1010 760" style={{position:'absolute',inset:0,width:'100%',height:'100%'}}>{targets.map((target,index)=><path key={index} d={`M510 170 C510 310 ${target.x} 320 ${target.x} ${target.y}`} fill="none" stroke={target.c} strokeWidth="15" strokeLinecap="round" strokeDasharray="620" strokeDashoffset={620*(1-branches)} opacity={.35+.65*branches}/>)}</svg>{targets.map((target,index)=><div key={index} style={{position:'absolute',left:target.x-70,top:target.y-70,width:140,height:140,borderRadius:34,border:`5px solid ${target.c}`,background:'white',boxShadow:answerShadows.card,opacity:branches,transform:`scale(${index===1?.9+branches*.2:.84+branches*.12})`}}/>)}<ResultBadge text="EIN WEG WIRD GEWÄHLT" visible={branches} style={{position:'absolute',left:345,bottom:48}}/></Stage></SceneShell>;};

export const Scene04Temperature:React.FC=()=>{const frame=useCurrentFrame();const high=bp('scene-04','s4-high',frame);const low=bp('scene-04','s4-low',frame);const value=Math.max(0,Math.min(1,high*(1-low)));const angle=-125+250*value;const spread=70+value*240;return <SceneShell title="Kreativität bestimmt die Streuung"><Stage emphasis={.45+value*.55}><div style={{position:'absolute',left:310,top:80,width:390,height:390,borderRadius:'50%',border:`18px solid ${answerPalette.line}`,background:'radial-gradient(circle,#fff 35%,#eee7f7 100%)',boxShadow:answerShadows.card}}><div style={{position:'absolute',left:188,top:188,width:150,height:16,borderRadius:99,background:answerPalette.accent,transformOrigin:'8px 8px',transform:`rotate(${angle}deg)`,boxShadow:'0 0 20px rgba(109,58,219,.4)'}}/><div style={{position:'absolute',left:158,top:158,width:74,height:74,borderRadius:'50%',background:answerPalette.foreground}}><div/></div><div style={{position:'absolute',left:90,right:90,bottom:42,textAlign:'center',fontSize:34,fontWeight:970,color:value>.5?answerPalette.danger:answerPalette.success}}>{value>.5?'HOCH':'NIEDRIG'}</div></div><div style={{position:'absolute',left:505,top:520}}>{[-1,0,1].map((n)=><div key={n} style={{position:'absolute',left:n*spread-95,width:190,height:130,borderRadius:32,border:`4px solid ${n===0?answerPalette.accent:answerPalette.line}`,background:n===0?answerPalette.accentSoft:'white',boxShadow:answerShadows.card,transform:`rotate(${n*value*8}deg)`}}/>)}</div><ResultBadge text={value>.5?'MEHR VARIANTEN':'STABILERE ANTWORT'} tone={value>.5?'danger':'success'} visible={Math.max(high,low)} style={{position:'absolute',left:350,bottom:38}}/></Stage></SceneShell>;};

export const Scene05WordingShift:React.FC=()=>{const frame=useCurrentFrame();const wording=bp('scene-05','s5-wording',frame);const shift=bp('scene-05','s5-shift',frame);return <SceneShell title="Schon ein kleines Wort verschiebt die Verteilung"><Stage emphasis={shift}><PromptCard text="Erkläre es KURZ" style={{position:'absolute',left:245,top:70,opacity:1-shift,transform:`translateY(${shift*-30}px)`}}/><PromptCard text="Erkläre es PRÄZISE" tone="dark" style={{position:'absolute',left:245,top:70,opacity:shift,transform:`translateY(${(1-shift)*30}px)`}}/><div style={{position:'absolute',left:150,right:150,top:320,display:'flex',flexDirection:'column',gap:34}}><ProbabilityBar label="KNAPP" value={(1-shift)*.82+shift*.36} active={shift<.5}/><ProbabilityBar label="DETAIL" value={(1-shift)*.34+shift*.88} active={shift>=.5}/><ProbabilityBar label="BEISPIEL" value={(1-shift)*.25+shift*.68} active={shift>=.5}/></div><div style={{position:'absolute',left:456,top:238,fontSize:70,fontWeight:970,color:answerPalette.accent,opacity:wording}}>↓</div></Stage></SceneShell>;};

export const Scene06Facts:React.FC=()=>{const frame=useCurrentFrame();const notWrong=bp('scene-06','s6-not-wrong',frame);const consistent=bp('scene-06','s6-consistent',frame);return <SceneShell title="Andere Formulierung heißt nicht automatisch falsch"><Stage emphasis={consistent}><AnswerCard label="FORMULIERUNG A" fact="Fakt: 42" tone="success" style={{position:'absolute',left:70,top:150,transform:`translateX(${interpolate(notWrong,[0,1],[-180,0])}px)`}}/><AnswerCard label="FORMULIERUNG B" fact="Fakt: 42" tone="accent" style={{position:'absolute',right:70,top:150,transform:`translateX(${interpolate(notWrong,[0,1],[180,0])}px)`}}/><div style={{position:'absolute',left:390,top:430,width:230,height:160,borderRadius:40,border:`6px solid ${answerPalette.success}`,background:answerPalette.successSoft,boxShadow:answerShadows.success,display:'flex',alignItems:'center',justifyContent:'center',fontSize:34,fontWeight:970,color:answerPalette.success,opacity:notWrong}}>FAKT 42</div><div style={{position:'absolute',left:280,right:280,bottom:70,height:20,borderRadius:99,background:answerPalette.success,transform:`scaleX(${consistent})`,boxShadow:'0 0 26px rgba(21,131,93,.35)'}}/><ResultBadge text="FAKTEN BLEIBEN GLEICH" tone="success" visible={consistent} style={{position:'absolute',left:350,bottom:25}}/></Stage></SceneShell>;};

export const Scene07StableSetup:React.FC=()=>{const frame=useCurrentFrame();const goal=bp('scene-07','s7-goal',frame);const settings=bp('scene-07','s7-settings',frame);const context=bp('scene-07','s7-context',frame);const modules=[['ZIEL',goal],['FORMAT',goal],['GRENZEN',goal],['EINSTELLUNGEN',settings],['AUSGANGSKONTEXT',context]] as const;return <SceneShell title="Stabile Antworten brauchen stabile Bedingungen"><Stage emphasis={context}><div style={{position:'absolute',left:175,right:175,top:65,bottom:65,display:'flex',flexDirection:'column',gap:22}}>{modules.map(([label,visible],index)=><div key={label} style={{height:112,borderRadius:32,border:`4px solid ${index>=3?answerPalette.success:answerPalette.accent}`,background:index>=3?answerPalette.successSoft:answerPalette.accentSoft,boxShadow:answerShadows.card,display:'flex',alignItems:'center',padding:'0 34px',fontSize:30,fontWeight:970,color:index>=3?answerPalette.success:answerPalette.accent,opacity:visible,transform:`translateX(${(1-visible)*(index%2===0?-100:100)}px) scale(${.92+visible*.08})`}}><span style={{width:52,height:52,borderRadius:18,background:index>=3?answerPalette.success:answerPalette.accent,color:'white',display:'flex',alignItems:'center',justifyContent:'center',marginRight:28}}>✓</span>{label}</div>)}</div></Stage></SceneShell>;};

export const Scene08Compare:React.FC=()=>{const frame=useCurrentFrame();const compare=bp('scene-08','s8-compare',frame);const normal=bp('scene-08','s8-normal',frame);const warning=bp('scene-08','s8-warning',frame);return <SceneShell title="Vergleiche Formulierungen und prüfe die Fakten"><Stage emphasis={warning}><AnswerCard label="ANTWORT A" fact="Wortlaut anders · Fakt 42" tone="success" style={{position:'absolute',left:70,top:145,transform:`translateX(${interpolate(compare,[0,1],[-180,0])}px)`}}/><AnswerCard label="ANTWORT B" fact="Anders erklärt · Fakt 42" tone="success" style={{position:'absolute',right:70,top:145,transform:`translateX(${interpolate(compare,[0,1],[180,0])}px)`}}/><div style={{position:'absolute',left:180,right:180,top:440,height:130,borderRadius:38,border:`5px solid ${answerPalette.success}`,background:answerPalette.successSoft,display:'flex',alignItems:'center',justifyContent:'center',fontSize:34,fontWeight:970,color:answerPalette.success,opacity:normal}}>FORMULIERUNG ANDERS · FAKT GLEICH</div><div style={{position:'absolute',left:235,right:235,bottom:58,height:120,borderRadius:36,border:`5px solid ${answerPalette.danger}`,background:answerPalette.dangerSoft,display:'flex',alignItems:'center',justifyContent:'center',fontSize:30,fontWeight:970,color:answerPalette.danger,opacity:warning,transform:`scale(${.9+warning*.1})`,boxShadow:answerShadows.danger}}>WIDERSPRUCH = WARNSIGNAL</div></Stage></SceneShell>;};

export const ANSWER_SCENE_COMPONENTS={'scene-01':Scene01SameQuestion,'scene-02':Scene02Probabilities,'scene-03':Scene03RandomChoice,'scene-04':Scene04Temperature,'scene-05':Scene05WordingShift,'scene-06':Scene06Facts,'scene-07':Scene07StableSetup,'scene-08':Scene08Compare} satisfies Record<AnswerSceneId,React.FC>;
