import React from 'react';
import {MessageCircle,Search,Send,ShieldCheck,Sparkles} from 'lucide-react';
import {AbsoluteFill,Html5Audio,Sequence,interpolate,useCurrentFrame} from 'remotion';
import {BRAND} from '../../../brand/brand';
import {REEL_CAPTION_GLASS_STYLE,REEL_CAPTION_WRAPPER_STYLE} from '../captionSafe';
import {APPLE_MESSAGES_SCENES,APPLE_MESSAGES_SUBTITLES,MESSAGES_PALETTE as C,type MessagesCue,type MessagesScene} from './contract';
import {ApprovalVisual,ConnectVisual,DraftVisual,SearchVisual,WorkflowVisual} from './Visuals';

const visualByScene:Record<MessagesScene['sceneId'],React.FC>={scene1:ConnectVisual,scene2:SearchVisual,scene3:DraftVisual,scene4:ApprovalVisual,scene5:WorkflowVisual};
const iconByScene:Record<MessagesScene['sceneId'],React.ReactNode>={scene1:<MessageCircle size={32}/>,scene2:<Search size={32}/>,scene3:<Sparkles size={32}/>,scene4:<ShieldCheck size={32}/>,scene5:<Send size={32}/>};

const Header:React.FC<{scene:MessagesScene}>=({scene})=>{const f=useCurrentFrame();const a=interpolate(f,[0,12],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});return <div style={{position:'absolute',left:58,right:58,top:112,zIndex:120,display:'flex',justifyContent:'center',opacity:a,transform:`translateY(${(1-a)*-14}px)`}}><div style={{display:'inline-flex',alignItems:'center',gap:14,padding:'10px 18px 10px 12px',borderRadius:25,background:'rgba(255,255,255,.82)',border:'1px solid rgba(255,255,255,.74)',boxShadow:'0 12px 34px rgba(16,32,51,.10)',backdropFilter:'blur(12px)',WebkitBackdropFilter:'blur(12px)'}}><div style={{width:58,height:58,borderRadius:19,display:'grid',placeItems:'center',background:scene.surface,color:scene.accent}}>{iconByScene[scene.sceneId]}</div><div style={{fontFamily:BRAND.font,fontSize:scene.headline.length>26?37:42,fontWeight:950,letterSpacing:-1.3,color:C.ink,textAlign:'center'}}>{scene.headline}</div></div></div>};

const activeIndex=(frame:number,cue:MessagesCue,words:string[])=>{if(cue.words?.length===words.length){const i=cue.words.findIndex(w=>frame>=w.startFrame&&frame<w.endFrame);if(i>=0)return i;}const progress=(frame-cue.startFrame)/Math.max(1,cue.endFrame-cue.startFrame);return Math.min(words.length-1,Math.max(0,Math.floor(progress*words.length)));};
const Captions:React.FC=()=>{const f=useCurrentFrame();const cue=APPLE_MESSAGES_SUBTITLES.find(c=>f>=c.startFrame&&f<c.endFrame);if(!cue)return null;const scene=APPLE_MESSAGES_SCENES.find(s=>s.sceneId===cue.sceneId);const words=cue.words?.length?cue.words.map(w=>w.text):cue.text.trim().split(/\s+/);const active=activeIndex(f,cue,words);const alpha=Math.min(interpolate(f,[cue.startFrame,cue.startFrame+3],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}),interpolate(f,[cue.endFrame-3,cue.endFrame],[1,0],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}));return <div style={{...REEL_CAPTION_WRAPPER_STYLE,opacity:alpha}}><div style={{...REEL_CAPTION_GLASS_STYLE,fontFamily:BRAND.font,fontSize:43,fontWeight:880,lineHeight:1.16,letterSpacing:-.55,color:C.ink,textShadow:'0 1px 2px rgba(255,255,255,.5)'}}>{words.map((w,i)=><React.Fragment key={`${cue.id}-${i}`}><span style={{display:'inline-block',color:i===active?(scene?.accent??C.purple):C.ink,transform:`scale(${i===active?1.045:1})`}}>{w}</span>{i<words.length-1?' ':null}</React.Fragment>)}</div></div>};

const SceneLayer:React.FC<{scene:MessagesScene}>=({scene})=>{const Visual=visualByScene[scene.sceneId];return <AbsoluteFill><Visual/><Header scene={scene}/></AbsoluteFill>};
export type ReelChatGPTAppleMessagesProps={voiceoverSrc?:string;showCaptions?:boolean};
export const ReelChatGPTAppleMessages:React.FC<ReelChatGPTAppleMessagesProps>=({voiceoverSrc,showCaptions=true})=>{if(!voiceoverSrc)throw new Error('KI-ChatGPTAppleMessages requires a verified local voiceoverSrc. Run prepare-reel-render.mjs before production render.');return <AbsoluteFill style={{background:C.cloud,color:C.ink,fontFamily:BRAND.font,overflow:'hidden'}}>{APPLE_MESSAGES_SCENES.map(scene=><Sequence key={scene.sceneId} from={scene.startFrame} durationInFrames={scene.endFrame-scene.startFrame} name={`APPLE-MESSAGES-${scene.sceneId}`}><SceneLayer scene={scene}/></Sequence>)}<Html5Audio src={voiceoverSrc}/>{showCaptions?<Captions/>:null}</AbsoluteFill>};
