import React,{type CSSProperties} from 'react';
import {ArrowRight,BriefcaseBusiness,Check,CheckCircle2,Code2,LockKeyhole,MessageCircle,Monitor,Search,Send,ShieldCheck,Sparkles,UserCheck} from 'lucide-react';
import {AbsoluteFill,interpolate,spring,useCurrentFrame,useVideoConfig} from 'remotion';
import {MESSAGES_PALETTE as C} from './contract';

const p=(f:number,a:number,b:number)=>interpolate(f,[a,b],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});
const pop=(frame:number,delay=0)=>{const {fps}=useVideoConfig();return spring({frame:Math.max(0,frame-delay),fps,config:{damping:18,stiffness:150,mass:.75}})};
const Panel:React.FC<{children:React.ReactNode;style?:CSSProperties}>=({children,style})=><div style={{background:'rgba(255,255,255,.94)',border:'1px solid rgba(16,32,51,.10)',borderRadius:34,boxShadow:'0 26px 74px rgba(16,32,51,.14)',...style}}>{children}</div>;
const Chip:React.FC<{children:React.ReactNode;bg?:string;color?:string;style?:CSSProperties}>=({children,bg=C.white,color=C.ink,style})=><div style={{display:'inline-flex',alignItems:'center',gap:9,padding:'11px 16px',borderRadius:999,background:bg,color,fontWeight:850,fontSize:24,boxShadow:'0 10px 26px rgba(16,32,51,.08)',...style}}>{children}</div>;
const Bubble:React.FC<{children:React.ReactNode;side?:'left'|'right';accent?:string;style?:CSSProperties}>=({children,side='left',accent=C.blue,style})=><div style={{alignSelf:side==='right'?'flex-end':'flex-start',maxWidth:'84%',padding:'17px 21px',borderRadius:side==='right'?'23px 23px 7px 23px':'23px 23px 23px 7px',background:side==='right'?accent:C.white,color:side==='right'?C.white:C.ink,border:side==='left'?'1px solid rgba(16,32,51,.08)':'none',boxShadow:'0 10px 24px rgba(16,32,51,.09)',fontSize:26,lineHeight:1.25,fontWeight:700,...style}}>{children}</div>;
const DotBg:React.FC<{accent:string}>=({accent})=><AbsoluteFill style={{background:`radial-gradient(circle at 18% 18%, ${accent}26 0 150px, transparent 151px), radial-gradient(circle at 88% 26%, #FFFFFF 0 190px, transparent 191px), linear-gradient(160deg,#FCFEFF 0%,#F5F8FC 58%,#EEF3F8 100%)`}}/>;

export const ConnectVisual:React.FC=()=>{const f=useCurrentFrame();const link=p(f,28,62);const badge=p(f,68,88);return <AbsoluteFill><DotBg accent={C.cyan}/><div style={{position:'absolute',left:58,right:58,top:270,height:870,display:'grid',gridTemplateColumns:'1fr 130px 1fr',alignItems:'center'}}>
  <Panel style={{height:680,padding:30,transform:`translateX(${(1-p(f,0,20))*-55}px)`,opacity:p(f,0,16)}}><div style={{display:'flex',alignItems:'center',gap:14,fontSize:34,fontWeight:950}}><Sparkles size={35}/>ChatGPT</div><div style={{marginTop:56,display:'flex',flexDirection:'column',gap:18}}><Bubble side="right" accent={C.cyan}>Was hatte mir Max gestern geschrieben?</Bubble><Bubble>Ich kann in Messages danach suchen.</Bubble></div><Chip bg={C.cyanSoft} color={C.blue} style={{marginTop:54}}><Search size={24}/>Suche</Chip></Panel>
  <div style={{height:8,borderRadius:8,background:`linear-gradient(90deg,${C.cyan},${C.blue})`,transform:`scaleX(${link})`,transformOrigin:'left',position:'relative'}}><div style={{position:'absolute',right:-18,top:-18,width:44,height:44,borderRadius:22,background:C.blue,color:C.white,display:'grid',placeItems:'center',transform:`scale(${link})`}}><ArrowRight size={24}/></div></div>
  <Panel style={{height:680,padding:30,transform:`translateX(${(1-p(f,8,28))*55}px)`,opacity:p(f,8,24)}}><div style={{display:'flex',alignItems:'center',gap:14,fontSize:34,fontWeight:950}}><MessageCircle size={35}/>Messages</div><div style={{marginTop:58,display:'flex',flexDirection:'column',gap:18}}><Bubble>Freitag passt. Treffen wir uns um 18 Uhr?</Bubble><Bubble side="right" accent={C.blue}>Perfekt, bis dann.</Bubble></div><Chip bg={C.blueSoft} color={C.blue} style={{marginTop:54}}><MessageCircle size={24}/>Apple Messages</Chip></Panel>
 </div><div style={{position:'absolute',left:0,right:0,top:1210,display:'flex',justifyContent:'center',opacity:badge,transform:`translateY(${(1-badge)*18}px)`}}><Chip bg={C.white} color={C.purple}><Sparkles size={24}/>Plugin verbindet ChatGPT mit Messages</Chip></div></AbsoluteFill>};

export const SearchVisual:React.FC=()=>{const f=useCurrentFrame();const scan=p(f,26,60);const hit=p(f,70,92);const summary=p(f,112,136);return <AbsoluteFill><DotBg accent={C.blue}/><Panel style={{position:'absolute',left:66,right:66,top:270,height:930,padding:34}}>
 <div style={{display:'flex',alignItems:'center',gap:14,fontSize:30,fontWeight:900}}><Search size={32} color={C.blue}/>Suche in Messages</div>
 <div style={{marginTop:30,padding:'18px 22px',borderRadius:22,background:C.blueSoft,fontSize:27,fontWeight:800}}>„Was hatte mir Max gestern wegen Freitag geschrieben?“</div>
 <div style={{marginTop:30,display:'grid',gridTemplateColumns:'320px 1fr',gap:24,height:650}}><div style={{display:'flex',flexDirection:'column',gap:14}}>{['Max','Lea','Team','Familie'].map((n,i)=><div key={n} style={{padding:'20px 18px',borderRadius:20,background:i===0&&hit>.2?C.cyanSoft:'#F7F9FC',border:i===0&&hit>.2?`2px solid ${C.cyan}`:'1px solid rgba(16,32,51,.08)',fontSize:26,fontWeight:850,transform:i===0?`scale(${1+.02*hit})`:undefined}}>{n}</div>)}</div>
 <div style={{position:'relative',borderRadius:24,background:'#F7F9FC',padding:24,overflow:'hidden'}}><div style={{position:'absolute',left:0,top:`${20+scan*72}%`,right:0,height:5,background:`linear-gradient(90deg,transparent,${C.cyan},transparent)`,opacity:scan<1?1:0}}/><div style={{display:'flex',flexDirection:'column',gap:16,opacity:.42+.58*hit}}><Bubble>Freitag passt. Treffen wir uns um 18 Uhr?</Bubble><Bubble side="right">Ja, passt.</Bubble><Bubble>Super. Dann am Alex.</Bubble></div><div style={{position:'absolute',left:24,right:24,bottom:24,padding:20,borderRadius:22,background:C.white,border:`2px solid ${C.green}`,opacity:summary,transform:`translateY(${(1-summary)*18}px)`}}><div style={{fontSize:20,fontWeight:900,color:C.green,marginBottom:7}}>KONTEXT GEFUNDEN</div><div style={{fontSize:25,fontWeight:800}}>Freitag · 18 Uhr · Alexanderplatz</div></div></div></div>
 </Panel></AbsoluteFill>};

export const DraftVisual:React.FC=()=>{const f=useCurrentFrame();const context=p(f,8,28);const draft=p(f,50,88);const ready=p(f,104,128);return <AbsoluteFill><DotBg accent={C.green}/><div style={{position:'absolute',left:70,right:70,top:285,height:880,display:'grid',gridTemplateRows:'190px 1fr',gap:24}}>
 <Panel style={{padding:26,display:'flex',alignItems:'center',gap:16,opacity:context,transform:`translateY(${(1-context)*18}px)`}}><Chip bg={C.blueSoft} color={C.blue}>Freitag</Chip><Chip bg={C.cyanSoft} color={C.blue}>18 Uhr</Chip><Chip bg={C.yellowSoft} color={C.ink}>Alexanderplatz</Chip><div style={{marginLeft:'auto',fontSize:24,fontWeight:900}}>Kontext</div></Panel>
 <Panel style={{padding:32,display:'flex',flexDirection:'column'}}><div style={{fontSize:27,fontWeight:900,display:'flex',alignItems:'center',gap:12}}><Sparkles size={28} color={C.green}/>Antwort entwerfen</div><div style={{marginTop:36,opacity:draft,transform:`translateY(${(1-draft)*20}px)`,display:'flex',flexDirection:'column',gap:18}}><Bubble side="right" accent={C.green}>Perfekt, Freitag um 18 Uhr am Alex passt. Bis dann!</Bubble><div style={{fontSize:22,color:'#526071',fontWeight:700}}>Aus dem gefundenen Chat-Kontext formuliert</div></div><div style={{marginTop:'auto',display:'flex',justifyContent:'center',opacity:ready,transform:`scale(${.92+.08*ready})`}}><Chip bg={C.greenSoft} color={C.green}><CheckCircle2 size={25}/>Antwort vorbereitet</Chip></div></Panel>
 </div></AbsoluteFill>};

export const ApprovalVisual:React.FC=()=>{const f=useCurrentFrame();const stop=p(f,12,34);const recipient=p(f,52,74);const message=p(f,78,100);const approve=p(f,116,142);const send=p(f,154,180);return <AbsoluteFill><DotBg accent={C.orange}/><Panel style={{position:'absolute',left:72,right:72,top:280,height:900,padding:34}}>
 <div style={{display:'flex',alignItems:'center',justifyContent:'space-between'}}><div style={{fontSize:31,fontWeight:950,display:'flex',gap:12,alignItems:'center'}}><ShieldCheck size={34} color={C.orange}/>Freigabe vor Senden</div><Chip bg={C.orangeSoft} color={C.orange}><LockKeyhole size={22}/>Standard</Chip></div>
 <div style={{marginTop:46,display:'grid',gridTemplateColumns:'1fr 100px 1fr',alignItems:'center',gap:16}}><Panel style={{padding:24,background:C.greenSoft,border:`1px solid ${C.green}55`,opacity:stop}}><div style={{fontSize:20,fontWeight:900,color:C.green}}>ENTWURF</div><div style={{marginTop:10,fontSize:25,fontWeight:800}}>„Perfekt, Freitag um 18 Uhr …“</div></Panel><ArrowRight size={46} color={C.orange} style={{justifySelf:'center',opacity:stop}}/><div style={{height:130,borderRadius:26,border:`3px solid ${C.orange}`,display:'grid',placeItems:'center',background:C.orangeSoft,opacity:stop}}><div style={{fontSize:24,fontWeight:950,color:C.orange}}>STOP</div></div></div>
 <div style={{marginTop:40,display:'grid',gridTemplateColumns:'1fr 1fr',gap:22}}><div style={{padding:25,borderRadius:26,background:C.white,border:'1px solid rgba(16,32,51,.09)',opacity:recipient,transform:`translateY(${(1-recipient)*18}px)`}}><div style={{display:'flex',alignItems:'center',gap:11,fontSize:23,fontWeight:900}}><UserCheck size={25} color={C.blue}/>Empfänger prüfen</div><div style={{fontSize:30,fontWeight:950,marginTop:18}}>Max</div></div><div style={{padding:25,borderRadius:26,background:C.white,border:'1px solid rgba(16,32,51,.09)',opacity:message,transform:`translateY(${(1-message)*18}px)`}}><div style={{display:'flex',alignItems:'center',gap:11,fontSize:23,fontWeight:900}}><MessageCircle size={25} color={C.purple}/>Nachricht prüfen</div><div style={{fontSize:24,fontWeight:800,marginTop:18}}>Inhalt bestätigen</div></div></div>
 <div style={{marginTop:38,display:'flex',justifyContent:'center'}}><div style={{display:'inline-flex',alignItems:'center',gap:14,padding:'19px 28px',borderRadius:999,background:approve>.95?C.green:'#D8DEE7',color:approve>.95?C.white:'#718096',fontSize:28,fontWeight:950,transform:`scale(${.96+.04*approve})`}}>{approve>.95?<Check size={28}/>:<LockKeyhole size={28}/>}Freigabe</div></div>
 <div style={{marginTop:32,height:84,display:'flex',justifyContent:'center',alignItems:'center',opacity:send}}><Chip bg={C.blue} color={C.white}><Send size={25}/>Senden</Chip></div>
 </Panel></AbsoluteFill>};

export const WorkflowVisual:React.FC=()=>{const f=useCurrentFrame();const availability=p(f,10,40);const flow=p(f,52,150);const final=p(f,164,190);const steps=[['Suche',Search,C.blue],['Kontext',MessageCircle,C.cyan],['Entwurf',Sparkles,C.green],['Freigabe',ShieldCheck,C.orange],['Senden',Send,C.purple]] as const;return <AbsoluteFill><DotBg accent={C.purple}/><div style={{position:'absolute',left:66,right:66,top:280}}>
 <div style={{display:'flex',justifyContent:'center',gap:15,opacity:availability}}><Chip bg={C.white}><Monitor size={23}/>macOS Desktop</Chip><Chip bg={C.white}><BriefcaseBusiness size={23}/>alle Tarife</Chip><Chip bg={C.white}><Code2 size={23}/>Work + Codex</Chip></div>
 <Panel style={{marginTop:44,padding:34,height:620}}><div style={{fontSize:28,fontWeight:950,marginBottom:44}}>Der neue Workflow</div><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:10}}>{steps.map(([label,Icon,color],i)=>{const local=p(f,52+i*18,76+i*18);return <React.Fragment key={label}><div style={{width:150,opacity:local,transform:`translateY(${(1-local)*18}px)`}}><div style={{width:76,height:76,borderRadius:24,margin:'0 auto',display:'grid',placeItems:'center',background:`${color}18`,color}}><Icon size={38}/></div><div style={{textAlign:'center',marginTop:16,fontSize:22,fontWeight:900}}>{label}</div></div>{i<steps.length-1?<ArrowRight size={26} color="#93A0B2" style={{opacity:p(f,68+i*18,86+i*18)}}/>:null}</React.Fragment>})}</div><div style={{marginTop:70,height:12,borderRadius:999,background:'#E7EBF0',overflow:'hidden'}}><div style={{height:'100%',width:`${flow*100}%`,background:`linear-gradient(90deg,${C.blue},${C.cyan},${C.green},${C.orange},${C.purple})`}}/></div></Panel>
 <div style={{marginTop:42,display:'flex',justifyContent:'center',opacity:final,transform:`translateY(${(1-final)*18}px)`}}><Chip bg={C.white} color={C.purple}><Sparkles size={25}/>ChatGPT arbeitet direkt mit deiner App</Chip></div>
 </div></AbsoluteFill>};
