import type {AuthoredVisualScene} from '../../animation-library/authoredProductionGate';

export const AMBIGUOUS_PROMPTS_VISUAL_PROFILES: readonly AuthoredVisualScene[] = [
  {
    sceneId: 'ambiguous-01',
    visualId: 'ambiguous-branching-field-v2',
    fingerprint: {
      primaryPrimitive: 'path',
      cameraMotion: 'push',
      depthStyle: 'layered-2d',
      entryMechanism: 'draw',
      medium: 'remotion-native',
      direction: 'center-out',
      visualFamily: 'ambiguity-branching',
      layoutFamily: 'prompt-core-branch-field',
      motionSignature: 'prompt-establish-paths-branch-options',
    },
  },
  {
    sceneId: 'ambiguous-02',
    visualId: 'ambiguous-interpretation-dial-v2',
    fingerprint: {
      primaryPrimitive: 'chart',
      cameraMotion: 'parallax',
      depthStyle: 'flat',
      entryMechanism: 'assemble',
      medium: 'remotion-native',
      direction: 'circular',
      visualFamily: 'interpretation-choice',
      layoutFamily: 'radial-interpretation-dial',
      motionSignature: 'dial-build-pointer-scan-target-miss',
    },
  },
  {
    sceneId: 'ambiguous-03',
    visualId: 'ambiguous-constraint-funnel-v2',
    fingerprint: {
      primaryPrimitive: 'path',
      cameraMotion: 'pull',
      depthStyle: 'pseudo-3d',
      entryMechanism: 'mask',
      medium: 'remotion-native',
      direction: 'outside-in',
      visualFamily: 'constraint-collapse',
      layoutFamily: 'layered-constraint-funnel',
      motionSignature: 'constraints-enter-routes-converge-result',
    },
  },
  {
    sceneId: 'ambiguous-04',
    visualId: 'ambiguous-example-blueprint-v2',
    fingerprint: {
      primaryPrimitive: 'illustration',
      cameraMotion: 'parallax',
      depthStyle: 'layered-2d',
      entryMechanism: 'morph',
      medium: 'remotion-native',
      direction: 'top-to-bottom',
      visualFamily: 'example-anchoring',
      layoutFamily: 'dual-document-blueprint-output',
      motionSignature: 'prompt-example-align-blueprint-build',
    },
  },
  {
    sceneId: 'ambiguous-05',
    visualId: 'ambiguous-three-step-path-v2',
    fingerprint: {
      primaryPrimitive: 'object',
      cameraMotion: 'pan',
      depthStyle: 'flat',
      entryMechanism: 'draw',
      medium: 'remotion-native',
      direction: 'left-to-right',
      visualFamily: 'prompt-structure',
      layoutFamily: 'three-milestone-pathway',
      motionSignature: 'route-draw-milestones-activate-finish',
    },
  },
] as const;
